### ISSUE TITLE
Face datasets

### ISSUE THREAD

**Issue by Ganonmaster** [deepfakes/faceswap-playground#1]
[Here is a folder containing the cage and trump faces, as well as a few faces I've gathered.](https://jansenh.stackstorage.com/s/UayUugaE0GSda0y) So far it includes Phoenix Marie, Hillary Clinton, Charlize Theron.

**Comment by Ganonmaster** [comment]
You'll notice that it fails to properly detect phoenix marie's face in a few frames, causing the glitch in between the frames. I'm not sure what would work better for cases like that: interpolation of face positions between frames, or just better face detection in general.

**Comment by Yutsa** [comment]
Could we create like a repo to store datasets ? I have gathered Jena Coleman faces and I'd love to share them.

**Comment by Apollo122** [comment]
@Yutsa It's a good idea but how can we know their quality? Should we ask a preview, what are our options? Because if we accept any data pushed, repo will turn into a garbage pile in no time.

**Comment by Yutsa** [comment]
Yeah I understand the issue. Maybe something where every upload must be approved to be visible ? The best thing would be a vote system and if a dataset has enough positive votes it's made available to the official data set repository/website.

But I don't know if something like this exists already or not

**Comment by Ganonmaster** [comment]
You could upvote/downvote issues and pull requests with emotes. If you have a dataset to add, or expand upon, you could do so via pull requests. However, I see several problems.

Github has a file size limit per account/organisation. Basically if the repository grows larger than 1-2GB, it's time to pay up. I'm not sure if I would go that route. I can't speak for @deepfakes ofcourse.

Also note that the pictures are made by other people and the faces we use are processing are those of actual people. Both groups have rights. Copyright being one of them. In the Netherlands there is also what is known as `Portretrecht` (portrait right) which allows the person who is portrayed in a picture to object against the publication of said picture. If the picture is copyrighted, or if the person in the picture were to object, you'd have to take it down or otherwise face consequences. This would be a problem for both a website or a github repository.

**Comment by Apollo122** [comment]
files can be uploaded anonymously. we do the downvote/upvote in reddit and upload the approved ones to mega.nz

**Comment by Clorr** [comment]
A resource link: https://www.reddit.com/r/deepfakes/comments/7nh94g/datasets_for_a_few_pornstars_and_celebrities/
