### ISSUE TITLE
Suggestions please to improve!

### ISSUE THREAD

**Issue by nerdprogrammergm** [deepfakes/faceswap-playground#10]
![image](https://user-images.githubusercontent.com/20768297/34389575-63dfb41e-eb60-11e7-9d6d-21e691dfb1ea.png)

This is what I am getting after training my models for around 32 hours!
Also how can I remove this blur square/rectangle frame?

**Comment by Ganonmaster** [comment]
At this time, there are no controls for the blur. We can work on improving that part, but at this time it is one of the limits of this version. We can work to improve two things here: blending the face better or adding options to tweak the blur values.

**Comment by nerdprogrammergm** [comment]
Okay, was trying to work on this blur part, found this link.
Do share your experience and result(image).
https://gist.github.com/anonymous/d3815aba83a8f79779451262599b0955

**Comment by Ganonmaster** [comment]
Please look at the existing code as well. It already has a few values that you can tweak to adjust your results.
