### ISSUE TITLE
cannot create frames when converting videos

### ISSUE THREAD

**Issue by ydengizea** [deepfakes/faceswap-playground#101]
hi, I installed the [myfakeapp](https://radek350.wordpress.com/2018/02/17/myfakeapp-fakeapp-alternative/) to play with it. Everything works fine except converting videos. It had error saying 'cannot create frames'. Does anyone have the same issue? 

Thanks a lot!

**Comment by andykdy** [comment]
As stated in your previous issue, the code in myfakeapp is outdated and not really relevant to this repository

**Comment by bryanlyon** [comment]
Very few of the people here have ever used myfakeapp so we can't help you with it.

You can still use the command line to convert the frames with your existing models.  Please read the usage.md in the main github for instructions on how to do it.

**Comment by ydengizea** [comment]
Thanks guys
