### ISSUE TITLE
Which loss is good enough

### ISSUE THREAD

**Issue by HugoGranstrom** [deepfakes/faceswap-playground#104]
At which loss is it reasonable to expect good result? Not necessarily fantastic results but good enough to not just being a blurry copy-paste.

**Comment by bryanlyon** [comment]
Don't rely on the loss numbers.  Look at the previews (enable it off disabled to check).  Loss numbers aren't really a measure of how it looks and you have to make a subjective decision.

**Comment by HugoGranstrom** [comment]
The problem is that the only GPU I have access to is only accessable from a online Jupyter notebook so the preview (openCV) doesn't work in my case. If I try to run it with the `-p` option it raises an error about "x server" not available. Would it be possible to add a Jupyter-friendly preview?

**Comment by Clorr** [comment]
If you look at the bottom of the scripts/train.py, there is a display function. You certainly can plug the jupyter image disply there. If you use faceswap from jupyter, it would be welcome if you push a PR with usable notebooks

**Comment by torzdf** [comment]
Could you not just allow x-forwarding from the Jupyter notebook and ssh in?

*NB I know nothing of Jupyter so could be way off.

**Comment by 3xtr3m3d** [comment]
@HugoGranstrom what i do in jupyter notebooks is use -w option to write preview to image file and view it time to time for results

**Comment by HugoGranstrom** [comment]
@3xtr3m3d Good idea. Will try it ;-) Thank you.
