### ISSUE TITLE
No module named 'face_recognition'

### ISSUE THREAD

**Issue by Binbose** [deepfakes/faceswap-playground#106]
I tried to setup the system as described here: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md
When I want to run 
`python faceswap.py -h `
I get the following error message:

```
Traceback (most recent call last):
  File "faceswap.py", line 8, in <module>
    from lib.cli import FullHelpArgumentParser
  File "D:\gitfaceswap\faceswap\lib\cli.py", line 7, in <module>
    from lib.FaceFilter import FaceFilter
  File "D:\gitfaceswap\faceswap\lib\FaceFilter.py", line 3, in <module>
    import face_recognition
ModuleNotFoundError: No module named 'face_recognition'
```

did I miss doing something, or why is the module not included?

**Comment by Clorr** [comment]
Face_recognition is part of all requirements*.txt. Have you installed requirements with pip install -r requirements-....txt?

**Comment by Binbose** [comment]
I did conda install --yes --file requirements-python36.txt
Does that not have the same effect?

**Comment by Binbose** [comment]
Ok, I am too stupid to read error messages, it gave me:

PackagesNotFoundError: The following packages are not available from current channels:

  - opencv-python==3.3.0.10
  - tensorflow==1.5.0
  - face_recognition
  - dlib

But why?

**Comment by waltergammarota** [comment]
You might be having an error in the process of installing the packages in the requirements file, by installing the packs like you're doing (conda install --yes --file requirements-python36.txt) if one fails, all dependencies will fail to install. 

Try to run this instead: 

`while read requirement; do conda install --yes $requirement; done < requirements-python36.txt 2>error.log`

And later check the error.log file, to detect what's going wrong with your installation.

Good luck!
