### ISSUE TITLE
represent array of 68 2D points as histogram to filter faces?

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#108]
Is there way to represent 68 points alignments as histogram like

![chrome_2018-03-21_10-29-27](https://user-images.githubusercontent.com/8076202/37696904-1376ee32-2cf3-11e8-9d36-9c1d5069ab51.png)

will it help to cut unnecessary faces to make faceset more regular and better for nn?

**Comment by Clorr** [comment]
I think this is what was the 1st intention in https://github.com/deepfakes/faceswap/issues/123 . I agree it would be good to have this to be able to compare 2 facesets before starting training

**Comment by Clorr** [comment]
There are various examples around. I don't know if you have found some interesting ones. Maybe this one can help: https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_dlib_pnp_head_pose_estimation_video.py (One guy tried here to output the values as angles: https://github.com/mpatacchiola/deepgaze/issues/40)

**Comment by iperov** [comment]
solved
