### ISSUE TITLE
Any one know how to change current model  64x64pxl model to 128x128 pxl?? 

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap-playground#109]
Does any one know how to change the current faceswap 64x64pxls original models to 128x128pxls models?? if possible share the code??

**Comment by bryanlyon** [comment]
There has been some experimental work, but it requires a castle not complex model to get good results.  You need to increase the dimensions and the layers of the model to change the resolution.  Right now, most of us are working on perfecting what we have before we build out new models.

**Comment by Clorr** [comment]
[This commit](https://github.com/Clorr/faceswap/commit/cd6b5401266444a3598052c18f175f0d0bf4d04e) and [this issue](https://github.com/deepfakes/faceswap/issues/247) are about pushing output up to 256x256. This does not bring much improvments, but you can try
