### ISSUE TITLE
Converted faceswap looks really different from training preview (Beginner) 

### ISSUE THREAD

**Issue by egf54** [deepfakes/faceswap-playground#11]
New to deep learning and programming in general (couple months of basic programming knowledge), so my perspective is limited and I'm learning as I go. But I'm trying to understand what's going on in this case:

I have a fairly well trained model (16-20+ hours on a 980ti with 5.2 compute capability), from the preview window the results are visually satisfactory I think: https://i.imgur.com/uYoHRS6.png . Maybe the images are cropped too closely to the face? I used the extract script from this project without modifying anything.

But when I run faceswap convert, the image that is created is noticeably lower quality:  https://i.imgur.com/1FcgV9V.png

Furthermore, I'm also curious about why the converted area in the image is seemingly so small, as I roughly highlighted here: https://i.imgur.com/6uhzcQ9.png

My knowledge is very limited, but I imagine this is not a simple issue if it isn't already fixed. I'm not asking for a tutorial, but maybe some pointers in the right direction, about what affects the size of the converted area on a detected face, which parameters to play with, etc.

**Comment by Ganonmaster** [comment]
The face detection is still kind of iffy at times.

Basically, the first step of the conversion process detecting an area that contains the face. It will then crop around the face area and apply the deep learning model. Lastly, it will apply a slight blur/smoothing around the edges. It's the first step where this specific image goes wrong. It draws a rectangle around the most outer parts where it detects features that are "like a face." It seems like the most outer edge it detects in this case is the eye. So anything outside of that point is not considered for swapping.

In addition, it seems to blur part of the outer edge too, revealing the eye of the original actor underneath. One thing you can try, is disable the blur effect, to see the outline of the crop more clearly. It won't solve your problem, but may provide some clarity as to the area that it detects as a face. There is no command line option for this yet, but if you look in `lib/faces_process.py` you will find a line that says `use_smooth_mask=True,` - this means that it will use the smoothing mask by default. On that line, replace `True` with `False` - this should disable the smoothing mask for the next time you run the command. (note that these lines are case sensitive)

There are several other projects we are looking to integrate with this project that would potentially improve the face detection. Take a look at some of the other issues on the faceswap-model and faceswap repositories to see what can be improved.

**Comment by shaoanlu** [comment]
Regarding the converted area, Modify a line of `random_warp()` in `image_augmentation.py` will give larger coverage of input image. 
``` python
def random_warp( image ):
    assert image.shape == (256,256,3)
    # range_ = numpy.linspace( 128-80, 128+80, 5 ) # original one
    range_ = numpy.linspace( 128-110, 128+110, 5 ) # modified one
    ...
```
Also, since the output image size is fixed to 64 x 64, the swapped face will always looks blurry when source image is large.

**Comment by Yutsa** [comment]
I also have issues with results from convert sometimes where the detected zone is really small and the result is really bad whereas results in the training were great.

How could we improve that ? Is it only because of the face detection ?

**Comment by Ganonmaster** [comment]
Yes, that is primarily a face-detection thing.

**Comment by Yutsa** [comment]
It's weird it worked really well before and it looks like it has gotten worse, even processing the same video as I had before.

**Comment by Gastel71** [comment]
I think I have almost the same problem with the latest version on the master branch. The preview of the trained model is visually perfect with cost function values under 0.01. Unfortunately when running the convert script the results are abysmal, almost like it is using an aproxximate model or a very low res source/target image. The results are bad regardless of the options used (blur, kernel size etc. and the adjust convert produces a bunch of random pixels on the target faces by the way). Additionaly if the target is moving, even slightly, the swapped face jitters a lot. Any help would be much appreciated.
