### ISSUE TITLE
how to change the number of nodes and layers in the training process?

### ISSUE THREAD

**Issue by vamzii** [deepfakes/faceswap-playground#110]
i was able to train the model and stuff,
was able to change the batch size, but where can i change the number of layers and nodes?

**Comment by Clorr** [comment]
This has been discussed around already like here : https://github.com/deepfakes/faceswap/issues/117

**Comment by deepfakesclub** [comment]
I have users regularly swear that they use something like 1024 nodes AND 1024 layers simultaneously in FakeApp for really good results. This is just patently absurd. I am skeptical FakeApp does anything other than truncate the original model LowMem style for lower settings.
