### ISSUE TITLE
How to save only the new face on a black background ?

### ISSUE THREAD

**Issue by Cybrak** [deepfakes/faceswap-playground#111]
Hello, 
I would like to be able to save the generated face on a black background instead of the original image. (easier to properly comp it afterwards) Any idea what lines do I need to change to do that  ? 
Thanks !!
Or maybe save the mask ?

**Comment by Clorr** [comment]
It depends if you have some python background or not. If not, there is no default way to do that. However if you know a bit of python, you can have a look at the Adjust converter (`-c Adjust`) which is not so complicated. You will see that there is an `original` var that you can replace by an empty black picture/array

**Comment by Clorr** [comment]
But note that the model will output a square image with a part of background, if you really want only the face, you will have to check how it is done in the Masked converter and tackle more lines of code to just get the good matrix

**Comment by Cybrak** [comment]
Thanks Clorr, I'll have a look at that script tonight !
Would it work to just multiply the rgb values of _original_ by 0 before adding the face on top ? I tried to do that to _image_ in the _converter.patch_image_  step of _convert.py_ but the face was affected.

**Comment by bryanlyon** [comment]
You have to make sure to change the image after it removes the face but before it patches it into the original image.  Though since you're using opencv, instead of black, I'd use transparent.  Just add an alpha channel and save as a png.
