### ISSUE TITLE
I am going to create a new training, but getting "Failed loading existing training data" ??? 

### ISSUE THREAD

**Issue by junanyeap** [deepfakes/faceswap-playground#112]
Error Code
`Failed loading existing training data.
Unable to open file (unable to open file: name = '/home/junan/fakes/model/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

And this is my command line to start training, correct me if any wrong.
`
python3 faceswap.py train -A ~/fakes/data/a -B ~/fakes/data/b -m ~/fakes/model/ -p -v -s 100 -w -t LowMem -pl -bs 32 -ep 10000 -g 1
`

Spec:
- 
- i5 5200u
- GT920m
- 4GB ram
- 128GB ssd
- ubuntu 16.04

![screenshot from 2018-03-23 22-42-48](https://user-images.githubusercontent.com/25972862/37835625-91a1a7c6-2eeb-11e8-921f-eef4d1c4bc58.png)

Update: I found that it was the problem of "out of memory" in dmesg
![screenshot from 2018-03-24 19-08-11](https://user-images.githubusercontent.com/25972862/37863297-12551618-2f97-11e8-8736-6e486edb9a03.png)

Thanks for helping, sorry for my poor English.

**Comment by junanyeap** [comment]
i have tried delete the model dir, but not working

**Comment by bryanlyon** [comment]
It looks like it's not finding the file.  If you don't have one that is normal.  Just let it run and it'll create the file.  Just make sure the folder already exists.

**Comment by junanyeap** [comment]
@bryanlyon  hello, in "model" dir I don't have the one that is normal, and this is the error result from the command that would (might? )create the encoder.h5 in ~/fakes/model/. 
As you mean, if I have encoder.h5 before start training, it might be work fine ?

**Comment by bryanlyon** [comment]
If you're creating a new model, it's normal to not have the files there.  It will create the files if you let it run.

**Comment by junanyeap** [comment]
So the problem is when I start a new train, program would searching existing encoder instead of create new encoder.
Any idea to fix?

**Comment by bryanlyon** [comment]
Just run it for a while and it should work.  Don't cancel it.

**Comment by junanyeap** [comment]
It showed up "killed" after few seconds.
