### ISSUE TITLE
Only Lowmem works on a 4GB graphic card?

### ISSUE THREAD

**Issue by ntmatter1** [deepfakes/faceswap-playground#114]
I have a 1050 Ti, 4GB, and only the LowMem setting seems to work, I get the Resource exhausted: OOM when allocating tensor with shape[64,2048,4,4] error when running without the LowMem flag.   Would this maybe be a driver issue?  Tried using latest driver, but maybe there's a setting or something?  Task Manager shows 3.8GB of out 4.0 dedicated mem in use, very little shared mem in use, 68% card utilization.  Driver version is 23.21.13.9077.

**Comment by mul5kuq5pn** [comment]
What is the exact error msg?
Could also be warning in the sense of "I'd like to have more memory but what I have is fine".
I don't think it's a driver issue. But having the latest is a good idea: https://www.nvidia.com/Download/index.aspx?lang=en-us

**Comment by bryanlyon** [comment]
Original doesn't work on 4gb right now due to dlib.  The import patch which is coming soon should fix that, but for now you need 6gb for it.

**Comment by ntmatter1** [comment]
Got it, thanks.  It grinds away on LowMem so it functions, I was just hoping for an alternative since I have a 4GB card.  Trying to figure out if going to a 1080 is going to be worth it.

**Comment by bryanlyon** [comment]
Unless you're making money off it, I wouldn't buy a 10xx series card right now, especially with Volta coming down in price this year or Turing coming out q3.

4gb original should be working again within a few days.

**Comment by ntmatter1** [comment]
One more note on this - if you use LowMem on the training, you have to use LowMem on the converting too.  That only took about 2 hours to figure out.

**Comment by deepfakesclub** [comment]
@bryanlyon 
Tell me about it... I missed the last two Nvidia site inventory drops, hit the final order "submit" button only to be told it's out of stock again. Missed a couple super cheap Amazon Warehouse Deal drops the same way (the new ones seemed to be priced higher than before).

I'm starting to see SOME local miners unload cards, but not too many. Local resale prices are SLOWLY starting to go down.

News of unconfirmed 20xx release dates around the corner.

What to do, what to do... I just want a cheap 1080.

**Comment by bryanlyon** [comment]
Honestly, the best way for a cheap 1080 is an Aorus gaming box.  Not too outrageous in price and works well, even for a laptop or a Cuda only add-on because of the external box.

Seriously, they're not great for mining due to cooling, but they work well enough for games and Cuda, plus you can shell it to make it internal if you want.

**Comment by iperov** [comment]
> Original doesn't work on 4gb right now due to dlib

model doesnt depend on dlib.
Extractor works ok with 3GB.

**Comment by torzdf** [comment]
> model doesnt depend on dlib.

But dlib takes up RAM even if it isn't being used, due to the fact that it gets default imported, and it is a GPU RAM hog. I have raised a PR to hopefully fix this.

**Comment by iperov** [comment]
> But dlib takes up RAM even if it isn't being used

no, you are wrong.

**Comment by hank32601** [comment]
Same here, I was able to convert GAN128 with my 1050TI 4G, but after I installed cuda9 just to try it, I was not able to convert with GPU anymore. Not with cuda9, cuda91 or cuda8. I also tried all libcudnn (6, 7.0, 7.1) in all combinations with cuda an nvidia-drivers (275, 384, 390)

I see a short GPU usage around 40% and an estimated time of 19min but after 2 pics it pauses, an the estimated time jumps up to 20h.

I also went back a few commits (faceswap and dlib), no change.

I tried torzdfs PR, no change.

My system is Ubuntu 16.04, 4G Ram, 1050TI 4G.

**Comment by iperov** [comment]
I am making global refactoring.
Currently I have extract and train working on 2GB card GT 730.

**Comment by iperov** [comment]
![cmd_2018-03-31_12-36-40](https://user-images.githubusercontent.com/8076202/38161478-8ee17c14-34e0-11e8-8a8e-ae1bdf87f24c.png)

![123](https://user-images.githubusercontent.com/8076202/38161480-92702b82-34e0-11e8-826f-954615e22fcc.png)

**Comment by iperov** [comment]
perfect

![nvidia share_2018-03-31_20-15-56](https://user-images.githubusercontent.com/8076202/38165297-60d4a4d0-3522-11e8-8ddd-f639277ca7e3.jpg)

**Comment by ntmatter1** [comment]
Is there a way with Cuda 9 and cudnn 7.0 to get it to work on anything other than the LowMem setting on a 1050 Ti 4GB?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bryanlyon** [comment]
@iperov While we encourage discussion (and even disagreement), we do not appreciate the mockery, hostility and arguments that you bring up.

Reducing RAM usage is a goal across the project, there is no reason to be hostile to alternate solutions.  We appreciate your ability and nobody has said you can't come up with other options or ways of doing it.  But DLIB does use a massive amount of vram (in my explorations as much as 1gb).  There is no reason that we can't implement your method if it is better, but replies like you're giving here are inappropriate.  Please stop being hostile and understand that we all care about the project, we just have different opinions and we need to respect each other's.

**Comment by iperov** [comment]
@quadlol check https://github.com/iperov/OpenDeepFaceSwap
H64 (2GB+) 
H128 (3GB+)
DF (4GB+)
