### ISSUE TITLE
Error while reading image', '/image/.xyz.png' on MacOS

### ISSUE THREAD

**Issue by DrDreGFunk** [deepfakes/faceswap-playground#116]
Mac OS High Sierra
Mac: 10.13.2
Python 3.5 :: Anaconda custom (64-bit)
Using CPU
Processor: 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3

For some reason, this started happening. This hasn't happened before and last time it worked perfectly. Also the error at the bottom:
"Exception: ('Error while reading image', '/Volumes/My Passport/Deepfakes/faceswap-master/Cage_Faces/._CageFace0863.png')"
^^ The image is readable and it just does this randomly to any other image every time I retry this process. 

WHAT IT SAYS IN THE TERMINAL:
------------------------------------------------------------------------------------------------------
(faceswap) MY NAME-MacBook-Pro-3:faceswap-master MY NAME$ python faceswap.py train -A Video_faces -B Cage_Faces -m model -p

/Users/MY NAME/anaconda3/envs/faceswap/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

  from ._conv import register_converters as _register_converters

Using TensorFlow backend.

Model A Directory: /Volumes/My Passport/Deepfakes/faceswap-master/Video_faces

Model B Directory: /Volumes/My Passport/Deepfakes/faceswap-master/Cage_Faces

Training data directory: /Volumes/My Passport/Deepfakes/faceswap-master/model

Loading data, this may take a while...

Loading Model from Model_Original plugin...

Using live preview

2018-03-27 12:28:03.240899: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA

loaded model weights

Loading Trainer from Model_Original plugin...

Starting. Press "Enter" to stop training and save model

Exception in thread Thread-3:

Traceback (most recent call last):

  File "/Volumes/My Passport/Deepfakes/faceswap-master/lib/training_data.py", line 41, in read_image

    image = self.color_adjust(cv2.imread(fn))

  File "/Volumes/My Passport/Deepfakes/faceswap-master/lib/training_data.py", line 37, in color_adjust

    return img / 255.0

TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Users/MY NAME/anaconda3/envs/faceswap/lib/python3.5/threading.py", line 923, in _bootstrap_inner

    self.run()

  File "/Volumes/My Passport/Deepfakes/faceswap-master/lib/utils.py", line 62, in run

    for item in self.generator:

  File "/Volumes/My Passport/Deepfakes/faceswap-master/lib/training_data.py", line 32, in minibatch

    rtn = numpy.float32([self.read_image(img) for img in data[i:i+size]])

  File "/Volumes/My Passport/Deepfakes/faceswap-master/lib/training_data.py", line 32, in <listcomp>

    rtn = numpy.float32([self.read_image(img) for img in data[i:i+size]])

  File "/Volumes/My Passport/Deepfakes/faceswap-master/lib/training_data.py", line 43, in read_image

    raise Exception("Error while reading image", fn)

Exception: ('Error while reading image', '/Volumes/My Passport/Deepfakes/faceswap-master/Cage_Faces/._CageFace0863.png')

**Comment by Clorr** [comment]
As you can see in your error message, the file name begins with a `.` This is not your image, it is the thumbnail that macOS generates for the quick preview. You won't see them in finder but python will take them as inputs. I usually type `rm .*.jpg` in the folder to remove them (NB: This command deletes files, so you should use it with care). We should add some filter to avoid reading them but I did not tackle this yet

**Comment by DrDreGFunk** [comment]
@Clorr Ok and thank you for your response. I'll sit tight for now as I don't want to mess anything up and see if a solution for it comes up eventually.

**Comment by bryanlyon** [comment]
It's safe to delete the extra files, just make sure you're in the right folder before you do it is all.

It may look like there are multiple errors, but in fact you actually only have one error in those messages.  The rest are all just more information to help us debug the error.

**Comment by DrDreGFunk** [comment]
I got it working! I just deleted all the .png files and just started again.

**Comment by DrDreGFunk** [comment]
@Clorr I just want to clarify, is it better to use FakeApp or is it the same without using it? Because I don't know whether I should go to my windows laptop and use it or not.
