### ISSUE TITLE
opencv error. where should I put the picture?

### ISSUE THREAD

**Issue by raksasaa** [deepfakes/faceswap-playground#12]
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Failed to extract from image: input\a.jpg. Reason: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

I put an image in: input\a.jpg
here is my source dir:

```
2017/12/29  23:10    <DIR>          .
2017/12/29  23:10    <DIR>          ..
2017/12/29  08:52                19 .dockerignore
2017/12/29  08:52    <DIR>          .github
2017/12/29  08:52                67 .gitignore
2017/12/29  08:52    <DIR>          contrib
2017/12/29  21:35    <DIR>          data
2017/12/29  08:52               600 Dockerfile
2017/12/29  08:52               734 faceswap.py
2017/12/29  21:43    <DIR>          input
2017/12/29  08:52             5,740 INSTALL.md
2017/12/29  21:44    <DIR>          lib
2017/12/29  21:35    <DIR>          models
2017/12/29  22:33    <DIR>          output
2017/12/29  08:52             5,432 README.md
2017/12/29  08:52               134 requirements-gpu.txt
2017/12/29  08:52               130 requirements.txt
2017/12/29  21:43    <DIR>          scripts
2017/12/29  08:52             5,885 USAGE.md
```

**Comment by Ganonmaster** [comment]
What size is your image? Width? Height?

**Comment by raksasaa** [comment]
500 * 610

I also tryed ：

```
D:\code\python\faceswap>python faceswap.py convert -i D:\code\python\faceswap\input -o  D:\code\python\faceswap\output  -m D:\code\python\faceswap\models
```

But it doesn't work neither

**Comment by Ganonmaster** [comment]
What happens if you were to save it in a different format and convert it again; like PNG for example?

**Comment by raksasaa** [comment]
For PNG : nothing changed
For BMP: cannot find files

**Comment by Ganonmaster** [comment]
What if you end the model part of the command with a `\`?

ie. `python faceswap.py convert -i D:\code\python\faceswap\input -o  D:\code\python\faceswap\output  -m D:\code\python\faceswap\models\`

**Comment by raksasaa** [comment]
my fault

the script told me to download  shape_predictor_68_face_landmarks.dat    and put it to contrib.

Now I get this:

![b](https://user-images.githubusercontent.com/11160538/34454740-b869d16a-edac-11e7-8b7f-bea25738bc13.jpg)

.......

**Comment by raksasaa** [comment]
more:
![untitled134](https://user-images.githubusercontent.com/11160538/34454768-577384ae-edad-11e7-98d1-43d28ac20713.png)
:
![thkp7986kx](https://user-images.githubusercontent.com/11160538/34454763-3cff3a8c-edad-11e7-91a7-37dc825fe439.jpg)

**Comment by raksasaa** [comment]
I guess：

sample picture A/B should be  as similar as possible.
