### ISSUE TITLE
Using -e Seems to Override -S

### ISSUE THREAD

**Issue by ghost** [deepfakes/faceswap-playground#123]
I'm trying out all the arguments in extraction one-by-one and mixing them to see the effects.
It seems like when using the erosion, specifically -e -10, the seamless argument -S seems to be overridden.

This seems to be obvious in some ways, but is it supposed to be doing that? Just wondering.

**Comment by Kirin-kun** [comment]
What does -e and -S have to do with extraction? It concerns conversion.

And I used them several time and if -S was missing, I(d have seen it immediately. 

If I read the code, I see that erosion is applied first, then blur and finally seamless clone.

Maybe if the dilation is too high, then the effect of seamless clone is lost?

But, I have to say the code of negative erosion is poor.

I may not be a programming expert, but this code is redundant:

```
if erosion_kernel_size is not None:
            if erosion_kernel_size > 0:
                self.erosion_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(erosion_kernel_size,erosion_kernel_size))
            elif erosion_kernel_size < 0:
                self.erosion_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(abs(erosion_kernel_size),abs(erosion_kernel_size)))
```
absolute value is the same in both cases. So it could be replaced by:
```

if erosion_kernel_size is not None:
            self.erosion_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(abs(erosion_kernel_size),abs(erosion_kernel_size)))
```
