### ISSUE TITLE
How to make Model_GAN256?

### ISSUE THREAD

**Issue by bigsea00001** [deepfakes/faceswap-playground#127]
I copied Model_GAN128 and renamed Model_GAN256. After that, I changed 128 related digits to 256, adjusted the upscale_ps or res_block numbers, but the following error occurred. I wonder if the way I do is wrong. Is there a good way?

ValueError: Operands could not be broadcast together with shapes (256, 256, 32) (256, 256, 16)

**Comment by bryanlyon** [comment]
All layers outputs need to match the best layers inputs and size.  Right now, you have two layers that aren't matching correctly.  You need to make them match together for it to work.

That said, I think you'll be disappointed in these results.  You're asking the ai to do 4x the pixels without having given it more neurons to work with.  You'll really need to increase each layer size by 2-4x to get better results.  But then you'll need more vram than you can get in a consumer card.

**Comment by ruah1984** [comment]
GTX 1080TI can is it enough to support 256??

**Comment by bigsea00001** [comment]
Bryanlyon, many thanks for your reply.
but, I have done all the adjustments to the numbers I can, but now I am abandoned because of an error. If I succeed, I will leave a message here.

ruah1984, I think it seems possible if you lower the BATCH_SIZE in the training process.

**Comment by iperov** [comment]
what you need 256 ?

**Comment by bigsea00001** [comment]
Because, I need more good qulity~

**Comment by iperov** [comment]
Good quality not depends on resolution of model.
I proved it depends on what sample types feeded into NN.

Result of almost twice reduced 64 model
https://www.youtube.com/watch?v=EVG13JU31d8

vs 64 original full https://www.youtube.com/watch?v=Va9JLpkCUBs

**Comment by gessyoo** [comment]
iperov, you've got some good insights that most of us folks don't.  I'm also interested in a quality result.  Will you share your improved model?

**Comment by ruah1984** [comment]
@iperov  are you using dfaker or retrain model ( Clorr version) ?
what have you change??

**Comment by iperov** [comment]
I will share here https://github.com/iperov/DeepFaceSwapper.
I working every day on it.

**Comment by ruah1984** [comment]
@iperov ,i also think you soon will out from the old "organization group" . haha.
keep in works, i also want to know how far the Deepfake can become more advance. 
this new technology will change the Movie industry soon.

**Comment by Kirin-kun** [comment]
I never ever got good result with GAN anyway. The loss_DA never went under 0.12xx even though I tried to match the poses from A and B. I don't know what the conditions are to have something acceptable. Probably a very carefully selected data set.

I consider this model broken. Only the Original (and probably DF) give something that looks good. Eventually Iperov's improvements on these models will make them better, but that will be in his own repo.
