### ISSUE TITLE
convert settings

### ISSUE THREAD

**Issue by hutauf** [deepfakes/faceswap-playground#128]
When I faceswap, there are sharp corners between the original content and the inserted new faces. I tried some parameters, but it doesn't really get any better. Are there any recommendations for these parameters?

--blur-size
--seamless
--mask-type
--erosion-kernel-size
--match-histogram
-sh
--smooth-mask
--avg-color-adjust

Which one is good, which settings are good? Which is active by default? (The --help doesn't say..)

**Comment by Apollo122** [comment]
I don't use avg color. Default converter is better.

Blur 20
Erosion 20
Histogram on if it's not a close up or you get a rainbow effect :)
Others default

**Comment by ruah1984** [comment]
who  Adjust mask before?? i try a few time but cant get the good result. any one can share the best parameter for this?

**Comment by feepdakenoob** [comment]
ruah1984, best results come from trial and error. There is not a perfect set of settings that works for every scenario. Test the settings and combinations of settings out on a small snippet and see what you get.

**Comment by kunguang** [comment]
![image](https://user-images.githubusercontent.com/3446934/38998335-ecf04556-4421-11e8-8840-0b12c2530639.png)
how get off this shadow
