### ISSUE TITLE
Windows 10 using CPU not GPU

### ISSUE THREAD

**Issue by Lobotuerk** [deepfakes/faceswap-playground#129]
When training, faceswap is using tensorflow, not tensorflow-gpu. If i unistall the tensorflow lib, i get missing module error. Dlib is set to USE_CUDA yes, i have cuda 9.0 and cdnn 7.0. Of course, my cpu goes to 100% and my gpu is idle. GPU = GTX 970 4gb
This is the log when i try to run it:
`Model A Directory: D:\MLT\DeepFake\faceswap\data\yo
Model B Directory: D:\MLT\DeepFake\faceswap\data\mauricio
Training data directory: D:\MLT\DeepFake\faceswap\models
Loading data, this may take a while...
Using live preview
Loading Model from Model_Original plugin...
D:\ProgramData\Anaconda2\envs\dfake\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From D:\ProgramData\Anaconda2\envs\dfake\lib\site-packages\keras\backend\tensorflow_backend.py:1264: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\ProgramData\Anaconda2\envs\dfake\lib\site-packages\keras\backend\tensorflow_backend.py:1349: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-04-10 18:21:53.813878: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
loaded model weights
Loading Trainer from Model_Original plugin...
Starting. Press "Enter" to stop training and save model
Exit requested! The trainer will complete its current cycle, save the models and quit (it can take up a couple of seconds depending on your training speed). If you want to kill it now, press Ctrl + c`

**Comment by ruah1984** [comment]
you should install the tensorflow -gpu version

**Comment by Lobotuerk** [comment]
I have Tensorflow-gpu installed, when i try to train i get asked for not gpu version

`Requirement already satisfied: tensorflow-gpu==1.5.0 in d:\programdata\anaconda2\envs\dfake\lib\site-packages`

**Comment by gessyoo** [comment]
Lobotuerk, have you tried running the CUDA 9 samples included with the toolkit to troubleshoot?  Maybe try uninstalling CUDA 9 and installing CUDA 8?  Nvidia's site says that CUDA toolkit 6.5 supports GTX 970, but they are not very clear on whether CUDA 9 is supported on Maxwell GTX 970 cards.  https://developer.nvidia.com/cuda-downloads-geforce-gtx9xx

**Comment by b4nn3d** [comment]
Pip install --upgrade tensorflow-gpu

**Comment by Lobotuerk** [comment]
I formated the pc, reinstalled everything and now is working. Maybe something with the drivers of the card or something was messing the stuff. Thanks anyways for the help
