### ISSUE TITLE
How to improve face recognition during the extract process?

### ISSUE THREAD

**Issue by gessyoo** [deepfakes/faceswap-playground#130]
Seeking advice on how to improve facial recognition during the extract process.  I've used the filtering options -f and -n and -D cnn and tried -r,  which help extract more frames, but many nearly identical frames are still getting missed.  Is there a recommended image resolution for the extract process?  Is a 1280x720 image too large for effective face extraction?  Any insights appreciated. 

- **Command lined used (if not specified in steps to reproduce)**: faceswap.py  extract -f 1.jpg 2.jpg -n not.jpg -D cnn -r 20 
- **Operating system and version:** Windows 10 x64
- **Python version: 3.6.4
- **Faceswap version:** latest current version
- **Faceswap method:** GPU
- **Other related issues:**

**Comment by Kirin-kun** [comment]
Well, give a sample of missed faces and maybe people will be able to determine why they are missed.
