### ISSUE TITLE
Somebody checked the program for malicious code, such as mining or ddos bot?

### ISSUE THREAD

**Issue by BetJek** [deepfakes/faceswap-playground#132]
just wondering.

**Comment by torzdf** [comment]
It's opensource with a ton of contributors. Fairly sure you're safe.

**Comment by gessyoo** [comment]
FakeApp 2.2 supposedly has an optional donation cryptocurrency mining feature, and some dubious deepfake porn sites mine cryptocurrency with visitors' CPUs.  So avoid these.  As torzdf said, these python scripts are open source and have many contributors.

**Comment by Kirin-kun** [comment]
I read the code, like many other people, and there's no such thing as malicious code here. The libs used are all open and publicly available.

FakeApp or any other closed source application, are another story.
