### ISSUE TITLE
Extract not dectecting any faces in images

### ISSUE THREAD

**Issue by yashfk001** [deepfakes/faceswap-playground#135]
Extract in not detecting any faces in any of the images, i have used your reference Nicolas cage pictures for this.  It wont detect face on any of them. I have gone through all issues submitted here and tried to resize images or try with new ones, but it didnt work
![screenshot from 2018-04-19 22-01-58](https://user-images.githubusercontent.com/38536512/39005445-e34a6a30-441d-11e8-9f07-86b308b9e2c7.png)

**Comment by torzdf** [comment]
In the first instance, I'd check your cuda install is working correctly:

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#verify-installation

**Comment by yashfk001** [comment]
Cuda and cudnn installation is proper. I am able to train older extracted pictures with gpu. Train seems to work properly, issue is there in extract and convert. It is not detecting any faces

**Comment by Clorr** [comment]
Seems that a filter image is specified. What is in this image ?

**Comment by yashfk001** [comment]
I cant find this image and i didn't apply any filter on it, i just ran "python faceswap.py extract -i photo/cage -o phot/cageOut".
How can i remove this filter?

**Comment by torzdf** [comment]
The filter shouldn't matter. It's just the default value.

Honestly, when I had this issue, it was a dlib/cuda issue. Nothing to do with faceswap per se. Just because it trains does not mean your install is ok, as DLIB and Tensorflow have different implementations.

**Comment by yashfk001** [comment]
@torzdf : Issue was with dlib, now that is resolved. Its working. 
Thanks @torzdf , @Clorr
