### ISSUE TITLE
'all_images' referenced before assignment and could not broadcast

### ISSUE THREAD

**Issue by ryukishisama** [deepfakes/faceswap-playground#14]
I just get to the training using python train.py command and I got: 
`
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    images_A = load_images( images_A ) / 255.0
  File "C:\Users\remi_\faceswap\utils.py", line 16, in load_images
    return all_images
UnboundLocalError: local variable 'all_images' referenced before assignment
`
Adding "all_images = 0" before the loop I then got this error
`Traceback (most recent call last):
  File "train.py", line 27, in <module>
    images_B = load_images( images_B ) / 255.0
  File "C:\Users\ramo_\faceswap\utils.py", line 17, in load_images
    all_images[i] = image
ValueError: could not broadcast input array from shape (795,793,3) into shape (630,626,3)`

**Comment by ryukishisama** [comment]
Ok just got over those error, I got to put all my image in 256*256 pixel format, I didn't know and it was not told in the usage doc. Now I get python to train but it only uses my cpu I don't know why. I even installed the gpu requirement.

**Comment by ryukishisama** [comment]
I pretty mu tried everything there and it still run on my cpu. 
https://d4datascience.wordpress.com/2017/05/06/setting-up-a-gpu-based-deep-learning-machine/

My video card is a GTX 970

**Comment by Clorr** [comment]
Please open a new one if you still have a problem
