### ISSUE TITLE
extract on CUDA does not see faces. but sees on the CPU

### ISSUE THREAD

**Issue by BetJek** [deepfakes/faceswap-playground#141]
(Virtual_Conda_1) D:\Face\faceswap-master>python faceswap.py extract -i D:\Face\2\Photo\ -o D:\Face\faceswap-master\data\2\
Input Directory: D:\Face\2\Photo
Output Directory: D:\Face\faceswap-master\data\2
Filter: filter.jpg
Using json serializer
Starting, this may take a while...
Loading Extract from Extract_Align plugin...
100%|█████████████████████████████████████████████████████████████████████████████| 12055/12055 [08:55<00:00, 22.53it/s]
Alignments filepath: D:\Face\2\Photo\alignments.json
Writing alignments to: D:\Face\2\Photo\alignments.json
-------------------------
Images found:        12055
Faces detected:      0
-------------------------
Done!

(Virtual_Conda_1) D:\Face\faceswap-master>pip freeze
absl-py==0.2.0
bleach==1.5.0
certifi==2018.4.16
cmake==3.11.0
Cython==0.28.2
decorator==4.3.0
dlib==19.8.1
h5py==2.7.1
html5lib==0.9999999
Keras==2.1.2
Markdown==2.6.11
mkl-fft==1.0.0
mkl-random==1.0.1
networkx==2.1
numpy==1.14.2
opencv-python==3.3.0.10
pathlib==1.0.1
Pillow==5.1.0
protobuf==3.5.2.post1
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.6
scikit-image==0.13.1
scipy==1.0.1
six==1.11.0
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.1
tqdm==4.23.0
Werkzeug==0.14.1
wincertstore==0.2

(Virtual_Conda_1) D:\Face\faceswap-master>

**Comment by torzdf** [comment]
Run it with the -v flag and post output:

`python faceswap.py extract -i D:\Face\2\Photo\ -o D:\Face\faceswap-master\data\2 -v`

**Comment by BetJek** [comment]
100%|████████████████████████████████████████████████████████████████████████████▉| 12051/12055 [06:55<00:00, 28.99it/s]Failed to extract from image: D:\Face\2\Photo\photo-frame-9996.png. Reason: No module named 'dlib'
Failed to extract from image: D:\Face\2\Photo\photo-frame-9997.png. Reason: No module named 'dlib'
Failed to extract from image: D:\Face\2\Photo\photo-frame-9998.png. Reason: No module named 'dlib'
100%|████████████████████████████████████████████████████████████████████████████▉| 12054/12055 [06:55<00:00, 28.99it/s]Failed to extract from image: D:\Face\2\Photo\photo-frame-9999.png. Reason: No module named 'dlib'
100%|█████████████████████████████████████████████████████████████████████████████| 12055/12055 [06:55<00:00, 28.99it/s]
Alignments filepath: D:\Face\2\Photo\alignments.json
Writing alignments to: D:\Face\2\Photo\alignments.json
-------------------------
Images found:        12055
Faces detected:      0
-------------------------
Done!

**Comment by torzdf** [comment]
Yeah, I thought so... Dlib isn't installed

**Comment by BetJek** [comment]
what command you need to enter for compilation dlib? i have VS 15 and cmake and VS 17. i downloaded dlib from git.

**Comment by Kirin-kun** [comment]
Hopefully, it should work on Windows 10 too, but I make no guarantee because I can't test.
