### ISSUE TITLE
better average color and mask blending

### ISSUE THREAD

**Issue by Hunterwolf88** [deepfakes/faceswap-playground#145]
Hello there,
how can I get better results like those?
https://github.com/deepfakes/faceswap/issues/30

I still have that rectangle around the swapped faces by default

**Comment by torzdf** [comment]
On 720p images I use blur of 50, but it will depend on your frames

**Comment by Hunterwolf88** [comment]
thanks :) adding --blur-size and --erosion-kernel-size on default settings worked well
