### ISSUE TITLE
conversion is missing frames

### ISSUE THREAD

**Issue by Hunterwolf88** [deepfakes/faceswap-playground#146]
Hello there,
How do you get rid of the missing frames conversion?
I have a lot of frames not converted expecially where the mouth is opened and/or the angle is not totally straight.
Is there some kind of threshold that has to be tweaked while extracting / training / converting?
what's your experience?
I would prefer a conversion with a non-perfect matching face, rather than completely skip the frame conversion.

**Comment by torzdf** [comment]
Conversion shouldn't be skipped unless the face wasn't detected. As long as the face was detected it will attempt to do a conversion, even if the end result turns out to be bad.

**Comment by Hunterwolf88** [comment]
can the detection be improved? (even with the downside of false positives)

**Comment by torzdf** [comment]
Not really, unless someone builds a better one. Currently it is based on this: https://github.com/1adrianb/face-alignment.  For best results, use cnn detector and rotate images (-r on)

**Comment by Hunterwolf88** [comment]
thank you, I figured out a better extraction using

`python faceswap.py extract -i ./INPUTFOLDER -o ./OUTPUTFOLDER --detector cnn --rotate-images 360`

**Comment by torzdf** [comment]
-r 360 won't do anything (It will rotate once at 360 degrees, which would take it back to upright).

'-r on' or '-r 90' will rotate the image 4 times at 0, 90, 180, 270

other examples:
'-r 180' : 2 rotations at 0, 180

'-r 45': 8 rotations at 0, 45, 90, 135, 180, 225, 270, 315
