### ISSUE TITLE
Deleted unwanted others' face before training, but still output in the merged images.

### ISSUE THREAD

**Issue by koest** [deepfakes/faceswap-playground#147]
I only need one specific actor's faces, then I **deleted** other persons' face in the destination **aligned** files before training, but when I merged after training, **all the persons' faces were replaced**.
How can I delete unwanted faces?

**Comment by torzdf** [comment]
Are you using GUI or command line?

Either way, did you point 'Input Aligned Dir" towards your aligned folder when you converted?

**Comment by koest** [comment]
Thank you torzdf for replying.
I am a python beginner and just find it hard to setup the environment. 
I guess what I use the the command line. It have many bat files and I only need to double click them.

The Merger.bat is as below

@echo off
SET PATH=%PATH%;%CD%\_internal\bin;%CD%\_internal\bin\Scripts;%CD%\_internal\bin\CMake\Bin
SET TMP=%CD%\_internal\_tmp
SET TEMP=%CD%\_internal\_tmp
SET PYTHON_EXECUTABLE=%CD%\_internal\bin\python.exe
SET HOME=%CD%\_internal\userprofile
SET USERPROFILE=%CD%\_internal\userprofile
SET APPDATA=%CD%\_internal\userroaming
SET WORKSPACE=%CD%\workspace

cd _internal\bin

rmdir %WORKSPACE%\data_dst\merged /s /q
start "" /D "%CD%" /LOW "python.exe" faceswap\faceswap.py convert -i %WORKSPACE%\data_dst -o %WORKSPACE%\data_dst\merged -m %WORKSPACE%\model --trainer Original --converter Masked --seamless --blur-size 0 --erosion-kernel-size 1

I guess the problem occur in the merger procedure, because when I train, unwanted faces do not appear in the preview window.

And could you please tell me how I can download the GUI version? I just successfully setup the command line version, but find it hard to use.

**Comment by torzdf** [comment]
If you have the latest version downloaded, you should be able to launch the gui fairly easily.

I don't have this set up on Windows, so I can't test this, but you can try:

Copy the Merger.bat file above to a new file called Gui.bat (make sure to take a copy so you don't break the current Merger file!)

Edit the Gui.bat file and change this line:

`start "" /D "%CD%" /LOW "python.exe" faceswap\faceswap.py convert -i %WORKSPACE%\data_dst -o %WORKSPACE%\data_dst\merged -m %WORKSPACE%\model --trainer Original --converter Masked --seamless --blur-size 0 --erosion-kernel-size 1`

to this:

`start "" /D "%CD%" /LOW "python.exe" faceswap\faceswap.py gui`

**Comment by koest** [comment]
Thank you torzdf. 
Let me have a try!

**Comment by koest** [comment]
@torzdf 
Thank you very much! I can launch the GUI. It is so easy to use.
I download the code from https://github.com/deepfakes/faceswap, the link always has the latest version right?

**Comment by koest** [comment]
@torzdf 
May I ask a question?
When I extract faces, the program used CPU instead of GPU, how can I used GPU?

**Comment by torzdf** [comment]
Yes it does.

**Comment by koest** [comment]
@torzdf May I ask how can I download the newest GUI version? I can see the GUI updated progress (now V0.3.0) but when I downloaded faceswap, the GUI version is still v0.2.1b.

**Comment by bryanlyon** [comment]
Download the staging branch.  That has the latest changes and bug fixes.

**Comment by koest** [comment]
@bryanlyon thank you very much! Now i am downloading it.

**Comment by torzdf** [comment]
V0.3.0 is not yet released, so 0.2.1b is latest stable.

I hope to have v0.3 released to staging in the next week, but it may take a little longer, as I'm doing this in my spare time.

**Comment by koest** [comment]
@torzdf Thanks a lot. I am looking forward to the release.
