### ISSUE TITLE
How to improve

### ISSUE THREAD

**Issue by YLaCoon** [deepfakes/faceswap-playground#148]
Hi,

actually everything worked fine so far. However, I am not getting good results. As least not as good as what I've seen produced by others. I have trained for 60k steps. So far I am using the default command line arguments (i.e. `-A some_dir -B some_other`). Is there any method/command line argument that I am missing? For example I tried `-s` for seamless image cloning, but that didn't work (masked only).
Thanks

## Actual behavior

![shia2smith](https://user-images.githubusercontent.com/38865806/39443428-e059b0d4-4cb4-11e8-94b8-5e224204242f.png)

## Steps to reproduce
```
python extract ...
python train ...
python convert ...
```

## Other relevant information
- **Operating system and version:** Linux Ubuntu 16.04
- **Python version:** 3.5
- **Faceswap version:** 958493
- **Faceswap method:** GPU

**Comment by koest** [comment]
Hi, how many hours have you trained? What GPU did you use? 1060?
My GPU is 1060 6G and I spent about 7 hours (same sample with yours), the outcome is not bad. 

Did you pick the faces in input_B? Some are not faces.

**Comment by YLaCoon** [comment]
I guess it ran for ~5 hours (1080 TI). Can you post some results so that I can compare? BTW `B` is Agent Smith from this video: https://www.youtube.com/watch?v=9aFVSkncq00. Are you using the GUI? I think it uses different command line arguments and you therefore get better results.

**Comment by torzdf** [comment]
What are your loss levels for A and B they are the most important things. You want to be aiming for below 0.02 on both sides.

Even on a Ti, you're probably going to need significantly longer than 5 hours.

**Comment by YLaCoon** [comment]
Both losses are below 0.02: `loss_A: 0.01114, loss_B: 0.01485`. I will continue a bit and update the results.

**Comment by Kirin-kun** [comment]
-s is for swapping the models.

Are you sure you used -S (uppercase)?

It actually doesn't look like you used seamless mode.

**Comment by YLaCoon** [comment]
Thanks @Kirin-kun . Now it works :+1: 

## Results with seamless cloning (`-S`)
![shia2smith_seamless](https://user-images.githubusercontent.com/38865806/39512212-5d338134-4df0-11e8-8fd3-435dce88e66b.png)
