### ISSUE TITLE
Failed building wheel for dlib

### ISSUE THREAD

**Issue by JobSmith** [deepfakes/faceswap-playground#149]
When I tried to execute the following command:

```
pip install -r requirements-python36.txt
```

It showed me this ERROR:

```
Failed building wheel for dlib
```

I don't know happened.

**Comment by Kirin-kun** [comment]
Install cmake and Visual Studio 2015 build tools.

dlib doesn't exist as prebuilt package, so when installing it, it needs to be compiled.

See #141

**Comment by JobSmith** [comment]
Thanks a lot!
