### ISSUE TITLE
Joint 3D Face Reconstruction and Dense Alignment with Position Map Regression Network

### ISSUE THREAD

**Issue by luiscosio** [deepfakes/faceswap-playground#152]
Have you guys seen this?

Repository:

https://github.com/YadiraF/PRNet

Relevant discussion:

https://news.ycombinator.com/item?id=16977516
https://www.reddit.com/r/MachineLearning/comments/8gk1rt/p_joint_3d_face_reconstruction/

**Comment by iperov** [comment]
video doesnt satisfy me. Result trained on existing 68 points predictor, we can see 3d face mask jittering.
So why to create predictor based on predictor? This is data loss.

**Comment by tjess78** [comment]
Bump, because the developement seems quite active and they now stated texture editing (which could help us to get better eye details) and face swapping as possible options

**Comment by luiscosio** [comment]
You are right @tjess78 .

Have you seen this @iperov ?

![image](https://user-images.githubusercontent.com/1666/39938163-a797b2ee-5517-11e8-8d4a-003d41e736c1.png)

**Comment by iperov** [comment]
looks crap. Also video can produce awful result.
