### ISSUE TITLE
The converted face appears to be crushed 

### ISSUE THREAD

**Issue by kawasakikou** [deepfakes/faceswap-playground#153]
## Actual behavior
I have new 10000 face data of A and B. Some of them also have rough image.

I got this video as an output result.
![fakeswap_nongan_mistakes](https://user-images.githubusercontent.com/7048018/39561487-ebf3b5f6-4ee0-11e8-817b-938a0b0ade81.gif)

Is it possible to improve this?
(change models? or Train with just a beautiful image?)
## Other relevant information
- Docker image on this repo

**Comment by Kirin-kun** [comment]
What was the loss? How much time did you train? Did you train on CPU or GPU?

Your thing look like it's not been trained enough.

**Comment by kawasakikou** [comment]
Loading Trainer from Model_Original plugin...
saved model weights loss_A: 0.01208, loss_B: 0.00906
saved model weights loss_A: 0.01206, loss_B: 0.01032
saved model weights loss_A: 0.01129, loss_B: 0.01104
saved model weights loss_A: 0.01225, loss_B: 0.01012
saved model weights loss_A: 0.01264, loss_B: 0.01008
saved model weights loss_A: 0.01175, loss_B: 0.01009
saved model weights loss_A: 0.01196, loss_B: 0.01032
[14:18:04] [#00682] loss_A: 0.01165, loss_B: 0.00997

**Comment by kawasakikou** [comment]
![video-frame-197_0](https://user-images.githubusercontent.com/7048018/40958989-3a47a62c-68d6-11e8-897f-763aa0778469.png)

**Comment by kawasakikou** [comment]
We're fucked

**Comment by kawasakikou** [comment]
Help me...

**Comment by torzdf** [comment]
That's probably too many images. Either way, this looks like a problem with your set up. Remove everything. Reinstall cuda reinstall requirements. Try again

**Comment by kawasakikou** [comment]
Thank you😭
How many images should I use? I also want to know the lowest resolution.
Probably there is no problem with cuda.

**Comment by seranus** [comment]
Look at the original set, it uses around 350 images. I use around 250 with a mix of search images and extracted frames.

If I have a bad set that ends up blurry I'll start with the original trump - cage and get good results
