### ISSUE TITLE
Poor performance on 1055ti mobile 

### ISSUE THREAD

**Issue by quadlol** [deepfakes/faceswap-playground#156]
How quickly do you normally do 100 iterations of training? On my 1055ti m it takes approximately 110 minutes. How does the program choose if it should use CPU or GPU for computing?

Also, these are my results for extraction
X%|####    | 47/90 [02:50<02:36,  3.64s/it]
is it normal?

**Comment by bryanlyon** [comment]
The program uses tensorflow and depending on which version of tensorflow you have installed will run on the CPU or GPU accordingly.  You can verify if it's using your GPU by watching GPU ram and speed when you start the tool.  It should fill up most of your GPU's memory and run at somewhere between 50-100% GPU speed.

**Comment by quadlol** [comment]
@bryanlyon thanks, i think the issue was that my laptop switched between CPU and GPU during while training - not sure what it was, maybe energy management but now its working.
