### ISSUE TITLE
Faceswap in cloud?

### ISSUE THREAD

**Issue by quadlol** [deepfakes/faceswap-playground#157]
Has anyone tried to deploy the faceswapper in cloud? What are your results?

**Comment by bryanlyon** [comment]
It's possible to run faceswap on an AWS instance.  The training tends to cost about $15 due to the high cost of GPU instances.  This price may go down if you break it up to low demand times or if prices go down (right now they're very high due to cryptocurrency mining).

The free google cloud for AI stuff does not have sufficient RAM resources to run faceswap, it's designed for smaller AI tools.

Right now, it's probably still cheapest and easiest to use consumer hardware, as even a GTX 1050 can train a model (eventually).

**Comment by bryanlyon** [comment]
The cheapest AWS instance is p2.xlarge which runs about $.9/hour.   The K80 on that instance is very close to a 1080 which takes a day or two for good results.  Google Cloud has similar pricing to AWS but slightly cheaper. Hence my $15 estimate ($15-43.8 actually depending on which service and how long you let it train).  Other instances may work faster than a k80 but they cost exponentially more.  

When I said there wasn't enough ram, I was only referring to their free tier which only gives you a slice of the GPU ram and is insufficient for training.

**Comment by shaoanlu** [comment]
p2.xlarge spot instance price is ~$0.3/hr. Also, performance of K80 (single GPU) is not even close to but at least 2x slower than GTX1080 according to [here](https://arxiv.org/pdf/1608.07249.pdf) (TABLE 7), and [here](http://timdettmers.com/2017/04/09/which-gpu-for-deep-learning/).

btw, I believe that the "training part" can be done on [google colab](https://colab.research.google.com/), which is totally free.

**Comment by gitfourteen** [comment]
@shaoanlu What was the share of K80 RAM you got when training with colab? Did you only try GAN?
I never succeeded with original mode and also LowMem. Best chance ever for me was ~2.5GB upper LIMITE and hundreds of byte free to use. 
Faceswap extracted in google drive.

**Comment by davidanger** [comment]
I think using old card like GTX980TI maybe more cheap.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
@quadlol 

> As for Google Cloud, I believe you can get 4 vCPUs, 16GB ram, Tesla K80 for 600$/month, that means trial can run for approx. 2 weeks. Is 16GB really not enough? (source https://www.youtube.com/watch?v=abEf3wQJBmE )

^no need for more than 2cpus. I mean yea 4 is better, but 2, or even 1 will work fine for basic 64x64 models. 128 may be pushing a little. I would suggest a teslak80 paired with 2cpus, bump the mem up to 13, theres a large memory deal google has, slight discount for 13. total comes to around 300 even.

**Comment by bryanlyon** [comment]
Just an update:  Since this was answered originally, Google Colab has started offering free access to GPUs,  It's not ideal since you may lose your instance at any time, but it's free and faceswap does work on it (with some small changes)
