### ISSUE TITLE
Warning about newest NVIDIA driver.

### ISSUE THREAD

**Issue by bryanlyon** [deepfakes/faceswap-playground#158]
Nvidia's newest driver (397.31) is actually a buggy and broken mess.  If you use it and experience ANY issues while on this version, please uninstall and revert to 391.35 as this will fix many issues.  This problem extends beyond just those using GTX 1060s and affects ALL cards.  Please avoid updating your drivers until Nvidia releases some fixes.

**Comment by luiscosio** [comment]
397.93 works just fine, try updating it.

**Comment by bryanlyon** [comment]
Yes, This was just a warning for 397.31.  This is no longer an issue.
