### ISSUE TITLE
Meaning of "Reuse existing models will train much faster than start from nothing."

### ISSUE THREAD

**Issue by quadlol** [deepfakes/faceswap-playground#159]
"Reuse existing models will train much faster than start from nothing."

What do you mean by this? From my understanding, the model contains encoder, which is basically A and B merged together which is then applied to an input. That means that it will always apply the content of the encoder (A and B) on an input. 
If I reuse the model for inputs C and D (train them). The encoder will contain A,B,C,D. If I press convert and choose D as an input and the model, it will just give me a result that looks like A,B,C,D.

Or did I misunderstand?

**Comment by seranus** [comment]
If you train your model on A and B and now your training C and D. If A and B are similar to C and D you can start the training with the A and B model so your starting loss would be smaller

**Comment by quadlol** [comment]
I see. I guess it will not work
