### ISSUE TITLE
Please tell me this is normal...

### ISSUE THREAD

**Issue by EdwardAutumn** [deepfakes/faceswap-playground#16]
i used the trained model  provided by this repository and this is what i got
![610599530](https://user-images.githubusercontent.com/19833520/34651463-74b8e3ce-f40b-11e7-93aa-bfa1e7a4b43b.jpg)
![513222102](https://user-images.githubusercontent.com/19833520/34651465-756ac30a-f40b-11e7-9b18-8afa4fe9259a.jpg)
![506980722](https://user-images.githubusercontent.com/19833520/34651466-76926d28-f40b-11e7-8c3f-8e29af584408.jpg)

**Comment by ccs1605** [comment]
yup, i got similar results. lol

**Comment by EdwardAutumn** [comment]
@ccs1605 ok.guess i have to wait for this project

**Comment by Tvde1** [comment]
Train longer
