### ISSUE TITLE
Can deepfakes convert only TARGET FACE in a frame with different faces?

### ISSUE THREAD

**Issue by gitfourteen** [deepfakes/faceswap-playground#160]
![extract](https://user-images.githubusercontent.com/22335780/39688300-a0dbe7ba-5204-11e8-8474-8f710899f9e4.png)
![convert](https://user-images.githubusercontent.com/22335780/39688305-a64e5c14-5204-11e8-9936-74936a4e8557.png)

The first picture is extracted from the original vedio, and the 2nd one converted by **latest faceswap**.
As you can see,  Cage and the Beauty are all face-swapped with ugly Trump. This is not we want. We need the choir girl!
What can we do to mitigate the embarrassing discontinued square profile and the blurring? Train with GAN?

I reused the default modles here and continued to **train(default)** the data adding more extracted Cage/Trump faces from other sources. 
The final loss are (loss_A: 0.03263, loss_B: 0.03267). Platform: CPU, Python36.

**Comment by Kirin-kun** [comment]
That's simple. 

If you want to convert only one face in the target frame, when converting, you have to point faceswap to the aligned directory (with -a) which contains only the faces you want to convert. If a face has been deleted, it won't be replaced. 

Conversely, if the aligned directory is not found, it will convert all the faces found in alignments.json.

**Comment by Kirin-kun** [comment]
For the square, you have to used -S (seamless mode).

**Comment by torzdf** [comment]
Or play around with blur settings

**Comment by gitfourteen** [comment]
@Kirin-kun 
thanks. I figured it out turning to the script converter.py
Seems that it is required to extract faces from original vedio(s) whether we apply them as the training data or not.

Wondering the possibility of the other way around: 
just input some sized sample-faces to 'ask' faceswap ignore converting any faces similar to them...it would save us from sorting them out with naked eye

**Comment by gitfourteen** [comment]
@torzdf 
thanks.what's the format of BLUR_SIZE?

>python faceswap.py convert -i ~dir\extracted-pic -o ~dir\converted-pic -m ~\modles -a ~\aligned-face -S -b ???

I tried ??? with 256 or 256*256...no idea

**Comment by torzdf** [comment]
You can use the --filter flag to ignore faces, but it is hit and miss on whether it picks up the faces.

I don't think blur can be used with seamless. 

I find starting with -b 30 is a good place, then adjust up or down depending on your source images. Blur basically 'erodes' the edges of the rectangle and it's significantly quicker than seamless. I believe the value is the number of pixels to blur.
