### ISSUE TITLE
Discrepancy in documentation and it's resources

### ISSUE THREAD

**Issue by kartikchauhan** [deepfakes/faceswap-playground#161]
In the repository [https://github.com/deepfakes/faceswap](deepfakes/faceswap), the md file says to run this command to extract faces `python faceswap.py extract`. This will take photos from src folder and extract faces into extract folder. However, there's not any folder present by `src` or `extract` name. 

I get the output:
_Output Directory: output
Input directory input not found._

The training data suggested in the readme file https://anonfile.com/p7w3m0d5be/face-swap.zip downloads a zip file. Upon extracting, it produces a folder with name `face-swap`.

Now, there's certainly a discrepancy here. Have they not verified their resources or is the documentation not updated? What should I follow now?

**Comment by torzdf** [comment]
`python faceswap.py extract -h`

or 
`python faceswap.py gui `

if you'd rather use a gui

Don't worry about the training data.

**Comment by bryanlyon** [comment]
You need to specify what src and extract folders you want to use, there is no default.  as Torzdf said, read the help in -h.  I'm closing this issue since it's solved there.
