### ISSUE TITLE
Low CPU utilization ~30%

### ISSUE THREAD

**Issue by gitfourteen** [deepfakes/faceswap-playground#162]
I would like first to give some basic information.

- [0] Platform: win10/Python 3.65
                 CPU Intel Core i7-6700@3.4GHz, 4 cores
                 GPU GT 720(vRAM 2GB)
                 Memory 8GB DDR3

- [1] **First build a virtual environment for CPU mode (with requirements-python36.txt)**
when **extract/train/convert** **_with default settings_**, everything was perfect. CPU utilization almost 100%, training Trump/Cage data ~1-2 minutes/ iteration, extracting ~3-4 seconds/picture

- [2] **Then build another virtual environment for GPU mode (with requirements-gpu-python36-cuda9.txt)**
2.1_setprojectdir_ to the same 'faceswap' directory.
**_with default settings_**, **extract** succeeded but at lower speed ~20-30 seconds/picture;
**train** failed since memory exhausted, informed OOM.
.
2.2**with the same data and modles, change to LowMem.**
informed something like 'You are trying to load a weight file containing 6 layers into a model with 7 layers', and then finally failed again(I did not read the error information but noticed GPU VRAM 100%).

Here is the point >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
When go back to CPU mode, it never work the same efficiency as before:
--CPU utilization steady at ~30%
--3-4 times longer time to extract/train

Having no idea what was going wrong, I even deleted the 2 virtual environments and faceswap and **reinstalled**(ONLY CPU mode). Still keep working ~30% CPU, ~4-5GB memory.

Can you help me to get full CPU capacity? Thank you for any help you can offer!
![cpu30](https://user-images.githubusercontent.com/22335780/39884889-d063942c-54bd-11e8-9389-fd4bd0d2d69e.jpg)

**Comment by bryanlyon** [comment]
To use lowmem, you need to use a separate model folder, it's not compatible with the Original model.  You probably didn't clear all the traces of tensorflow-gpu.  My advice is to clear it all with pip, make sure it's gone from the installed folders, and reinstall with requirements-python36.txt.

Right now, Lowmem is good for any GPUs with 4gb of vram.  less than 4gb may not work with any model.  More than 4gb of vram can use the original model.

**Comment by gitfourteen** [comment]
@bryanlyon Thanks.
I use command rmvirtualenv to remove the virtual environments. and reinstall as you suggest...
But if GPU/CPU run in different environments, how come GPU affect CPU? I am just newbie...

Would you suggest use different faceswap project directories for different model, like GPU/CPU?

I give up 2GB GPU...may try cloud later

**Comment by bryanlyon** [comment]
Virtualization (especially mkenv in Windows) is never perfect, and little bits and pieces of the main OS can get changed.  We've never tracked down all the little changes, so recommend only installing the one you want.  Warning though: running a train on a CPU takes weeks or even months.  We HIGHLY recommend a GTX 1060 6gb or better.
