### ISSUE TITLE
Unwrap/Rewarp a VR video

### ISSUE THREAD

**Issue by wackyphillwillis** [deepfakes/faceswap-playground#166]
Obviously VR videos are warped using some type of projection. This is bound to cause training issues. Anyone know how to unwarp the extracted frames and then rewarp them after conversion?

**Comment by bryanlyon** [comment]
Depends on the video that you're using and how it's wrapped.  Chances are it's either a 180 or 360 degree wrap.  It could be mono or stereo.  Then it could be barrel, or Fisheye.  All these matter in how to unwrap VR videos.  None of this is within the scope of faceswap so you'll need to search for the tools and resources for this on the web.
