### ISSUE TITLE
Why do we need warped data for training?

### ISSUE THREAD

**Issue by Jasas9754** [deepfakes/faceswap-playground#168]
I'm not an expert.

So I don't understand.

It seems training is working well without warped training data. What does this actually do?

**Comment by kvrooman** [comment]
The image distortion or warp will be the thing that the neural network
trains to correct when it reconstructs an image.
- If you want to train a denoising network, feed in an image distorted with
gaussian noise, salt-and-pepper noise, etc...
- If you want to train a deblurring network, feed in an image distorted
with motion blur, box blur, gaussian blur, etc.

The concept of swapping a face in my opinion has at least two distortions
that the image warp in Faceswap addresses.
1. The landmark affine transformation isn't perfect and sometimes results
in distorted frontal faces.  By intentionally warping the faces during
training in a similar manner to these affine failures, the neural network
is trained to correct these issues.
2. Two people's faces are generally structurally similar as they are both
faces after all. One person's face can be considered as a warped version of
another person's face. Thus intentionally warping Face A and training the
network to reconstruct Face A from a distorted input will also train it to
use the proper method to warp Face B into Face A. ( Note: that there are
also color differences between faces, adding a random color shift globally
or in patches to the warped face input probably would also help )

**Comment by Jasas9754** [comment]
Wow, that's a perfect explanation. Thank you.
