### ISSUE TITLE
Conversion of faces is particularly slow！GPU: Tesla P40, compute capability:6.1

### ISSUE THREAD

**Issue by samylee** [deepfakes/faceswap-playground#17]
Hi @deepfakes ,
Thanks for sharing your code. But when I convert the face, the speed of conversion is very slow. My GPU is very powerful. Why is the conversion slow? The speed is close to 2s/frame. Do you know the reason? Thank you!

**Comment by samwisdom** [comment]
Same here. It takes me hours just to convert 300 frames of videos (about 10 seconds). I'm using a google cloud computer running Ubuntu 16.04 (6 vCPUs; 30 GB memory; Tesla K80 GPU; CUDA 8).

**Comment by Clorr** [comment]
Please open a new one if you still have a problem
