### ISSUE TITLE
Can't start training from GUI

### ISSUE THREAD

**Issue by Ludoboii** [deepfakes/faceswap-playground#173]
## Expected behavior

Start training after selecting the two input folders and ticking the "Preview" box.

## Actual behavior

The program shows the following output:
```
Loading...
Traceback (most recent call last):
File "/home/giovanni/faceswap/faceswap.py", line 8, in <module>
raise Exception("This program requires at least python3.2")
Exception: This program requires at least python3.2
Process exited.
```

## Steps to reproduce

I simply followed all the instructions in INSTALL.md; moved the pictures of the two persons to `~/faceswap/photo`; extracted faces from the pictures I downloaded; added the following line in my .bashrc file to use python3 instead of python when in terminal: `alias python=python3`, however I got the error even before adding that line, when I typed the command `python3` instead of `python` to launch the script.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: 
```
git clone https://github.com/deepfakes/faceswap.git
cd faceswap
python setup.py
python faceswap.py extract -i ~/faceswap/photo/person1 -o ~/faceswap/data/person1
python faceswap.py extract -i ~/faceswap/photo/person2 -o ~/faceswap/data/person2
python faceswap.py gui
```
- **Operating system and version:** elementary OS 0.4.1 Loki, built on "Ubuntu 16.04.3 LTS", Linux 4.13.0-43-generic
- **Python version:** 3.5.2 and 2.7.12
- **Faceswap version:** Latest commit 049a4e5
- **Faceswap method:** GPU
- **Other related issues:** none
- `pip3 freeze` output:
```
absl-py==0.2.2
astor==0.6.2
beautifulsoup4==4.4.1
bleach==1.5.0
Brlapi==0.6.4
chardet==2.3.0
click==6.7
cloudpickle==0.5.3
cmake==3.11.0
command-not-found==0.3
cycler==0.10.0
dask==0.17.5
decorator==4.3.0
defer==1.0.6
dlib==19.13.1
face-recognition==1.2.2
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.0
google-images-download==2.3.0
grpcio==1.12.0
h5py==2.7.1
html5lib==0.9999999
Keras==2.1.2
kiwisolver==1.0.1
language-selector==0.1
louis==2.6.4
lxml==3.5.0
Markdown==2.6.11
matplotlib==2.2.2
networkx==2.1
numpy==1.14.3
onboard==1.2.0
opencv-python==3.4.1.15
pathlib==1.0.1
pexpect==4.0.1
Pillow==5.1.0
protobuf==3.5.2.post1
ptyprocess==0.5
pycups==1.9.73
pycurl==7.43.0
pygobject==3.20.0
pyparsing==2.2.0
python-apt===1.1.0.b1-elementary2-r2-ubuntu0.4.1.1
python-dateutil==2.7.3
python-systemd==231
pytz==2018.4
PyWavelets==0.5.2
pyxdg==0.25
PyYAML==3.12
reportlab==3.3.0
requests==2.9.1
scandir==1.6
scikit-image==0.14.0
scipy==1.1.0
screen-resolution-extra==0.0.0
selenium==3.12.0
sessioninstaller==0.0.0
six==1.11.0
system-service==0.3
tensorboard==1.8.0
tensorflow-gpu==1.8.0
termcolor==1.1.0
toolz==0.9.0
tqdm==4.23.4
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
Werkzeug==0.14.1
xkit==0.0.0
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by torzdf** [comment]
It's not running in python 3. Set up a virtual envy and run it from there. https://help.dreamhost.com/hc/en-us/articles/115000695551-Installing-and-using-virtualenv-with-Python-3
