### ISSUE TITLE
faceswap vs FakeApp

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap-playground#176]
What are the main differences between faceswap and FaceApp v1.1?
Can faceswap use data generated by FaceApp for training and converting?
Are both apps using the same default values (nodes,layers,batches) for training and converting?

I tried using some model training data generated by FaceApp, however faceswap gives an error:

---
Loading Model from Model_Original plugin...
Failed loading existing training data.
Dimension 1 in both shapes must be equal, but are 1024 and 512. Shapes are [1638
4,1024] and [16384,512]. for 'Assign_8' (op: 'Assign') with input shapes: [16384
,1024], [16384,512].
Model Not Found! A valid model must be provided to continue!

**Comment by bryanlyon** [comment]
We use different models.  This means you cannot move models between faceswap and fakeapp.
