### ISSUE TITLE
Training New Data

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap-playground#177]
Let's say I have facesets from 5 different videos for training, each in their own folders.
Is it best to train on all images at the same time or can I train on each folder separately?
I would stop training and then continue training later on a new folder.

For example, let's say I dump all facesets into one folder, and train for 20 hours.
Or I can train 5 folders separately for 4 hours, for a total of 20 hours.

Will the result be any different?

**Comment by bryanlyon** [comment]
If they're the same actor, I would recommend taking some of the images out,
but putting them all together.

This should train in about the same time as with any one of them.

If they're multiple actors, you shouldn't train them with the same model at
all.

**Comment by samsonsite1** [comment]
Input A remains unchanged for all training runs.
Input B has 5 separate folders, same actor.

So, are you saying it doesn't matter if the input B data is trained with everything together, or separately?
