### ISSUE TITLE
Partial Masks?

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap-playground#179]
Can faceswap detect faces for the following situations:

- Actor's face is partially off-screen. (eyes are clipped)
- Actor's face is partially obscured by something in the foreground.  (eyes are obscured).
All of these are full frontal faces.  No side views.

If not, is there anything that can be done to fix these situations, other than cutting these frames out of the video?

Are the actor's eyes the most important feature for face detection?  So, if no eyes are visible, then the face detector fails for all cases?

**Comment by bryanlyon** [comment]
No, eyes are not all our face recognition uses.  It can already find obscured faces, but it still requires enough of the face to identify.  Usually about 60% of the face is required.

You are welcome to try some solutions which let you manually create the landmarks.  Usually we recommended selecting videos that don't have bad framing which might be problematic for face recognition.

**Comment by samsonsite1** [comment]
If there was some way to import all of this image data into Adobe After Effects, I think that would solve a lot of problems, for those who want to edit video even more.  In AE, you can create exclusion masks per keyframe, so if you wanted to modify the mask of a single frame of video, you could do that.

Like for example, if you wanted to mask out specific facial features, like the eyes, nose, mouth... and leave everything else alone.  Or use AE's mask blending features instead.

I mean, after all the face detection and alignment has been done, the final task of preparing the video turns more and more into video editing.  So, if there was some way to bridge that into AE, I think that would be very useful.
