### ISSUE TITLE
What are some ways to blend the face in better?

### ISSUE THREAD

**Issue by DrDreGFunk** [deepfakes/faceswap-playground#180]
I'm using CPU Macbook pro and the lowest point so far I have experienced the losses go down to are "saved model weights loss_A: 0.01789, loss_B: 0.01811". I'm not sure if it will ever get lower than that and I've been training for 17 hours, so I was just wondering if I had to make do with what I've got. How could I make Data_B look more natural on Data_A? I know and understand that the FakeApp uses a seamless function; is there a way to implement that into faceswap? Or use programs like Adobe After Effects, to make it work? Also, what's the lowest loss value someone got with CPU?

**Comment by Kirin-kun** [comment]
Faceswap already uses seamless. It's the -S option at conversion.

**Comment by DrDreGFunk** [comment]
So it's an automatic function? If so, the results still don't blend very well and were wondering if there were other approaches of blending in the face e.g. if someone has used After Effects to blend etc. And again, will training on CPU be limited around the loss value I mentioned before. I've trained even longer and got it down to "saved model weights loss_A: 0.01668, loss_B: 0.01797". Just need to know if I should continue training or if there's no point and just use what I have so far...

**Comment by bryanlyon** [comment]
Training on CPU or GPU only differ in speed.  The more likely cause is that you've hit the local minimum and further tweaking wont improve that model as much.  It'll never be "perfect".  Our model is just not going to get that close.  Loss is an artificial measure and in fact, you may have already permanently harmed your model by over-training.  It's actually likely to get worse as you train it more.

You can always use external tools to blur or composite the images more.  Some small edits to the code can give you the face without compositing it into the original image.  (Actually doing this is left as an exercise to the reader, there are hints on how in this very repo).  After effects can easily be used if that is what you know how to use, other tools include Cinepaint or hitbox film.

**Comment by DrDreGFunk** [comment]
Ok, thank you my guy for this information.
