### ISSUE TITLE
Alignment file is not written in premature termination

### ISSUE THREAD

**Issue by ltpoch** [deepfakes/faceswap-playground#181]
Hi all,

I thought the alignment file was written as the face(s) were extracted, but I found out just now that it is in fact only written in the end of the extraction process. Terminating the extraction before finish, no matter in GUI or commands, does not write anything to the alignments file (if there has been one). 

Also, the --skip-existing function in extraction only checks the output folder but not the alignments file, so the missing entry in alignments wouldn't be easily found. Together these leads to an inconsistency between the alignments and the extracted face set, and caused most of the flashing in my exported videos.

My temporary solution is using a script to break the input files into small subfolders and extract them separately. However it would be nice if there is a function to write the alignments file during the extraction, say maybe every 100~200 files extracted, or make it an adjustable parameter. So that we can break the extraction more easily, especially when using GUI. Would have done it if I am a better programmer. :/ 

This feature would be helpful to people has lower-spec computers, such as myself. I often stop the extraction to do other tasks or to play games and got crappy, flashing conversions afterwards. Always thought it is the instability from hog until I found this issue today.

**Comment by bryanlyon** [comment]
This has been requested before, but it's not a priority since you can split the folder like you said.  We welcome PRs though.

**Comment by ltpoch** [comment]
@bryanlyon Thanks for the reply. I just started playing with it and did not went through the discussion. I'll try to mod it myself but still hope this function could be implement soon. :)

**Comment by Kirin-kun** [comment]
The easy solution is to embed the landmarks information in the extracted files themselves instead of creating a serializing file. Adding textual information in a png, or even a jpg (exif), is easy.

If you interrupt the extraction process and do a skip-existing, nothing would be lost.

**Comment by ltpoch** [comment]
Sounds great.

**Comment by ltpoch** [comment]
Even if the extraction has finished without error, some of the items in json are still not updated, which are mostly non-faces from previous cycles. I found the issue causing this problem in the load_skip_alignments() at ln.326 in scripts/fsmedia.py.

At ln.330 the function write existing alignments into the faces_detected:
```
    for key, val in existing_alignments.items():
        if val:
            faces_detected[key] = val
```
However this overwrites the newly/correctly extracted alignments with the old one. No matter how many times extractions are executed the wrongly extracted ones will not be updated even if the extracted faces are correct.

I tried to modify the code (as below) ,and it worked , writing the new alignments into the json file.:
```
    def load_skip_alignments(self, alignfile, faces_detected):
        """ Load existing alignments if skipping existing images """
        if self.have_alignments_file:
            existing_alignments = self.read_alignments()
            for key, val in faces_detected.items():
                if val:
                    existing_alignments[key] = val
            return existing_alignments
        else:
            print("Existing alignments file '{}' not found.".format(alignfile))
            return faces_detected
```

I never really use github before so if someone could add this modification I will appreciate. :)
