### ISSUE TITLE
Tools Folder?

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap-playground#183]
How does one use the tools, sort.py and effmpeg.py?

I tried calling them directly, but I think they might be dependent on other loaded libs.
But, I don't see anything in faceswap.py to call them.

==============================================

&gt; python.exe sort.py

Traceback (most recent call last):
  File "sort.py", line 15, in <module>
    from lib.cli import DirFullPaths, FileFullPaths
ModuleNotFoundError: No module named 'lib'

===============================================

Are they GUI only python scripts?

**Comment by torzdf** [comment]
`python.exe tools.py sort`
