### ISSUE TITLE
Memory Question

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap-playground#185]
Let's say I have 16GB of system RAM installed.
Normally, when I train, my total memory stays around 3GB to 5GB.

But, sometimes, while training, using default settings (original model, etc..), my memory jumps 8 GB, 
from 5GB to 13GB, and everything slows to a crawl.  This only happens after I open a browser window, 
and start browsing for a few minutes.

Now, if I open up Windows Task Manager, python.exe is only consuming 2GB, and my browser app is only consuming less than 250 MB.  So, where is this 8GB disappearing to?

If I never touch my computer while training, total memory usage never goes above 5GB, so I'm just curious what's happening here.

**Comment by Kirin-kun** [comment]
faceswap doesn't use a lot of RAM. Only VRAM is truly useful for training on GPU.

But when you launch a browser, it tries to use graphic acceleration to render the page so it uses VRAM. Suddenly, it competes with faceswap for the VRAM it has already reserved and everything slows to a crawl and your mouse might even stop responding.

If you don't want this, I guess you could try to disable hardware acceleration in your browser.

**Comment by samsonsite1** [comment]
Let's say I install two graphics cards.  Assume one card is dedicated to rendering, and the other is hooked up to my monitor.  Can faceswap be configured so it only uses the 2nd GPU, and leaves the monitor GPU alone?

**Comment by Kirin-kun** [comment]
I think you can use an environment variable for that, before launching faceswap. 

SET CUDA_VISIBLE_DEVICES=1 | Only device 1 will be seen
SET CUDA_VISIBLE_DEVICES=0,1 | Devices 0 and 1 will be visible
SET CUDA_VISIBLE_DEVICES=”0,1” | Same as above, quotation marks are optional
SET CUDA_VISIBLE_DEVICES=0,2,3 | Devices 0, 2, 3 will be visible; device 1 is masked

If you use hwmonitor, you should see clearly which GPU is used.
