### ISSUE TITLE
Error in analysis loading...

### ISSUE THREAD

**Issue by kellurian** [deepfakes/faceswap-playground#188]
While its not central to the program, I have been having error with loading the stats from training sessions. I really actually like this feature, so its kind of a bummer that it hasn't been working. I have one model set it seems to work on, but every other one gives me this error:
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\users\sean\anaconda3\Lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "H:\faceswap\lib\gui\display_analysis.py", line 63, in load_session
    self.set_session_summary(loaded_data, msg)
  File "H:\faceswap\lib\gui\display_analysis.py", line 79, in set_session_summary
    self.summary = SessionsSummary(data).summary
  File "H:\faceswap\lib\gui\stats.py", line 132, in __init__
    self.summary_stats_compile(raw_data)
  File "H:\faceswap\lib\gui\stats.py", line 138, in summary_stats_compile
    raw_summaries.append(self.summarise_session(idx, session))
  File "H:\faceswap\lib\gui\stats.py", line 151, in summarise_session
    rate = (session["batchsize"] * session["iterations"]) / elapsed
ZeroDivisionError: float division by zero

Any idea what may be causing it?
System is windows 10, 980 TI SLI, intel I75820K using anaconda

**Comment by torzdf** [comment]
Can you attach the trainingstats.fss file?

**Comment by torzdf** [comment]
This should be fixed in latest commit.

The error comes about when a training session is terminated almost immediately, so an elapsed time of 0.0 seconds is recorded. 

I have changed the code so an elapsed time of 0.1 seconds will be recorded if this happens in future. You previous training sessions should now load fine.

**Comment by kellurian** [comment]
great thank you

**Comment by kellurian** [comment]
that worked great. Thank you.
