### ISSUE TITLE
Error when launching train

### ISSUE THREAD

**Issue by kumaranvpl** [deepfakes/faceswap-playground#19]
I am not using floydhub. I am running it locally. Following is my output

(venv) kumaran@kumaran:~/Projects/faceswap$ python faceswap.py train -A data/trump -B data/obama -m models/obama_trump/ -p
/home/kumaran/Projects/faceswap/venv/lib/python3.6/site-packages/h5py/init.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/kumaran/Projects/faceswap/venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
return f(*args, **kwds)
Model A Directory: /home/kumaran/Projects/faceswap/data/trump
Model B Directory: /home/kumaran/Projects/faceswap/data/obama
Training data directory: /home/kumaran/Projects/faceswap/models/obama_trump
Not loading existing training data.
Unable to open file (unable to open file: name = '/home/kumaran/Projects/faceswap/models/obama_trump/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Starting, this may take a while...
usage: faceswap.py [-h] {extract,train,convert} ...

positional arguments:
{extract,train,convert}
extract Extract the faces from a pictures.
train This command trains the model for the two faces A and
B.
convert Convert a source image to a new one with the face
swapped.

optional arguments:
-h, --help show this help message and exit
(venv) kumaran@kumaran:~/Projects/faceswap$

**Comment by Clorr** [comment]
Please open a new one if you still have a problem
