### ISSUE TITLE
Bypass face detection in conversion process

### ISSUE THREAD

**Issue by rosenb0rg** [deepfakes/faceswap-playground#194]
I'm experimenting with training on isolated facial regions (i.e. mouth only). 

 I'm able to train the network with mouth-only image sets and get good results based on the preview, but the conversion process goes through a facial recognition and extraction process, before applying the encoder. Is there a way to feed the network "raw input" and get out the raw results? The conversion script has a lot of layers and components so I'm not quite sure where to start.

**Comment by Pantich78** [comment]
Hi, sorry I don't have an answer but I'm curious to know if you get more fine details like skin pores training a smaller region.
Thanks
