### ISSUE TITLE
Faces Detected: 0 

### ISSUE THREAD

**Issue by sakshamyadav** [deepfakes/faceswap-playground#195]
## Expected behavior

Trying to extract faces from the raw images. 

## Actual behavior

I'm using the extract command, and I'm getting this problem: "Failed to extract from image: /Users/yadav_sa/desktop/faceswap-master/photo/ken/image.jpg. Reason: module 'keras.backend' has no attribute 'placeholder'"

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: python faceswap.py extract -i me -o me_faces

- **Operating system and version:** MacOS 10.13.5 (High Sierra)
- **Python version:** 3.6
- **Faceswap version:** Latest 
- **Faceswap method:** CPU

**Comment by sakshamyadav** [comment]
For some reason, when running 'python faceswap.py extract', it's able to find all the images, but doesn't detect any faces. I tried with heaps of images, even ones with really well defined faces, but it wasn't able to detect any.

 It could be due to the below adjustment that I made, but I'm not sure: 

![screen shot 2018-07-16 at 11 53 12 pm](https://user-images.githubusercontent.com/29766280/42762340-71c7f26c-8953-11e8-8fe8-b144511bc82a.png)
![screen shot 2018-07-16 at 11 53 42 pm](https://user-images.githubusercontent.com/29766280/42762361-8384ea32-8953-11e8-9642-4965a5da8ce5.png)

After this error showed up, I removed all 3 elements from the list `required_entries = ['placeholder', 'variable', 'function']` on line 95, which resolved the error. 

Then, I managed to successfully run extract without any errors, but it detected 0 faces. Thanks!

**Comment by sakshamyadav** [comment]
Sorry if my error wasn't clear guys. Basically I'm getting ValueError: Invalid backend. Missing required entry : placeholder. 

 File "/anaconda/lib/python3.6/site-packages/keras/backend/__init__.py", line 98, in <module>
    raise ValueError('Invalid backend. Missing required entry : ' + e)

**Comment by sakshamyadav** [comment]
Seems like there is something wrong with my backend file

**Comment by bryanlyon** [comment]
This is a Keras error saying that the backend is not set correctly.  Please make sure that you have installed all requirements and that your keras config is set to the tensorflow backend.  See the following link for more information https://keras.io/backend/ .

**Comment by sakshamyadav** [comment]
Thanks for the reply Bryan. I’ve been trying to fix this for over 12 hours and now I have a huge headache, pls help haha 🙂

**Comment by gessyoo** [comment]
sakshamyadav,  not sure what OS you're running, but in Windows the command to issue in the python environment is:  set "KERAS_BACKEND=tensorflow"  For some reason, keras defaults to theano as the backend, but theano isn't being developed anymore.  Also, there is some incompatibility with the current code and the latest version of keras (2.2), so you need to use the version in requirements.txt.  Keras 2.16 works for me, but not Keras 2.2.

**Comment by torzdf** [comment]
> Also, there is some incompatibility with the current code and the latest version of keras (2.2)

This is no longer the case. The latest commit uses Keras 2.2

**Comment by sakshamyadav** [comment]
I think I found the culprit. 

```
{
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "mxnet",
    "image_data_format": "channels_first"
}
```
backend was set to mxnet instead of tensorflow. I changed it to tensorflow, so now I'm not getting any errors, but it still says 0 faces detected! Why?? Pls help haha

**Comment by sakshamyadav** [comment]
I think I've got it figured out now, thanks everyone!
