### ISSUE TITLE
Problem with 'convert'

### ISSUE THREAD

**Issue by sakshamyadav** [deepfakes/faceswap-playground#199]

**Comment by sakshamyadav** [comment]
I have my original Trump and Cage files stored in` faceswap/trump` and `faceswap/cage` respectively. 

I extracted them both to` faceswap/trump_extracted `and `faceswap/cage_extracted` respectively. 

I trained the models using 
`python faceswap.py train -A ~/faceswap/trump_faces-B ~/faceswap/cage_faces -m ~/faceswap/models/`

I want to replace all of Trump's face (in ` faceswap/trump`) with Cage's face. So I do this: `python faceswap.py convert -i ~/faceswap/trump/ -o ~/faceswap/output/ -m ~/faceswap/models/
`

But this replaces Trump's face with his own face. Am I doing something wrong?

**Comment by gessyoo** [comment]
I think you want to do this:  python faceswap.py convert -i ~/faceswap/trump/ -o ~/faceswap/output/ -m ~/faceswap/models/ -a ~/ {dir. with the cage aligments.json file} 

Specify the alignments directory.  python faceswap.py convert -h shows all the options.
