### ISSUE TITLE
Adding Rotation with Bounding to increase Likelihood of Face Being Found

### ISSUE THREAD

**Issue by seattleg** [deepfakes/faceswap-playground#20]
FIRST: love the work, awesome job!
**SECOND A SUGGESTION:**
Currently the angle of a face often messes with the face detection of dlib
is it possible to add a condition such that if a face is not found, rotate the image by a certain degree within a bounded box ( so as not to cut out the image ) and running through the dlib face detection? It might take longer to extract and convert, but at least it will be automatic. If a face is found during the process, run it through the model ( or extraction process ) then re-rotate and output the extracted or converted face. To increase efficiency, maybe remember the last degree of rotation used since movement between frames might not change as much.

**Comment by Clorr** [comment]
There is now the cnn option that activates mmod face detector which deals nice with angles. However, it is very resource intensive, and being able to use the standard face detector with varied angles would be nice. Feel free to post this in the main repo
