### ISSUE TITLE
dlib-cnn 

### ISSUE THREAD

**Issue by sjunique** [deepfakes/faceswap-playground#204]
have installed the recent facewap version  according to the requirements.txt
every things is working fine except getting the following error while usling dlib-cnn
i even downloaded the dlib-master from github and compiled that too
I am using faceswap GUI

**Failed to extract from image:  Reason: std::bad_alloc**
system: linux (linux mint)
python version
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0] on linux

**Comment by torzdf** [comment]
Not enough VRAM. What GFX card are you running? Also post the output when running extract with the -v flag.

**Comment by sjunique** [comment]
saw in one of the post dlib.DLIB_USE_CUDA and imine was not properly installed
now all is good
