### ISSUE TITLE
manual alignment automatically exited.

### ISSUE THREAD

**Issue by klee86** [deepfakes/faceswap-playground#212]
**command**:
python D:\pythondf\python-3.6.3.amd64\faceswap\tools.py alignments -j manual -a D:/pythondf/python-3.6.3.amd64/faceswap/imgA/alignments.json -fc D:\pythondf\python-3.6.3.amd64\faceswap\data\dataset\A\face -fr D:/pythondf/python-3.6.3.amd64/faceswap/imgA -fmt json -o console

Loading...
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
Using TensorFlow backend.

[ALIGNMENT DATA]
Loading alignments from D:\pythondf\python-3.6.3.amd64\faceswap\imgA\alignments.json

[FRAMES DATA]
Loading file list from D:\pythondf\python-3.6.3.amd64\faceswap\imgA

[MANUAL PROCESSING]
Loading Extract from Extract_Align plugin...

=============== NAVIGATION ===============
- 's': Skip Mode (All, No Faces, Multi Faces, Has Faces)
- 'z': Previous Frame
- 'x': Next Frame
- '}': Go to Last Frame
- '{': Go to First Frame
- 'ESC': Exit
- '/': Cycle Frame Zoom
- ']': 100 Frames Forward
- '[': 100 Frames Back
================ DISPLAY ================
- 'y': Toggle Image
================= COLOR =================
- 'u': Cycle Bounding Box Color
- 'i': Cycle Extract Box Color
- 'o': Cycle Landmarks Color
- 'p': Cycle Landmarks Mesh Color
================== SIZE ==================
- 'h': Cycle Bounding Box thickness
- 'j': Cycle Extract Box thickness
- 'k': Cycle Landmarks - point size
- 'l': Cycle Landmarks Mesh - thickness
================== EDIT ==================
- 'Left Click': Bounding Box - Move
- 'Middle Click': Bounding Box - Resize
- 'm': Change Mode (View, Edit)
- 'v': Copy Next Frame's Alignments
- 'c': Copy Previous Frame's Alignments
- 'd': Delete Selected Alignment
- 'r': Reload Alignments (Discard all changes)
- 'SPACE': Save Alignments
- '0 to 9': Select/Deselect Face at this Index
Process exited.

It seems to be a few windows show up in very tiny moment and disappears. Please help

**Comment by torzdf** [comment]
There is an issue with Windows not reading openCV state properly. I had a fix implemented in Staging. I have just pushed to Master, so please checkout the latest commit, try again and let me know if it works.

If it doesn't, could you let me know how your python is setup (Anaconda, python venv etc.) and within your venv post the output from:

`python -c 'import sys; import platform ; print(sys.version); print (platform.system())'`

**Comment by torzdf** [comment]
Ok, it's a hacky fix, but I've added the ability to disable window state monitoring. It should now work, but you'll be unable to close the window with the "x" button (you'll need to press escape).

Launch with the `-dm` flag:
`python D:\pythondf\python-3.6.3.amd64\faceswap\tools.py alignments -j manual -a D:/pythondf/python-3.6.3.amd64/faceswap/imgA/alignments.json -fr D:/pythondf/python-3.6.3.amd64/faceswap/imgA -dm`

**Comment by klee86** [comment]
it works now! Thank you!
