### ISSUE TITLE
How to enable adversarial loss when using GAN?

### ISSUE THREAD

**Issue by g0147** [deepfakes/faceswap-playground#218]
May i know how to enable adversarial loss function when using GAN for handling occlusion?

**Comment by torzdf** [comment]
`-pl`

I wouldn't recommend using GAN. It doesn't work very well. Will probably be removed soon with a view to re-porting.

**Comment by bryanlyon** [comment]
Asking for adversarial loss in GAN for obstructions is like asking for how to enable the internal combustion on an f150 to tow a cruise ship.  You're asking for the wrong feature and even the feature that does exist doesn't work like you seem to want.

The "A" in GAN is adversarial and it's the default mode.  It does nothing to handle occlusion though.  It's just a way to train a model with an adaptive loss.

The feature you're actually looking for is a segmentation mask.  This does exist in the GAN, but it's incomplete and insufficient for most occlusions.  It does not remove occlusions automatically and requires a lot of manual intervention to accomplish removing them.  If you're still interested in this type of capability, please come ask more in our Discord chat at https://discord.gg/u8wEDa .  We can answer more questions and guide you on how to mask your images and handle occlusions.

**Comment by g0147** [comment]
> I wouldn't recommend using GAN. It doesn't work very well. Will probably be removed soon with a view to re-porting.

faceswap-GAN v2.2 ?
