### ISSUE TITLE
Can I use 2 GPUs?

### ISSUE THREAD

**Issue by Pocketspeed** [deepfakes/faceswap-playground#219]
Can I use 2 GPUs, a 980ti and 1070ti, for training models? Are there any special requirements or steps beyond entering GPU=2 in the Faceswap GUI?  Thank you for your time!

**Comment by bryanlyon** [comment]
Yes you can use multiple GPUs.  Please ensure that you calculate how big your batch can be on the smaller GPU then set it to double that when using 2 GPUs.

This will not double the speed, but instead increase the speed in an irregular way.  This depends on the GPU bandwidth available as well as the speeds of the GPUs.

Note that you cannot use -ag (allow growth) when using multiple GPUs.
