### ISSUE TITLE
Unable to complete setup (Unmissing Visual studio)

### ISSUE THREAD

**Issue by LulzRose** [deepfakes/faceswap-playground#221]
I have visual studio 2015 installed correctly and have run tried just about everything yet I countinuously receive this message when running the setup. 

\faceswap>python3 setup.py
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Windows 10
INFO    Installed Python: 3.6.5 64bit
INFO    Upgrading pip...
INFO    Installed pip: 18.1
Enable  Docker? [y/N] n
INFO    Docker Disabled
Enable  CUDA? [Y/n] y
INFO    CUDA Enabled
INFO    CUDA version: 9.0
INFO    cuDNN version: 7.4.1
WARNING Tensorflow currently has no official prebuild for your CUDA, cuDNN combination.
        Either install a combination that Tensorflow supports or build and install your own tensorflow-gpu.
        CUDA Version: 9.0
        cuDNN Version: 7.4
        Help:
        Building Tensorflow: https://www.tensorflow.org/install/install_sources
        Tensorflow supported versions: https://www.tensorflow.org/install/source#tested_build_configurations
Location of custom tensorflow-gpu wheel (leave blank to manually install):
INFO    Checking System Dependencies...
INFO    CMake version: 3.13.0
ERROR   Visual Studio 2015 could not be found. See https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#microsoft-visual-studio-2015 for instructions
INFO    Visual Studio C++ version: Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215

**Comment by torzdf** [comment]
If you could join the discord group (https://discord.gg/FdEwxXd) and go to #tech-support we should be able to get you up and running.

If that's not possible, could you post open up a standard windows command prompt and post the output of each of these:

```reg query HKLM\SOFTWARE\Microsoft\VisualStudio\14.0\VSPerf```
```reg query HKLM\SOFTWARE\Microsoft\VisualStudio```
```reg query HKLM\SOFTWARE\Microsoft\VisualStudio\14.0```

And also post a screengrab of this folder:
```C:\Program Files (x86)\Microsoft Visual Studio 14.0```
