### ISSUE TITLE
Doesn't create tensorboard logdir

### ISSUE THREAD

**Issue by david30907d** [deepfakes/faceswap-playground#223]
Please fill-in the form below to help others understand your problem.

NOTE: We assume you have first tried to read the README and the INSTALL files. Also prior to  opening an issue, you should search for similar issues an look if someone had your problem before! 

If your problem is specific and that you decide posting an issue, don't forget to close it afterwards. Also you should consider adding information to the documentation once you have found a solution to your problem. The repository here can only live with the contribution of everyone, and not only with developers helping noobs...

## Expected behavior

It would be great to view loss on tensorboard, but faceswap didn't create logdir for me.

## Actual behavior

No logdir.

## Steps to reproduce

`python3 faceswap.py train ...`

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment]
Tensorboard support is now added in train_refactor and will be merged to master eventually
