### ISSUE TITLE
python error  and unable to convert videos

### ISSUE THREAD

**Issue by thedirtyyugo** [deepfakes/faceswap-playground#224]
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux -:64-bit OS, x64 based processor windows 10
- **Python version:** 2.7, 3.5, 3.6.4, ..-.python 3.7
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU - cpu

CUDA/cuDNN version: cudnn-9.0-windows10-x64-v7.4.1.
GPU model and memory:NVIDIA GeForce GTX 1070

issues
2018-12-01 22:15:38.357265: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_dnn.cc:378] Loaded runtime CuDNN library: 7401 (compatibility version 7400) but source was compiled with 7003 (compatibility version 7000). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

When trying to use GPU as my processor this is the error I receive.  I understand that it says that I have the wrong cudnn file.  I downloaded 7.0.4 and that didn't work and I downloaded version 6 but don't know how to upgrade to version 7.  what can I do to be able to use GPU processor?

 issues 
another issue is after finishing the training step using cpu I cant convert frames.  it wont allow me to at all and shuts down python.  why cant I create the frames on the original video?

I use GAN converter for both training and converting.

**Comment by torzdf** [comment]
1) check https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#windows-install-guide for detailed instructions on getting cuda/cudnn correctly installed
2) Use the latest commit and provide the generated crashlog if you are getting crashes
3) Python 3.7 is not supported by Tensorflow
4) GAN is unreliable at best, broken at worst. Not recommended. A new port is in the pipeline which may or may not be an improvement.

**Comment by thedirtyyugo** [comment]
I still cant convert videos.  I use the original converter and installed everything from that link and my python still crashes.  no error message pops up other that, couldn't create frames. 
what goes in output video, input video, and model.  I feel as if im not accessing the right folders to convert the frames.

**Comment by torzdf** [comment]
> Use the latest commit and provide the generated crashlog if you are getting crashes
