### ISSUE TITLE
Error during faceswap.py extract run. No Graphics Card Detected! FAN is not currently supported on CPU. Use another aligner.

### ISSUE THREAD

**Issue by zoeleesss** [deepfakes/faceswap-playground#229]
## Expected behavior

I was trying to extract the features of Cage's face and save it.
`python3 faceswap.py extract -i data/cage/ -o extracted/cage/`

## Setup Screenshot
<img width="709" alt="screen shot 2018-12-26 at 7 45 07 pm" src="https://user-images.githubusercontent.com/31149915/50445540-71069f00-094a-11e9-9211-a1381703e897.png">

## Actual behavior

But there is something wrong. I cannot run on my MacBook Pro ( MacOS 10.14 )
Errors as below screenshots:
<img width="666" alt="screen shot 2018-12-26 at 7 47 49 pm" src="https://user-images.githubusercontent.com/31149915/50445268-87abf680-0948-11e9-8040-6d6addc378ba.png">
<img width="701" alt="screen shot 2018-12-26 at 7 47 55 pm" src="https://user-images.githubusercontent.com/31149915/50445272-90043180-0948-11e9-99a4-fd20c44dfba6.png">
<img width="602" alt="screen shot 2018-12-26 at 7 48 02 pm" src="https://user-images.githubusercontent.com/31149915/50445277-9692a900-0948-11e9-8010-ced2c7803685.png">
 
## Other relevant information

- **Command lined used**: 
`python3 faceswap.py extract -i data/cage/ -o extracted/cage/`
- **Operating system and version:** MacOS 10.14
- **Python version: 3.6.5
- installed packages:

```
pip freeze

nose==1.3.7
numpy==1.15.4
TBB==0.1
xs-MacBook-Pro:faceswap x$ pip3 freeze
absl-py==0.6.1
astor==0.7.1
beautifulsoup4==4.6.0
certifi==2018.4.16
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
cmake==3.13.2.post1
cycler==0.10.0
dask==1.0.0
decorator==4.3.0
defusedxml==0.5.0
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.0
grpcio==1.16.0
h5py==2.8.0
html5lib==1.0.1
idna==2.6
jieba==0.39
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
lxml==4.2.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==2.2.2
networkx==2.2
nltk==3.3
numpy==1.15.3
nvidia-ml-py3==7.352.0
opencv-python==3.4.4.19
pathlib==1.0.1
pbr==4.0.3
Pillow==5.3.0
protobuf==3.6.1
psutil==5.4.8
pynvx==0.0.4
pyparsing==2.3.0
PySocks==1.6.8
python-dateutil==2.7.5
pytz==2018.7
PyWavelets==1.0.1
PyYAML==3.13
requests==2.18.4
scandir==1.7
scapy==2.4.0
scikit-image==0.14.1
scikit-learn==0.20.0
scipy==1.1.0
six==1.11.0
SOAPpy==0.12.22
tensorboard==1.12.0
tensorflow==1.12.0
termcolor==1.1.0
tld==0.7.10
toolz==0.9.0
tqdm==4.28.1
urllib3==1.22
wapiti3==3.0.1
webencodings==0.5.1
Werkzeug==0.14.1
wstools==0.4.8
xlwt==1.3.0
yaswfp==0.9.3

```

**Comment by zoeleesss** [comment]
@torzdf  Hey bro. Thanks for your insight. Actually i was thinking if it is possible to run this program with my current laptop hardware settings?

![image](https://user-images.githubusercontent.com/31149915/50446324-75818680-094f-11e9-866e-aa18cb17f815.png)

If yes, please do tell me how to do with it.
If not, i will have to buy a new and more powerful Windows computer? 😭

**Comment by torzdf** [comment]
Intel Iris won't do it. You'll be forced to use the CPU.

You will need an Nvidia Graphics card (The latest Turing architecture isn't supported at the moment). There may be external graphics card solutions, but I can't vouch for them.

**Comment by zoeleesss** [comment]
@torzdf  Yeah.. Well, i wanna use the CPU to run. And how am i supposed to do with that? 
Could you please tell me how? Thanks again! Really appreciate it.. (*^__^*)

**Comment by torzdf** [comment]
Just don't use the FAN aligner. Everything else will work

**Comment by zoeleesss** [comment]
@torzdf  Okay..?  So what kind of command should i use instead of `python3 faceswap.py extract -i data/cage/ -o extracted/cage/` to do the same trick? Or what else should i do to make it work? Thanks!! 👍😃

**Comment by torzdf** [comment]
Set the Detector and aligner options.

You should join the Discord group for better support

**Comment by jinger627** [comment]
i had the same problem. use option '-A dlib' . not use FAN.  regard,

./faceswap.py extract -i ... -o ... -A dlib

**Comment by zoeleesss** [comment]
> i had the same problem. use option '-A dlib' . not use FAN. regard,
> 
> ./faceswap.py extract -i ... -o ... -A dlib

@jinger627  Thanks so much. It's working now.
