### ISSUE TITLE
encoder.h5

### ISSUE THREAD

**Issue by heenim33** [deepfakes/faceswap-playground#23]
After the model training, we got three models，I want to know the function of encoder.h5。can anyone tell me?Thanks

**Comment by heenim33** [comment]
i also wonder how does the model work .For classification tasks,There will be a label ,compare the network output with label ,and we will get a "loss"minimize the loss ,we will get a model. but  how does this model work,I'm confused

**Comment by ToastMX** [comment]
First the encoder compresses the face into a face vector and the decoder builds the picture of a new face.

If you now train one encoder on both datasets and two decoders for different faces, you can encode every face and then, by deciding which decoder you choose, make it into the face you want.

Here is a good explanation too https://www.youtube.com/watch?v=7XchCsYtYMQ

**Comment by Clorr** [comment]
@heenim33 the autoencoder takes a distorted face as input and the original image as output. It is actually a "face rectifier" (it removes the distortion)
