### ISSUE TITLE
Why it says and how to deal with: macOS users need to install XQuartz

### ISSUE THREAD

**Issue by zoeleesss** [deepfakes/faceswap-playground#230]
I was trying to run GUI for faceswap. `faceswap.py gui`, but i cannot run this due to the following errors:

<img width="791" alt="screen shot 2018-12-26 at 8 16 08 pm" src="https://user-images.githubusercontent.com/31149915/50445680-436e2580-094b-11e9-90ac-aea36bbd6715.png">

So I did download this so-called XQuartz. But honestly i dont know what it is and how to do with it. So i wanna ask you guys how to deal with this XQuartz thing and make it work? 

Thanks a lot in advance!

<img width="485" alt="screen shot 2018-12-26 at 8 16 33 pm" src="https://user-images.githubusercontent.com/31149915/50445684-479a4300-094b-11e9-968e-03d90faba736.png">

## Other relevant information
- **Command lined used ** `faceswap.py gui`
- **Operating system and version:** MacOS 10.14
- **Python version:** 3.6.5

**Comment by torzdf** [comment]
As far as I remember, you just need to install it, then re-run the faceswap gui

**Comment by zoeleesss** [comment]
@torzdf  Well. The thing is that I did download the .dmg and install it. But however, i couldn't run the program `faceswap gui` , and it still says the same error `macOS users need to install XQuartz` as before. 
So any idea how to figure it out? And what the XQuartz thing is and how to make it work on macOS?
Thanks again!(*^__^*) 😄

**Comment by torzdf** [comment]
XQuartz allows python to display GUIs. 

I would need to find a mac to test on, but I'm pretty sure I just installed it before and it used to work.
