### ISSUE TITLE
Display “cuDNN not found” or wrong "CUDA_VERSION" when running "setup.py"

### ISSUE THREAD

**Issue by PisChiao** [deepfakes/faceswap-playground#231]
My os is windows 10 and I have already installed CUDN v9.0 and cuDNN v7.4 and other packages it need. But when I run "python setup.py",it display like "CUDA version: CUDA.SDK.LIB.PATH" "cuDNN not found".

I checked the source of setup.py
```
cuda_keys = [key
                 for key in os.environ.keys()
                 if key.lower().startswith("cuda") and key.lower() != "cuda_path"]
......
CUDA_VERSION = cuda_keys[0].replace("CUDA_PATH_V", "").replace("_", ".")
CUDA_PATH = os.environ[cuda_keys[0]]
out_info("CUDA version: " + CUDA_VERSION)
......
cudnn_checkfile = os.path.join(CUDA_PATH, "include", "cudnn.h")
```
i tried to print "cuda_keys", it shows
```
['CUDA_LIB_PATH', 'CUDA_PATH_V9_0', 'CUDA_BIN_PATH', 'CUDA_SDK_LIB_PATH', 'CUDA_SDK_BIN_PATH', 'CUDA_SDK_PATH']
```
I think the author want to get "CUDA_PATH_V9_0"，but in my system environment "CUDA_LIB_PATH" is the first one, so cuda_keys[0] is "CUDA_LIB_PATH" but not "CUDA_PATH_V9_0".

I ignored this problem and I can use “faceswap.py” normally.So i just want to remind that this error does not affect to use the program.

Hope this bug can be fixed,using regular expression matching may help solve this problem.

I am sorry that my English is not very good. I hope you can understand what I'm saying.^_^

**Comment by torzdf** [comment]
Thanks for the bug report. This is fixed in the latest commit.
