### ISSUE TITLE
Initializing MTCNN Detector failed

### ISSUE THREAD

**Issue by sublimationAC** [deepfakes/faceswap-playground#233]
Please fill-in the form below to help others understand your problem.

NOTE: We assume you have first tried to read the README and the INSTALL files. Also prior to  opening an issue, you should search for similar issues an look if someone had your problem before! 

If your problem is specific and that you decide posting an issue, don't forget to close it afterwards. Also you should consider adding information to the documentation once you have found a solution to your problem. The repository here can only live with the contribution of everyone, and not only with developers helping noobs...

## Expected behavior

Trying to extract an image set with: python faceswap.py extract -i data/test/ -o result_data/trump/

## Actual behavior

01/10/2019 11:31:42 INFO     Log level set to: INFO
01/10/2019 11:31:45 INFO     Output Directory:/home/weiliu/Desktop/gihub/deepfakes/faceswap/result_data/trump
01/10/2019 11:31:45 INFO     Input Directory: /home/weiliu/Desktop/gihub/deepfakes/faceswap/data/test
01/10/2019 11:31:45 INFO     Loading Detect from Mtcnn plugin...
01/10/2019 11:31:45 INFO     Loading Align from Fan plugin...
01/10/2019 11:31:45 INFO     NB: Parallel processing disabled.You may get faster extraction speeds by enabling it with the -mp switch
01/10/2019 11:31:45 INFO     Starting, this may take a while...
01/10/2019 11:31:46 INFO     Initializing MTCNN Detector...
01/10/2019 11:31:54 ERROR    Caught exception in child process: 1830
01/10/2019 11:32:45 INFO     Waiting for Detector... Time out in 4 minutes

## Steps to reproduce

I got this issue on Centos when running extract without docker.

## Other relevant information
Operating system and version: Centos 3.19.0-80-generic
Python version: 3.6.4

An issue I met yesterday is that when I ran python setup.py, the cuDNN can not be found. I tried to debug it and I found the cudnn_checkfile was not calculated correctly so I changed it directly, which I am not sure whether it could cause the failure of "Initializing MTCNN Detector". 
The result of "os.path.join(CUDA_PATH, "include", "cudnn.h")", line 372 in setup.py, is "/usr/local/lib/libcudart.so.8."
I changed  into "cudnn_checkfile = "/usr/local/cuda/include/cudnn.h".
After that, I successfully ran the setup.py.
However, when running "python faceswap.py extract -i data/test/ -o result_data/trump/", I got such issue. 

Anyway, thank you for your excellent work!

**Comment by torzdf** [comment]
There are issues with TF 1.10. Try upgrading to 1.11+
https://github.com/deepfakes/faceswap/issues/529

**Comment by sublimationAC** [comment]
Thank you a million! 
That has solved my problem!
