### ISSUE TITLE
ImportError: cannot import name QueueHandler

### ISSUE THREAD

**Issue by zoeleesss** [deepfakes/faceswap-playground#236]
## Expected behavior

I wanted to run the train the models by using command
`python faceswap.py train -A extracted/trump -B extracted/cage -m model/ -p `

## Actual behavior

<img width="602" alt="screen shot 2019-01-13 at 11 58 10 am" src="https://user-images.githubusercontent.com/31149915/51081441-8b9e8d80-172a-11e9-903c-45a3ba3d803c.png">

## Other relevant information
- **Command lined used `python faceswap.py train -A extracted/trump -B extracted/cage -m model/ -p `
- **Operating system and version:**  macOS
- **Python version:** 3.6.5
- **installed packages**
`pip3 freeze`

absl-py==0.6.1
astor==0.7.1
beautifulsoup4==4.6.0
certifi==2018.4.16
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
cmake==3.13.2.post1
cycler==0.10.0
dask==1.0.0
decorator==4.3.0
defusedxml==0.5.0
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.0
grpcio==1.16.0
h5py==2.8.0
html5lib==1.0.1
idna==2.6
jieba==0.39
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
lxml==4.2.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==2.2.2
networkx==2.2
nltk==3.3
numpy==1.15.3
nvidia-ml-py3==7.352.0
opencv-python==3.4.4.19
pathlib==1.0.1
pbr==4.0.3
Pillow==5.3.0
protobuf==3.6.1
psutil==5.4.8
pynvx==0.0.4
pyparsing==2.3.0
PySocks==1.6.8
python-dateutil==2.7.5
pytz==2018.7
PyWavelets==1.0.1
PyYAML==3.13
requests==2.18.4
scandir==1.7
scapy==2.4.0
scikit-image==0.14.1
scikit-learn==0.20.0
scipy==1.1.0
six==1.11.0
SOAPpy==0.12.22
tensorboard==1.12.0
tensorflow==1.12.0
termcolor==1.1.0
tld==0.7.10
toolz==0.9.0
tqdm==4.28.1
urllib3==1.22
wapiti3==3.0.1
webencodings==0.5.1
Werkzeug==0.14.1
wstools==0.4.8
xlwt==1.3.0
yaswfp==0.9.3

**Comment by Friday21** [comment]
why close? how do you solve this? I met this problem  today too

**Comment by RokasMuningis** [comment]
Did you manage to resolve it? I'm also getting this :/

**Comment by Marcyavila** [comment]
how did you solved the "cannot import name QueueHandler" error? i'm having the exact same trouble here
