### ISSUE TITLE
DetectedFaces is not subscripable

### ISSUE THREAD

**Issue by liang93823** [deepfakes/faceswap-playground#242]
## Expected behavior

Try to swap face in a video using the convert command. While attemping I used the -f argument (or Filter option with GUI) to filter out unwanted faces. It should return pictures in which correct faces are swapped.

## Actual behavior

The script reported crash, saying 

"Exception in thread Thread-2:
Traceback (most recent call last):
File "D:\Anaconda\envs\faceswap\lib\threading.py", line 914, in _bootstrap_inner
self.run()
File "F:\faceswap\lib\multithreading.py", line 187, in run
for item in self.generator:
File "F:\faceswap\scripts\convert.py", line 160, in prepare_images
{"detected_faces": detected_faces})
File "F:\faceswap\scripts\fsmedia.py", line 281, in do_actions
action.process(output_item)
File "F:\faceswap\scripts\fsmedia.py", line 417, in process
if not self.filter.check(detected_face["face"]): #
TypeError: 'DetectedFace' object is not subscriptable"

## Steps to reproduce

Just try using the -f arugment or Filter option within GUI.

## Other relevant information
N/A

**Comment by torzdf** [comment]
Full crash report logfile please

**Comment by liang93823** [comment]
Sorry, I wasn't very specific. I just checked and there's no crash report generated. Instead, the program just froze and the warning posted above appears in red.

**Comment by torzdf** [comment]
Are you on the latest commit? That kind of error should definitely dump out a crash report to your faceswap folder

**Comment by liang93823** [comment]
I just cloned the git (https://github.com/deepfakes/faceswap.git), following the instructions.
