### ISSUE TITLE
Question: does the Effmpeg step preserve audio?

### ISSUE THREAD

**Issue by paulfryer** [deepfakes/faceswap-playground#243]
After copying in faces to all the images to process and then stitching the output video back together, is there a way to embed the audio from the original video?

**Comment by torzdf** [comment]
I don't use effmpeg, but I think if you put the source video into "reference video" it will pull the audio in

**Comment by paulfryer** [comment]
Ok, will try that when I get that far along.. currently at training iteration 33k on my first job.
thanks.
