### ISSUE TITLE
Can't train models at Google Colaboratory

### ISSUE THREAD

**Issue by student-101** [deepfakes/faceswap-playground#246]
## Problem

*I used Google Colaboratory for training faceswap models with GPU, but training is extremely slow.
In addition, validation loss didn't show up.
How can I solve these problem? (sorry for my poor English)*

## Log
02/04/2019 08:30:16 INFO     saved model weights
02/04/2019 08:40:13 INFO     saved model weights
02/04/2019 08:43:22 INFO     saved model weights
02/04/2019 08:46:29 INFO     saved model weights
02/04/2019 08:49:39 INFO     saved model weights
02/04/2019 08:52:54 INFO     saved model weights
02/04/2019 08:56:11 INFO     saved model weights
02/04/2019 08:59:31 INFO     saved model weights
02/04/2019 09:02:45 INFO     saved model weights
02/04/2019 09:06:01 INFO     saved model weights

## Other relevant information
- **Command lined used**: faceswap.py train -A ○○ -B ○○ -m ○○ --gpus 1
- **Operating system and version:** Linux 
- **Python version:** 3.6
- **Faceswap version:** commit hash or version number
- **Faceswap method:** GPU 1
- **Installed packages**

**Comment by student-101** [comment]
I don't know well about usage of discord.
Can I post question in that page?

**Comment by bryanlyon** [comment]
Discord is a chat app.  That server link takes you to where you can talk to people who have done google colab.  The basic answer for your situation is that you need to make sure to use a GPU instance on google colab for a reasonable speed.  Check the documentation on google colab for how to do it.
