### ISSUE TITLE
Problems with the filter of convert 

### ISSUE THREAD

**Issue by Lancelotgogo** [deepfakes/faceswap-playground#248]
Filter for convert function is not working.  And I had to rewrite a few lines to make it work again. I'm sure there is something wrong in the code.

**Comment by torzdf** [comment]
Convert is being refactored in the not too distant future, so this will be patched then. If you wish to raise a PR to patch it in the interim, then go ahead.

**Comment by bryanlyon** [comment]
For now, the recommendation is to filter before convert (either at extract or with the sort tool).  This will effectively work the same as the filter in convert.

**Comment by Lancelotgogo** [comment]
> For now, the recommendation is to filter before convert (either at extract or with the sort tool).  This will effectively work the same as the filter in convert.

Thank you. I will give it a try.
