### ISSUE TITLE
Description of models?

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#249]
I was checking the staging branch and I saw some new models.

Before trying them, I'd like to know if it's worth it? Is there some Trump/Cage samples somewhere using these models:

dfaker dfl-h128 iae original unbalanced villain

I guess original is the original 64

I don't see the OriginalHighRes in there. Does this mean this model will be dropped in the future? It's replaced by dlf-h128?

Also, an explanation of the new parameters would be nice.

**Comment by bryanlyon** [comment]
OriginalHighRes was never "original" so was renamed to unbalanced.  It's the same model.

dfaker and dfl-h128 are both ports of those models from their respective repos into faceswap.  They work pretty much the same way as they did in those repos.

Villain is a new model created for high detail situations and requires a high end graphics card.

Most parameters have explanations in -h or in the gui's hovertext.

**Comment by torzdf** [comment]
This is Villain:
https://www.youtube.com/watch?v=r1jng79a5xc

**Comment by torzdf** [comment]
But on top of the new models there are a ton of new customization options. Check the config folder, or the Edit menu in the GUI

**Comment by Kirin-kun** [comment]
In extract, the mtms (to have a minimal size of face) is gone?

Also, I just tried "unbalanced" with the exact same faces sets than with OriginalHighRes and it crashes with OOM (GTX 1060 6Gb).

```
(cface) C:\Users\Kirin>python c:\users\kirin\faceswap\faceswap.py train -A H:\Fa
kes\Erena\aligned.mtcnn -B H:\Fakes\00SRC_DATA\aligned -t unbalanced -m H:\Fakes
\models\modelo.00SRC_DATA.Erena -p -bs 20 -ag -nl
02/14/2019 19:22:59 INFO     Log level set to: INFO
Using TensorFlow backend.
02/14/2019 19:23:00 INFO     Model A Directory: H:\Fakes\Erena\aligned.mtcnn
02/14/2019 19:23:00 INFO     Model B Directory: H:\Fakes\00SRC_DATA\aligned
02/14/2019 19:23:00 INFO     Training data directory: H:\Fakes\models\modelo.00S
RC_DATA.Erena
02/14/2019 19:23:00 INFO     ===================================================
==================
02/14/2019 19:23:00 INFO     - Using live preview
                 -
02/14/2019 19:23:00 INFO     - Press 'ENTER' on the preview window to save and q
uit              -
02/14/2019 19:23:00 INFO     - Press 'S' on the preview window to save model wei
ghts immediately -
02/14/2019 19:23:00 INFO     ===================================================
==================
02/14/2019 19:23:01 INFO     Loading data, this may take a while...
02/14/2019 19:23:02 INFO     Loading Model from Unbalanced plugin...
02/14/2019 19:23:05 INFO     Loading config: 'c:\users\kirin\faceswap\config\tra
in.ini'
02/14/2019 19:23:05 WARNING  No existing state file found. Generating.
02/14/2019 19:23:06 WARNING  Failed loading existing training data. Generating n
ew models
02/14/2019 19:23:06 INFO     Loading Trainer from Original plugin...
02/14/2019 19:24:18 CRITICAL Error caught! Exiting...
02/14/2019 19:24:18 ERROR    Caught exception in thread: 'training_0'
02/14/2019 19:24:19 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "c:\users\kirin\faceswap\lib\cli.py", line 90, in execute_script
    process.process()
  File "c:\users\kirin\faceswap\scripts\train.py", line 97, in process
    self.end_thread(thread, err)
  File "c:\users\kirin\faceswap\scripts\train.py", line 122, in end_thread
    thread.join()
  File "c:\users\kirin\faceswap\lib\multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "c:\users\kirin\faceswap\lib\multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\kirin\faceswap\scripts\train.py", line 148, in training
    raise err
  File "c:\users\kirin\faceswap\scripts\train.py", line 138, in training
    self.run_training_cycle(model, trainer)
  File "c:\users\kirin\faceswap\scripts\train.py", line 210, in run_training_cyc
le
    trainer.train_one_step(viewer, timelapse)
  File "c:\users\kirin\faceswap\plugins\train\trainer\_base.py", line 138, in tr
ain_one_step
    loss[side] = batcher.train_one_batch(is_preview_iteration)
  File "c:\users\kirin\faceswap\plugins\train\trainer\_base.py", line 212, in tr
ain_one_batch
    loss = self.model.predictors[self.side].train_on_batch(*batch)
  File "C:\Users\Kirin\cface\lib\site-packages\keras\engine\training.py", line 1
217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\Kirin\cface\lib\site-packages\keras\backend\tensorflow_backend.
py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Kirin\cface\lib\site-packages\keras\backend\tensorflow_backend.
py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Kirin\cface\lib\site-packages\tensorflow\python\client\session.
py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\Kirin\cface\lib\site-packages\tensorflow\python\framework\error
s_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[5,5,512,2048] and type float on /job:localhost/replica:0/t
ask:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training_1/Adam/mul_169}} = Mul[T=DT_FLOAT, _device="/job:loca
lhost/replica:0/task:0/device:GPU:0"](Adam/beta_1/read, training_1/Adam/Variable
_25/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss_1/mul/_693}} = _Recv[client_terminated=false, recv_device
="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/rep
lica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3890_l
oss_1/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/devic
e:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

02/14/2019 19:24:19 CRITICAL An unexpected crash has occurred. Crash report writ
ten to C:\Users\Kirin\crash_report.2019.02.14.192418466058.log. Please verify yo
u are running the latest version of faceswap before reporting
```

And it says "02/14/2019 19:23:06 INFO     Loading Trainer from Original plugin...". I thought it was unbalanced? 

On master, this faceset has no problem with OriginalHighRes and a batchsize of 20.

**Comment by torzdf** [comment]
Plugin specific options have been added to config. Look at the extract plugin options in edit menu.

OHR is the merged changes that @andenixa made to the model in the rc4_fix branch. It is not backwards compatible with ohr.

Due to historical naming conventions we now have a slight misnomer in the trainer/model split. Trainer in the above message refers to the data feeder (ie the image augmentation that is done to feed the model). Currently all models use the same 'original' trainer, but there is scope to add new feeders. An earlier message would have stated which model you were using

**Comment by Kirin-kun** [comment]
Well, both the unbalanced model and the villain model crash immediately with OOM with a batch size of 2 on a GTX1060 6Gb. It doesn't even create a single model file. 

I think the OriginalHighRes would be kept as an option if all further models are memory hogs.

If staging goes into master, at the moment I would only be able to use original. I didn't try the other models, but I have a hunch all the 128 models are going to crash.

A GTX 1060 is a decent card, IMO. 

And I found a bug: when the batch size is larger than the number of available faces in one of the sets, it crashes. It should reduce automatically the batch size to the max available (or at least stop nicely with a message).

**Comment by torzdf** [comment]
They both have a "lowmem" mode, which may help. Villain is unlikely to work. I struggle to get it running on a 1080 above bathsize 8.

I will check the possibility of re-porting *original* original-hires, but I know @andenixa wasn't happy with it as a model.

**Comment by Kirin-kun** [comment]
I found the parameters in the config.ini and set lowmem to true for unbalanced and villain and it started with a batchsize of 42 for unbalanced and 8 for Villain.

So, it seems it works, at least for training, with a GTX 1060 6Gb?

I will report eventually about conversion.

The change with "lowmem" means it will only take longer, or does the quality change too?

**Comment by torzdf** [comment]
Quality changes. It removes some layers to reduce vram usage. Same kind of thing as lowmem for original model.

**Comment by andenixa** [comment]
`unbalanced` or `OHR RC4_fix` is pretty heavy on resources which is why you might want to restrict yourself to bat h size no more than 16. In fact my personal recommendation never to exceed `-bs` by more than 24-32 because you shall have too much generalization which would result in small details to be lost.

**Comment by Kirin-kun** [comment]
It seems like both "unbalanced" and "villain" need at least 8gb or even 11gb to work without Lowmem.

The cost of running these "high res/details" models is becoming prohibitive. ^^

**Comment by torzdf** [comment]
@Kirin-kun The refactor *should* make it easier for developers to play around and release models, so hopefully people will release an array of models.

The fact of the matter is faceswapping IS VRAM intensive. Both of these models do have lowmem modes to make them available to all, and both of the lowmem modes *should* be better than the original model. The developers have tried to keep these models as inclusive as possible.

You are welcome to have a play around with the plugins and release a model of your own.
