### ISSUE TITLE
How long does a it take to train a model?

### ISSUE THREAD

**Issue by henricook** [deepfakes/faceswap-playground#25]
Mine's been running for about 2 hours maxing out my dual 12GB 1080 Tis - does this finish on its own? Or should i be stopping it when I think it's "done enough"?

If i have to stop it manually i might amend the project README so it's obvious

**Comment by Tvde1** [comment]
You can use the preview tool to see if it's good or not

**Comment by Clorr** [comment]
Many hours ;-)

**Comment by Clorr** [comment]
Please open a new one if you still have a problem
