### ISSUE TITLE
How do you choose face

### ISSUE THREAD

**Issue by gigajew** [deepfakes/faceswap-playground#250]
I've got a folder with photos of people, exports with people and alignments, and when using Convert, I can select a folder but I Can't select one photo to get the face from and one photo to put it on. I can only choose folders and it comes out with a random picture and blurry at that

**Comment by bryanlyon** [comment]
The tool is made for videos and image sequences, not single images.  There is a workaround if you want to do a specific image, put it into a folder on it's own then point the convert at that folder.

You don't need to select an image to get the face from, you have too train the model on the faces you're swapping.

**Comment by gigajew** [comment]
Okay I get what you mean, you only leave one face to use that picture. But how do you chose what body it ends up on?

**Comment by gigajew** [comment]
Okay I got it in the right order now, but the faces still end up really really blurry

**Comment by bryanlyon** [comment]
I think you're misunderstanding how this tool works.  Please read https://github.com/deepfakes/faceswap/blob/master/USAGE.md and understand the process of extract/train/convert.  This is not a simple swap two faces type of program.  It takes time to convert.

**Comment by bryanlyon** [comment]
How many images are you training with and how long are you training?  Usually you'll want around 1000 images for both a and b and training will usually take ~24 hours.
