### ISSUE TITLE
Small bug in staging cli.py

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#251]
In lib/cli.py in staging, the default for the mask is "facehull_rect", which isn't a valid parameter.

Workaround: just add the parameter on the command line (-M facehull)

(I don't use the gui, which adds the parameter on itself I guess)

**Comment by torzdf** [comment]
I have a list of bugs to be squashed, and this is on it....

**Comment by Kirin-kun** [comment]
Noted.

**Comment by torzdf** [comment]
Should be fixed in latest commit
