### ISSUE TITLE
Installation Error, showing ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by liang93823** [deepfakes/faceswap-playground#254]
**Since refactored model has come out, I cloned the latest commit and run setup.py in a newly created Anaconda environment.**

### Terminal output:
(Faceswap-2019-2-24) D:\Faceswap\2019-02-24>python setup.py
WARNING Running without root/admin privileges
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Windows 10
INFO    Installed Python: 3.5.6 64bit
INFO    Running in Conda
INFO    Running in a Virtual Environment
INFO    Encoding: cp936
INFO    Installed pip: 10.0.1
Enable  Docker? [y/N] n
INFO    Docker Disabled
Enable  CUDA? [Y/n] y
INFO    CUDA Enabled
INFO    CUDA version: 9.0
INFO    cuDNN version: 7.4.2
INFO    Checking System Dependencies...
INFO    CMake version: 3.13.4
INFO    Visual Studio 2015 version: 14.0
INFO    Visual Studio C++ version: v14.0.24215.01
INFO    1. Install PIP requirements
        You may want to execute `chcp 866` in cmd line
        to fix Unicode issues on Windows when installing dependencies
Please ensure your System Dependencies are met. Continue? [y/N] y
INFO    Installing Required Python Packages. This may take some time...
INFO    Installing tqdm
INFO    Installing psutil
INFO    Installing pathlib
INFO    Installing numpy==1.15.4
INFO    Installing opencv-python
INFO    Couldn't install opencv-python with Conda. Trying pip
INFO    Installing opencv-python
INFO    Installing scikit-image
INFO    Installing scikit-learn
INFO    Installing matplotlib==2.2.2
INFO    Installing ffmpy==0.2.2
INFO    Couldn't install ffmpy==0.2.2 with Conda. Trying pip
INFO    Installing ffmpy==0.2.2
INFO    Installing nvidia-ml-py3
INFO    Couldn't install nvidia-ml-py3 with Conda. Trying pip
INFO    Installing nvidia-ml-py3
INFO    Installing h5py==2.9.0
INFO    Installing Keras==2.2.4
INFO    Installing cmake
INFO    Installing dlib
INFO    Couldn't install dlib with Conda. Trying pip
INFO    Compiling dlib. This will take a while...
        Please ignore the following UserWarning: 'Disabling all use of wheels...'
D:\Anaconda\envs\Faceswap-2019-2-24\lib\site-packages\pip\_internal\commands\install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
INFO    Installing face-recognition
INFO    Couldn't install face-recognition with Conda. Trying pip
INFO    Installing face-recognition
INFO    Installing tensorflow-gpu==1.12.0
Collecting package metadata: done
Solving environment: done

Package Plan 

  environment location: D:\Anaconda\envs\Faceswap-2019-2-24

  added / updated specs:
    - tensorflow-gpu==1.12.0

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/win-64::cudatoolkit-9.0-1
  cudnn              pkgs/main/win-64::cudnn-7.3.1-cuda9.0_0
  tensorflow-gpu     pkgs/main/win-64::tensorflow-gpu-1.12.0-h0d30ee6_0

The following packages will be DOWNGRADED:

  _tflow_select                                 2.2.0-eigen --> 2.1.0-gpu
  tensorflow                    1.12.0-eigen_py36h67ac661_0 --> 1.12.0-gpu_py36ha5f9131_0
  tensorflow-base               1.12.0-eigen_py36h45df0d8_0 --> 1.12.0-gpu_py36h6e53903_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
INFO    Installing Required Conda Packages. This may take some time...
INFO    Installing ffmpeg
INFO    Installing tk
INFO    All python3 dependencies are met.
        You are good to go.

        Enter:  'python faceswap.py -h' to see the options
                'python faceswap.py gui' to launch the GUI

### Check installed packages:

(Faceswap-2019-2-24) D:\Faceswap\2019-02-24>conda list
packages in environment at D:\Anaconda\envs\Faceswap-2019-2-24:

 Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.7.0                    py36_0    defaults
astor                     0.7.1                    py36_0    defaults
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py36_0    defaults
click                     7.0                      pypi_0    pypi
cloudpickle               0.7.0                      py_0    defaults
cmake                     3.12.2               he025d50_0    defaults
cudatoolkit               9.0                           1    defaults
cudnn                     7.3.1                 cuda9.0_0    defaults
cycler                    0.10.0           py36h009560c_0    defaults
cytoolz                   0.9.0.1          py36hfa6e2cd_1    defaults
dask-core                 1.1.1                      py_0    defaults
decorator                 4.3.2                    py36_0    defaults
dlib                      19.16.0                  pypi_0    pypi
face-recognition          1.2.3                    pypi_0    pypi
face-recognition-models   0.3.0                    pypi_0    pypi
ffmpeg                    4.1               h86867b3_1001    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1    defaults
gast                      0.2.2                    py36_0    defaults
grpcio                    1.16.1           py36h351948d_1    defaults
h5py                      2.9.0            py36h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
imageio                   2.4.1                    py36_0    defaults
intel-openmp              2019.1                      144    defaults
jpeg                      9b                   hb83a4c4_2    defaults
keras                     2.2.4                         0    defaults
keras-applications        1.0.6                    py36_0    defaults
keras-base                2.2.4                    py36_0    defaults
keras-preprocessing       1.0.5                    py36_0    defaults
kiwisolver                1.0.1            py36h6538335_0    defaults
libpng                    1.6.36               h2a8f88b_0    defaults
libprotobuf               3.6.1                h7bd577a_0    defaults
libtiff                   4.0.10               hb898794_2    defaults
markdown                  3.0.1                    py36_0    defaults
matplotlib                2.2.2            py36had4c4a9_2    defaults
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.10           py36h14836fe_0    defaults
mkl_random                1.0.2            py36h343c172_0    defaults
networkx                  2.2                      py36_1    defaults
numpy                     1.15.4           py36h19fb1c0_0    defaults
numpy-base                1.15.4           py36hc3f5095_0    defaults
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py36_0    defaults
opencv-python             4.0.0.21                 pypi_0    pypi
openssl                   1.1.1a               he774522_0    defaults
pathlib                   1.0.1                    py36_1    defaults
pillow                    5.4.1            py36hdc69c19_0    defaults
pip                       19.0.1                   py36_0    defaults
protobuf                  3.6.1            py36h33f27b4_0    defaults
psutil                    5.5.0            py36he774522_0    defaults
pyparsing                 2.3.1                    py36_0    defaults
pyqt                      5.9.2            py36h6538335_2    defaults
pyreadline                2.1                      py36_1    defaults
python                    3.6.8                h9f7ef89_7    defaults
python-dateutil           2.7.5                    py36_0    defaults
pytz                      2018.9                   py36_0    defaults
pywavelets                1.0.1            py36h8c2d366_0    defaults
pyyaml                    3.13             py36hfa6e2cd_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
scikit-image              0.14.1           py36ha925a31_0    defaults
scikit-learn              0.20.2           py36h343c172_0    defaults
scipy                     1.2.1            py36h29ff71c_0    defaults
setuptools                40.8.0                   py36_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
six                       1.12.0                   py36_0    defaults
sqlite                    3.26.0               he774522_0    defaults
tensorboard               1.12.2           py36h33f27b4_0    defaults
tensorflow                1.12.0          gpu_py36ha5f9131_0    defaults
tensorflow-base           1.12.0          gpu_py36h6e53903_0    defaults
tensorflow-gpu            1.12.0               h0d30ee6_0    defaults
termcolor                 1.1.0                    py36_1    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1            py36hfa6e2cd_0    defaults
tqdm                      4.31.1                     py_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.3                   py36_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults

**Then, I tried to use GUI, and got the following error:**
### Error Message:

(Faceswap-2019-2-24) D:\Faceswap\2019-02-24>python faceswap.py gui
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Faceswap\2019-02-24\faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "D:\Faceswap\2019-02-24\lib\cli.py", line 12, in <module>
    from lib.utils import safe_shutdown
  File "D:\Faceswap\2019-02-24\lib\utils.py", line 12, in <module>
    import cv2
  File "D:\Anaconda\envs\Faceswap-2019-2-24\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ModuleNotFoundError: No module named 'cv2.cv2'

**Reinstalled OpenCV with conda, and the problem was not resolved. 
PS: Before model refactoring, I used the same installation process, and it worked out well.**

**Comment by torzdf** [comment]
Try running the installer from https://github.com/deepfakes/faceswap/releases and see if your problem persists.

I have seen this before and it's usually a conflict somewhere
