### ISSUE TITLE
can i computer run this project

### ISSUE THREAD

**Issue by xbb2yy** [deepfakes/faceswap-playground#259]
my computer 
cpu Core(TM) i5-7300HQ CPU @ 2.50GHz
GPU NVIDIA GeForce GTX 1050 2GB

i try to run faceswap, but it always OOM error.
can i computer run this faceswap, and how many times it will cost about if i train of 1000 images

**Comment by xbb2yy** [comment]
ensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,512,512]

**Comment by Kirin-kun** [comment]
2Gb is really really low. 

You can try the original model with lowmem set and see what batch size it supports.
