### ISSUE TITLE
[IMPROVEMENT] Create presets for different video cards

### ISSUE THREAD

**Issue by vladjerca** [deepfakes/faceswap-playground#26]
Considering the amount of users that use this app, and the multitude of available setups, it would be nice to create an MD or a set o presets for different system configurations on the long run.

**Comment by Clorr** [comment]
Why not, the only problem is to gather the data...

**Comment by vladjerca** [comment]
@Clorr Given that the repo has 3k+ stars, I think there's a big enough user base to create these definitions.

**Comment by Clorr** [comment]
It is not a matter of "should we create it or not". The question is to have someone doing it. If you think it is useful, start doing it, and make some Pull Request to add it to the docs....
