### ISSUE TITLE
Model corruption on CTRL-C on training with preview

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#264]
I stumbled on an edge case that led to my model being corrupted (showing red squares in the preview).

What I did:

- Connect to a remote Ubuntu server with "ssh -X" through another server I have an XMing session with.
- Launch a training session with preview: the window normally opens locally
- Let it run unattended for the week-end.

Here's what happens: 

After an unknown amount of time, the preview window closes on itself. Probably due to inactivity on the X11 connection, some router along the way kills the socket. 

But the ssh session is still there and the training seem to be continuing (not sure). 

I'm then stuck with a training session I can't stop! Because it doesn't react to Enter or S,, which it doesn't capture since it's the preview window that's supposed to capture it.

I'm forced to Ctrl-C the training. Needless to say I have a lot of Python traceback and it crashes. 

Relaunching the same command line shows me red-squares in the preview. I had to recopy the .bk files to get a working model, but then it means I lost hours of training.

Without the preview, I seem to be able to stop the training with Enter in the shell.

Is it possible to allow a clean shutdown from both window at the same time?

**Comment by torzdf** [comment]
It's something we can look at, I'm not sure how easy it will be as the preview monitor and cli monitor are separate entities with either one run depending on whether the -p flag is passed.

Related: I have issues sending openCV over x-forwarding, with it erroring out on some windows if I use the mouse. This is particularly the case with preview. Unfortunately this error happens somewhere deep in the source code for openCV so it's not something I can capture and handle. I now no longer forward it over X11. Instead I use vnc4server and send it to that display, connecting from my Windows box with RealVNC. This has proved to be extremely robust, so maybe something you want to look at?

**Comment by bryanlyon** [comment]
You can also ensure you run your remote training sessions in 'screen' which can let you resume broken terminal sessions.  

There isn't really a way we can make faceswap itself continue working in a reasonable way in your setup and work-arounds like screen should be used.
