### ISSUE TITLE
Issue with Mask

### ISSUE THREAD

**Issue by liang93823** [deepfakes/faceswap-playground#265]
Commit on Mar 4 by kilroythethird fixed the problem that unrelated portion near face area was masked, leaving the part like a blurry box. 

However, now there still seems to be a problem: a greenish line always presents on the bottom of the face area. It appears to be something worth fixing?

**Comment by bryanlyon** [comment]
This is an artifact and not really directly fixable.  Masks, erosion, blur, and draw-transparent are all ways to treat this (with various amounts of post processing required).
