### ISSUE TITLE
Please Help With This Error

### ISSUE THREAD

**Issue by DrDreGFunk** [deepfakes/faceswap-playground#27]
Mac OS High Sierra
Mac: 10.13.2
Python 3.6.3 :: Anaconda custom (64-bit)
Using CPU
Processor: 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3

Main Issue: IndexError

This is for training the faces

I've been using this guide as a reference:
 
https://www.reddit.com/r/deepfakes/comments/7ttqk2/tutorial_for_mac/

But got stuck on the part where it says

"python faceswap.py train -A porn_faces -B jessica_faces -m model -p". (I obviously renamed the "porn" and "jessica" as I'm not using this for porn)

The Error:

MY NAME-MacBook-Pro-2:faceswap MY NAME$ python faceswap.py train -A vid_faces -B Celeb_faces -m model -p
Model A Directory: /Volumes/My Passport/DeepFakes/faceswap/Vid_faces
Model B Directory: /Volumes/My Passport/DeepFakes/faceswap/Celeb_faces
Training data directory: /Volumes/My Passport/DeepFakes/faceswap/model
Loading data, this may take a while...
Using live preview
Loading Model from Model_Original plugin...
/Users/MY NAME/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
loaded model weights
Loading Trainer from Model_Original plugin...
Starting. Press "Enter" to stop training and save model
Exception in thread Thread-2:
Traceback (most recent call last):
  File “/Users/MY NAME/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Volumes/My Passport/DeepFakes/faceswap/lib/utils.py", line 42, in run
    for item in self.generator:
  File "/Volumes/My Passport/DeepFakes/faceswap/lib/training_data.py", line 43, in minibatch
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
  File "/Volumes/My Passport/DeepFakes/faceswap/lib/training_data.py", line 43, in <listcomp>
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
IndexError: list index out of range

**Comment by schmunk42** [comment]
How many "jessica" faces do you have? I ran into the same, when just using a few dozen images.
Might be worth giving a smaller batch size a try.

**Comment by DrDreGFunk** [comment]
Thank you for a response, I have 306 celeb faces. I'll try reducing batch size and let you know if it works or not.

**Comment by DrDreGFunk** [comment]
It still didn't work, I kept just 18 faces and it still gave me the same error.

**Comment by Clorr** [comment]
No it goes the other way round. Usually you get this error if you have batch_size > number of images . 306 is ok for B, but how many do you have for A?

(Note that official way to talk about this is to use Trump as source, and Cage as destination ;-) )
