### ISSUE TITLE
How to caculate GPU RAM needed by different batchs? Does batchsize affect model effect? 

### ISSUE THREAD

**Issue by pengyang** [deepfakes/faceswap-playground#274]
Question is :
1. How to caculate  video RAM which is needed by different batchsize?
2. How about batchsize affect to the trained model performance?  batchsize =64 or 128 is better?

## Expected behavior
GPU is GTX970 4GB video ram, expect to run faceswap training normally with default batchsize=64.
Other infor : Image size to train is 256*256

## Actual behavior
Run faceswap training with default batchsize=64, get OOM error. 
Then, run training with -bs 32,  works well.

## Steps to reproduce
NA
## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows10
- **Python version: 3.6.4
- **Faceswap version: April 7 version
- **Faceswap method:** GPU GTX970, 4GB RAM

**Comment by bryanlyon** [comment]
There is no way to predict due to your system, tensorflow certain, running apps and more.  You just have to experiment to find the batch sizes that work.
