### ISSUE TITLE
Can't get faceswap to use my GPU (Windows 10)

### ISSUE THREAD

**Issue by mover96** [deepfakes/faceswap-playground#28]
I installed everything as instructed (using requirements-gpu.txt) and I am able to successfully extract my images, but only using my CPU and not my GPU. I know this because the windows task manager shows that powershell is using 50% of my CPU but 0% of my GPU. Any idea how to get faceswap to use my GPU?

pip freeze output:
```
bleach==1.5.0
click==6.7
decorator==4.2.1
dlib==19.9.0
enum34==1.1.6
face-recognition==1.2.1
face-recognition-models==0.3.0
h5py==2.7.1
html5lib==0.9999999
Keras==2.1.2
Markdown==2.6.11
networkx==2.1
numpy==1.14.0
opencv-python==3.3.0.10
pathlib==1.0.1
Pillow==5.0.0
protobuf==3.5.1
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.6
scikit-image==0.13.1
scipy==1.0.0
six==1.11.0
tensorflow-gpu==1.4.0
tensorflow-tensorboard==0.4.0
tqdm==4.19.5
Werkzeug==0.14.1
```

**Comment by 3xtr3m3d** [comment]
post the terminal output

**Comment by modelsex** [comment]
https://github.com/davisking/dlib/archive/master.zip
Download this git, then run setup.py inside it.

**Comment by Clorr** [comment]
2 things in faceswap use GPU : Tensorflow and Dlib. Dlib gpu is not mandatory unless you use a special extract (called cnn or mmod). Please also post your python version
