### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by 95011913qqcom** [deepfakes/faceswap-playground#289]
resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

Thread error caught: [(<class 'Exception'>, Exception('Error in child process 30792. Traceback (most recent call last):\n File "H:\\faceswap\\faceswap-master\\plugins\\extract\\align\\_base.py", line 106, in run\n self.align(*args, **kwargs)\n File "H:\\faceswap\\faceswap-master\\plugins\\extract\\align\\_base.py", line 132, in align\n item["landmarks"] = self.process_landmarks(image, item["detected_faces"])\n File "H:\\faceswap\\faceswap-master\\plugins\\extract\\align\\_base.py", line 162, in process_landmarks\n feed_dict = self.align_image(detected_face, image)\n File "H:\\faceswap\\faceswap-master\\plugins\\extract\\align\\cv2_dnn.py", line 85, in align_image\n interpolation=interpolation)\ncv2.error: OpenCV(4.1.0) C:\\projects\\opencv-python\\opencv\\modules\\imgproc\\src\\resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function \'cv::resize\'\n\n',), <traceback object at 0x00000224E53C2708>)]

**Comment by torzdf** [comment]
Problem with one of your images, probably special characters in the filename.
