### ISSUE TITLE
Re-using model files

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap-playground#294]
A question about general usage.

Supposing I train two faceset A and B with a model, so I can swap the face of A to B.

Then, I change the A faceset to a new faceset A', so I can swap the face of A' to B.

B faceset stays the same.

Is it better to start a training from scratch or does copying the files from the previous training will save some training time?

On intuition, it should save some time, because it already learned some poses and expressions, but on the other hand, it will have to train longer to "forget" some of the features of the previous A face.

So, is the answer "it depends"? :)

**Comment by bryanlyon** [comment]
Keeping the B decoder and the shared encoder should be fine.  But I'd replace the A decoder and start everything from there.  Since it's you, I'd also recommend lowering the encoder's learning rate so it doesn't change too much with the new A.

**Comment by Kirin-kun** [comment]
Okay, thank you.
