### ISSUE TITLE
Understanding GAN model's choices

### ISSUE THREAD

**Issue by Luna419** [deepfakes/faceswap-playground#297]
I'm currently working with the GAN model and I have pretty good results. I'm now trying to understand the choices that were made for the training. For example, why is it interesting to calculate the loss of the discriminators (d_lossA and d_lossB) with the mixup option ?

**Comment by deepfakes** [comment]
GAN was removed from this repo a long time ago.

**Comment by deyu260** [comment]
> I'm currently working with the GAN model and I have pretty good results. I'm now trying to understand the choices that were made for the training. For example, why is it interesting to calculate the loss of the discriminators (d_lossA and d_lossB) with the mixup option ?

can you put your result from gan model?  i am doing the same thing .

**Comment by Luna419** [comment]
Here is a 2s video of deepfake (Oliver to Fallon). The conversion to gif format lowered the quality but you can see that the face is quite ok. However the edges of the part rebuilt by the gan can clearly be seen.  

![John_Oliver_Trim_2s_120000ep_GAN_blur](https://user-images.githubusercontent.com/48792906/61065257-9e58fd00-a403-11e9-94bf-e79856983e94.gif)
