### ISSUE TITLE
ImportError: cannot import name QueueHandler

### ISSUE THREAD

**Issue by dastardlydawgy** [deepfakes/faceswap-playground#299]
Please fill-in the form below to help others understand your problem.

NOTE: We assume you have first tried to read the README and the INSTALL files. Also prior to  opening an issue, you should search for similar issues an look if someone had your problem before! 

If your problem is specific and that you decide posting an issue, don't forget to close it afterwards. Also you should consider adding information to the documentation once you have found a solution to your problem. The repository here can only live with the contribution of everyone, and not only with developers helping noobs...

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment]
You are not in your faceswap environment

**Comment by dastardlydawgy** [comment]
Damn that was fast, thanks!

**Comment by dastardlydawgy** [comment]
changed the directory to my "faceswap_env" and tried running "python faceswap.py -h" and I get "can't open file 'faceswap.py': [Errno 2] No such file or directory." So that can't be right.  

the faceswap_env is located in a parent folder called faceswap and that parent folder contains all the code downloaded from git, so that has to be the correct directory since the faceswap_env contains only bin, lib, and include folders.  

As you can tell I am terribly new to this.

python 3.7
anaconda 3
Mac OSX 10.11.6

**Comment by dastardlydawgy** [comment]
realized i should have been typing "python3" that fixed it.
