### ISSUE TITLE
Before trying to install this REPO...

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap-playground#32]
I already have installed all the things from this guide: https://www.reddit.com/r/deepfakes/comments/7nq173/v2_tutorial_intelbased_python_easy_to_follow/ this was when there didn't exist the APP.

Also i have CMAKE (cmake-gui), cuda 8, PYTHON 3.6.3 (ANACONDA3 5.0.1 64-BITS).

https://i.imgur.com/jmlqxgp.jpg

But i really want to try this repo. (i know i will need to do most of the things VIA CMD commands).

I'm not a programmer or anything, so i want to know if i foloow the installation instructions for this REPO, it will not fuck UP my other installation right?

For what i read if i do it trough **Virtualenv** (i suppouse it's like a virtual environment):

> Windows specific:
> 
> virtualenvwrapper-win is a package that makes virtualenvs easier to manage on Windows.
> 
> pip install virtualenvwrapper-win

Everything will be downloaded/installed there without messing with other installations, i'm right?

Also if i can't do it, someone could help me **VIA TEAMVIEWER** to install it? 

thx in advance!

**Comment by 3xtr3m3d** [comment]
no it wont.  its easy to run this. just download and extract this to a folder and open a command prompt in this directory.

then install requirements with

pip install -r requirements-gpu.txt

after its done follow the readme

**Comment by modelsex** [comment]
pip install one by one in <requirements-gpu.txt>, then update here which one you meet error.
