### ISSUE TITLE
about convert

### ISSUE THREAD

**Issue by cute-angelia** [deepfakes/faceswap-playground#34]
![112270915](https://user-images.githubusercontent.com/26561606/35959688-981fb768-0ce1-11e8-845b-37e4c4ad9efb.jpg)

![461642204](https://user-images.githubusercontent.com/26561606/35959691-9dd43206-0ce1-11e8-8da1-cdf1bf59bb2f.jpg)

when i cmd "python faceswap.py convert -i ~/faceswap/photo/trump/ -o ~/faceswap/output/ -m ~/faceswap/models/"  ,  the imgs has "mosaic" 

without  swapped cage

What should I do? 

thank you

**Comment by kevers429** [comment]
looks good to me

**Comment by ProtonSato** [comment]
How long did the network train for? Seem to me only a few minutes.
