### ISSUE TITLE
Python version clarification

### ISSUE THREAD

**Issue by GSonderling** [deepfakes/faceswap-playground#35]
Installation guide specifies/recommends 3.6
https://github.com/deepfakes/faceswap/blob/master/INSTALL.md

But script only checks for 3.2. 

Either the script or the guide should be adjusted, to make sure no confusion occurs. 

It will save time and issue reports later.

**Comment by ProtonSato** [comment]
I believe a minimum of Python version 3.2 is required however since the latest version 3.6 it links to that in the guide instead.

**Comment by GSonderling** [comment]
Well in that case the guide should be changed. There is no need for people to fill their machines with clutter.

**Comment by Clorr** [comment]
Thanks for this, I just added a comment on your PR, but it should be accepted without problem
