### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by BobMacpherson** [deepfakes/faceswap-playground#37]
Archlinux 4.15.2
Python 3.6.4
Faceswap commit 20753a6

When running any command with "python faceswap.py" it fails to run and errors out "illegal hardware instruction" and fails to launch.  All deps have been installed via pip.
Found this in dmesg.
python[24460] trap invalid opcode ip:7fb4d67981ad sp:7ffd16de66c0 error:0 in dlib.cpython-36m-x86_64-linux-gnu.so[7fb4d6309000+5c5000]

**Comment by Tyrannosaurus1234** [comment]
My guess is Dlib is compiled with instruction sets your CPU doesn't support. Check which ones your CPU supports and compile Dlib with only those enabled - you can turn off AVX, SSE4.1, and SSE4.2.

**Comment by BobMacpherson** [comment]
Beyond 'python setup.py install', where would you pass the instructions to enable or disable?

**Comment by Clorr** [comment]
Could be also a 32 vs 64bit issue

**Comment by Clorr** [comment]
Can it be something like this?
https://github.com/davisking/dlib/issues/352

**Comment by BobMacpherson** [comment]
Fixed.
Had to patch dlib/tools/python/CMakeLists.txt in python-dlib to change sse4 to sse2. Using cmake options by them selves did not disable it
