### ISSUE TITLE
I built end-user 'FaceSwap build 155' for my Russian people

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#39]
easy to use bat files

tested on clean Windows 7 and Windows 10

no dependencies, except NVidia Video Drivers, NVidia Cuda 8.0, and 2015,2017 redist (included in torrent)

build 155 pull request with aligments.json, so no memory error on convert

https://rutracker.org/forum/viewtopic.php?t=5519086
magnet:?xt=urn:btih:B17828F816A9598A47FFD800900514A92B48B3C0

![314da1668232a284e5626778a5382d02 1](https://user-images.githubusercontent.com/8076202/36065660-3f5ef472-0eb7-11e8-9e79-2440f314220f.png)

**Comment by Apollo122** [comment]
I would say this is the start of GUI for faceswap. I hope you will do it next.

**Comment by iperov** [comment]
sry, I dont need GUI.
there are not so many various options, so I think cmd batches enough for now.

**Comment by ruah1984** [comment]
Do you have the instruction in English ?

**Comment by iperov** [comment]
sry no,
 use https://translate.google.com/

**Comment by ruah1984** [comment]
May I know if it can run with CPU tensorflow?

**Comment by iperov** [comment]
no CPU sry.

**Comment by Clorr** [comment]
You can PR this in the main repo by putting this in a dedicated folder ( `bat/ `for example)

**Comment by kgoodboy** [comment]
Dear iperov,

I'm really interested in your work, and have would like to have some discussion and questions on the result I have.

Can you leave your email or any other contact to 
kisagoodboy2018@gmail.com

Thanks,
