### ISSUE TITLE
Look into different methods of face alignment 

### ISSUE THREAD

**Issue by Ganonmaster** [deepfakes/faceswap-playground#4]
https://www.reddit.com/r/deepfakes/comments/7lae4c/face_alignment_scripts_based_on/

**Comment by deepfakes** [comment]
He he, I saw this one also ;-)

Can you please open the issue in faceswap-model ? It's not really about model, but it's more related to algorithm enhancement than user helping...

(I hope the 3 repo are not too redundant... I tried to keep separated `usage`, `development`, and `theory`)

**Comment by lactoseintolerant** [comment]
Is it correct that this alignment method was not implemented into faceswap? I believe df/dfaker uses this though?
