### ISSUE TITLE
Is there any seamless-like setting while using the GAN models?

### ISSUE THREAD

**Issue by salre9501** [deepfakes/faceswap-playground#40]
I know you can't use seamless with the GAN models, but is there any way to get rid of the visible square?

**Comment by Clorr** [comment]
GAN uses a masked convert so you shouldn't have square. Please also post a sample

**Comment by salre9501** [comment]
Here's the vid and I only trained for 30 minutes (might be NSFW):

http://sendvid.com/k4t4yjvy

Will the square go away with more training. I'm getting better results with the original model, but GAN might be better in the long run.
