### ISSUE TITLE
Failed loading existing training data

### ISSUE THREAD

**Issue by ghostbusters43** [deepfakes/faceswap-playground#42]
I ran the extract and trained for a while, but when I go to convert the images, I end up getting this error:
Failed loading existing training data.
You are trying to load a weight file containing 6 layers into a model with 7 layers.
Model Not Found! A valid model must be provided to continue!

This is what I used to train:
faceswap.py train -A data/extracted -B data/trump -bs 64 -t LowMem -w -s 1 -p -m data/model
This is what I used for convert:
faceswap.py convert -i data/okb -o modeltest -m data/model

Am I doing something wrong? I tested this with the trump/cage data and it worked fine with no error.

**Comment by iperov** [comment]
**convert** also **-t LowMem**

**Comment by iperov** [comment]
also convert and extract use --detector cnn
hog converter totally suxx

**Comment by ghostbusters43** [comment]
Removing -t LowMem just end up not letting me train the data due to ResourceExhaustedError :/

**Comment by iperov** [comment]
why removing **-t LowMem** ?
add it to **convert**

**Comment by ghostbusters43** [comment]
Oh sorry I misunderstood
It doesn't appear to be a valid command for convert when I add it though

**Comment by iperov** [comment]
yes you use old code
![notepad _2018-02-11_19-53-06](https://user-images.githubusercontent.com/8076202/36075234-5be9f958-0f65-11e8-8785-cf93f6096a92.png)

**Comment by ghostbusters43** [comment]
Alright that seemed to fix it. I just have CUDA errors but that's from tensorflow so I need to downgrade. Thanks!
