### ISSUE TITLE
CNN extractor problem

### ISSUE THREAD

**Issue by LordVulkan** [deepfakes/faceswap-playground#43]
With CNN extractor I'm getting more faces angles but the zoom and alignement are not consistent. 

This hand-made image is an example of some different extractions I get (forget the white background and focus on the faces):

![image](https://user-images.githubusercontent.com/562386/36076150-b467a15a-0f58-11e8-93f8-c2c7be93e049.png)

In a video of a frontal face I can get the first type of extraction for X frames but then suddenly I start to get zoomed in frames. Many of them are also not properly aligned and look like the images 4 and 5.

Is this good for training? Should I just use the hog extractor for now?

**Comment by Clorr** [comment]
Can you try with hog and post the comparison please?

**Comment by Apollo122** [comment]
Yeah I also had zoomed in outputs with CNN. It's a custom code but it uses same stuff I think.

https://github.com/deepfakes/faceswap/issues/162#issuecomment-364703657

**Comment by LordVulkan** [comment]
I will do some tests comparing hog and cnn and post the results later.

**Comment by LordVulkan** [comment]
Side by side comparison, left extracted with hog, right with cnn. With hog the alignement is 99.9% ok and in a very few frames the zoom is wrong. With cnn it is a mixed bag. (Yeah, its pron).

![image](https://user-images.githubusercontent.com/562386/36076899-22080b14-0f63-11e8-921b-3aede9af5b50.png)
![image](https://user-images.githubusercontent.com/562386/36076947-b808a240-0f63-11e8-815f-8023443a140b.png)
![image](https://user-images.githubusercontent.com/562386/36076988-82d83c9c-0f64-11e8-80ac-d22073535bb4.png)


![image](https://user-images.githubusercontent.com/562386/36076937-861556de-0f63-11e8-9a2e-4dd2c52c4fd4.png)
![image](https://user-images.githubusercontent.com/562386/36076966-18c506b4-0f64-11e8-80c4-c9d7a2782f7a.png)
![image](https://user-images.githubusercontent.com/562386/36076979-524022fc-0f64-11e8-9ef7-bf6cea4e8a17.png)

**Comment by Deadfishzzway** [comment]
I tried to train with dataset that are mixed with cnn and hog detection. The result is horrible. I guess it could be due to the zoom issue

**Comment by Clorr** [comment]
Maybe the face landmarks are not found. Do you have some message like: "Warning! landmarks not found. Switching to crop!"

**Comment by LordVulkan** [comment]
No warnings of any kind.

**Comment by Clorr** [comment]
In `lib/detect_faces.py` , can you add some logging with this code:
```
def detect_faces(frame, model="hog"):
    face_locations = face_recognition.face_locations(frame, model=model)
    landmarks = _raw_face_landmarks(frame, face_locations)
    print(face_locations)
    for ((y, right, bottom, x), landmarks) in zip(face_locations, landmarks):
        print([(p.x, p.y) for p in landmarks.parts()])
        yield DetectedFace(frame[y: bottom, x: right], x, right - x, y, bottom - y, landmarks)
```
Run it on misaligned faces and let me know the result

**Comment by LordVulkan** [comment]
Extracted face:

![rebeca2-1-0000020](https://user-images.githubusercontent.com/562386/36106417-91aad2bc-1017-11e8-9f12-b8990ef82be7.png)

print(face_locations)
`[(122, 251, 204, 169)]`

print([(p.x, p.y) for p in landmarks.parts()])
`[(180, 158), (179, 165), (178, 172), (178, 180), (178, 188), (180, 195), (184, 198), (189, 201), (197, 203), (208, 204), (220, 204), (231, 203), (240, 199), (246, 191), (249, 182), (251, 173), (253, 162), (180, 140), (181, 134), (185, 130), (189, 129), (194, 130), (205, 130), (212, 128), (221, 130), (229, 136), (234, 143), (199, 138), (197, 142), (194, 146), (192, 150), (191, 160), (193, 161), (195, 162), (199, 162), (204, 162), (185, 144), (187, 140), (191, 140), (194, 143), (190, 144), (187, 144), (212, 144), (216, 140), (221, 141), (226, 145), (221, 145), (216, 145), (189, 177), (190, 171), (193, 169), (196, 170), (199, 169), (205, 173), (212, 180), (205, 178), (199, 176), (196, 176), (193, 176), (190, 176), (190, 176), (193, 172), (196, 173), (199, 173), (210, 178), (199, 174), (196, 173), (193, 173)]`

**Comment by Clorr** [comment]
Ok, so it finds landmarks but does not the align. I'm checking this

**Comment by LordVulkan** [comment]
That face is not detected by hog extractor. I'm preparing a comparison between a few faces properly extracted by hog and badly extracted by cnn.

**Comment by Clorr** [comment]
can you provide me the source frame?

**Comment by Clorr** [comment]
or part of it if it is too NSFW

**Comment by LordVulkan** [comment]
Surprisingly, when cropping the NSFW side of the image the results have been altered despite not modifying the face and now are acceptable.

How can I send you an email or something with the frames?

**Comment by Clorr** [comment]
Put it somewhere online and paste the link here

**Comment by LordVulkan** [comment]
https://mega.nz/#!CUJFUbJD!FvNgLHK3p_agMkQ_vG1NbI3fyDjoM8w1Gwl6xEu2jwE

I have included the cropped frames too for you to see what I said in my previous post, they are inside the 'input' folder.

**Comment by Clorr** [comment]
Landmarks clearly don't match the face so it seems to be a problem on the dlib side.

![frame10](https://user-images.githubusercontent.com/873943/36110822-52dbc728-1024-11e8-8537-b17f2f02f289.png)
![frame20](https://user-images.githubusercontent.com/873943/36110823-52ff4a7c-1024-11e8-8541-0786b6906b72.png)
![frame30](https://user-images.githubusercontent.com/873943/36110824-5322db86-1024-11e8-9182-9b6c0a0ade5f.png)

**Comment by Clorr** [comment]
I'll open an issue on the main repo
