### ISSUE TITLE
FaceSwap vs FakeApp with same footage

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#45]
FakeApp 4 layers 1024 dim
FaceSwap -t Original

![mpc-hc64_2018-02-12_07-25-39](https://user-images.githubusercontent.com/8076202/36083214-bebf29d6-0fc9-11e8-9a0c-ede7843ec5d5.jpg)
![mpc-hc64_2018-02-12_07-47-55](https://user-images.githubusercontent.com/8076202/36083215-bedb1600-0fc9-11e8-97c6-2e064b95d640.jpg)
![mpc-hc64_2018-02-12_07-48-04](https://user-images.githubusercontent.com/8076202/36083216-bef7937a-0fc9-11e8-9dfc-c478d608ccb3.jpg)
![mpc-hc64_2018-02-12_07-48-40](https://user-images.githubusercontent.com/8076202/36083217-bf13685c-0fc9-11e8-8203-c29b1a037ff9.jpg)
![mpc-hc64_2018-02-12_07-49-02](https://user-images.githubusercontent.com/8076202/36083218-bf2fb16a-0fc9-11e8-9a43-aa1ad0de091a.jpg)
![mpc-hc64_2018-02-12_07-49-13](https://user-images.githubusercontent.com/8076202/36083219-bf4bb2a2-0fc9-11e8-817d-6dac749b2596.jpg)

**Comment by ruah1984** [comment]
Do you think because of merging problem ?

**Comment by iperov** [comment]
no problem, FaceSwap better :)

**Comment by ruah1984** [comment]
can you tell, what is different between the faceswap and fakeapp?? especially for the  training model. the Neural network layer, node are there same??
