### ISSUE TITLE
Trying to run faceswap.py to extract faces, receiving 'No module named *' errors

### ISSUE THREAD

**Issue by MisterGenerosity** [deepfakes/faceswap-playground#51]
I'm trying to run the python faceswap.py command.

No matter what I do, I am returned with an error that says 'ModuleNotFoundError: No module named 'tqdm'.

I had been receiving different errors. First it said No moduel named 'lib'. I noticed in my Faceswap directory that the directory was Lib, so I changed its case (unsure if this would have any effect) to lib. That error then went away, oddly enough. But now I receive this error and am unsure how to proceed.

I'm Windows 7 x64, running Python 3.6

**Comment by kevers429** [comment]
sudo pip install tqdm
