### ISSUE TITLE
Difference between -t Original and LowMem?

### ISSUE THREAD

**Issue by KMMR156** [deepfakes/faceswap-playground#52]
I see that `ENCODER_DIM` is lowered to 512 in LowMem and `x = self.conv(1024)(x)` is commented out, but how does that affect the end result of the training? If I use LowMem can i get the same quality as Original but it takes longer?

**Comment by Clorr** [comment]
Potentially the model will have less memory to store the features, so it may result in a less accurate model. But it is hardly quantifiable
