### ISSUE TITLE
Conversion doesn't seem to use all resources

### ISSUE THREAD

**Issue by zimtmilchreis** [deepfakes/faceswap-playground#53]
## Expected behavior
Not sure how convert works and which parts of GPU are needed, but it seems that GPU is a lot less stressed when convert is executed than in training case. So I suspect that it does not use all resources (maybe this could be optimized and be configurable or sth).

## Actual behavior

Convert does not use PC resources - GPU and CPU seems to be not really  used
1.75 it/s 1500 images, ~14 minutes
Well I've read old topic
https://github.com/deepfakes/faceswap/issues/184
and it seems that's quite good result but honestly I am not sure if comparing results to other people is meaningful at all

With DLIB whl 19.8.1 (which throws an error for dlib.DLIB_USE_CUDA - lol)
Training takes **80**% VRAM, 104% GPU speed, temp is **61**C, you can literally hear that GPU is working.
GPU Clock 1427, Memory Clock 6010, Memory Usage 3600MB

Same library, this time convert:
GPU clock 1113, Memory Clock 6010, Memory usage 3602, temp is **45**, **vram 6**%
Maybe that's normal? Hard to say, seems suspicious to me.

I've compiled ddlib 19.9 (couldn't find one for Windows), for some reason it gets OOM very quickly with same model so training does not work, but for convert part it finally says that DLIB_USE_CUDA is true 
yet I get same results/performance

CPU usage is 67% on one core, remaining ones are idle

## Steps to reproduce

Windows, python 3.6, GTX970, CPU 6700K, conversion of images without aligment file (before latest improvements), parameters seem to make no difference, images size is 1280x720

## Other relevant information

- **Operating system and version:** Windows
- **Python version:** 3.6.4
- **Faceswap version:** 51f1993d93e0ffb581d44416f327f0cf731c34e8
- **Faceswap method:** GPU
- ...
![couusage](https://user-images.githubusercontent.com/36545113/36321308-aafabb80-1349-11e8-9968-27558f3ab922.JPG)
![train_dlibnocuda](https://user-images.githubusercontent.com/36545113/36321310-ab9ad656-1349-11e8-8472-8248cd4d04da.JPG)
![convert_cuda](https://user-images.githubusercontent.com/36545113/36321311-ac2c5748-1349-11e8-9f9d-15bab64697c0.JPG)

**Comment by zimtmilchreis** [comment]
Update:
- it seems that if you have alignments it works much faster, though I guess in such case we should look at the conversion time.
- i've downloaded recent version of faceswap, installed gpu requirements for python with pip --no-cache-dir option. It downloaded all necessary packages without any errors. 
print (dlib.DLIB_USE_CUDA) returns true

yet it seems that during conversion (hog) both gpu and cpu seems to be at idle
Fakeapp 1.1 for the same set it two times faster and GPU seems to be under load (though also not 100%):

python faceswap.py extract -i inputDir -o outputDir--serializer yaml -D hog
156/7050 [01:26<1:03:25,  1.81it/s]

Fakeapp1.1
169/7050 [00:47<32:13,  3.56it/s]
also for some reason it seems like fakeapp extracts more faces afaik. 

Process option doesn't work, google indicates that there might be some problem with globals when new process is created:

Writing alignments to: DataPath\alignments.yml
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "somePathpython\python36\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "appPath\lib\multithreading.py", line 16, in runner
    return method(item)
TypeError: 'NoneType' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "faceswap.py", line 32, in <module>
    arguments.func(arguments)
  File "appPath\lib\cli.py", line 62, in process_arguments
    self.process()
  File "appPath\scripts\extract.py", line 49, in process
    for filename, faces in tqdm(pool_process(self.processFiles, files, processes=processes), total = len(files)):
  File "appPath\virtenv\lib\site-packages\tqdm\_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "appPath\lib\multithreading.py", line 12, in pool_process
    for i in pool.imap_unordered(runner, data):
  File "somePathpython\python36\Lib\multiprocessing\pool.py", line 735, in next
    raise value
TypeError: 'NoneType' object is not callable


(virtenv) appPath>

**Comment by ZeroCool22** [comment]
@zimtmilchreis  How is the command i should use for no cache?

pip install **--no-cache-dir** -r requirements-gpu-python36-cuda9.txt 

Like that?

**Comment by zimtmilchreis** [comment]
yes, though I've uninstalled (pip uinstall) libraries first
