### ISSUE TITLE
Seems training data link is broken

### ISSUE THREAD

**Issue by pchel-** [deepfakes/faceswap-playground#55]
Training data link [https://anonfile.com/p7w3m0d5be/face-swap.zip](https://anonfile.com/p7w3m0d5be/face-swap.zip) does not work. 

Could you please provide new one that works?

**Comment by beibuwandeluori** [comment]
https://cdn-05.anonfile.com/p7w3m0d5be/ac40cef3-1556999115/face-swap.zip
you can try this link
