### ISSUE TITLE
is this behavior normal?

### ISSUE THREAD

**Issue by 3xtr3m3d** [deepfakes/faceswap-playground#56]
Hi

is this kind of output is normal? whatever the mask i applied looks like i can't get rid of two eyebrows

is this normal or my dataset is having problem?

https://imgur.com/s1R9Qf6

Regards

**Comment by Apollo122** [comment]
Increase kernel size to crop outer part.

**Comment by 3xtr3m3d** [comment]
> Increase kernel size to crop outer part.

looks like that did the trick. but then it seems like lips are having problem.  any chance you know the default kernel size? 

i just checked with 32 as a random value
