### ISSUE TITLE
Trying to train with GAN...

### ISSUE THREAD

**Issue by enniowatson** [deepfakes/faceswap-playground#57]
First of all, please pardon my ignorance as just about all of this is brand new to me. I've been going through the basic trial and error trying to figure out how things work. I've gotten pretty good results with the original model. I wanted to try out the GAN model as I've seen elsewhere how well it can handle obstructions to the face and other issues. However I'm not getting any good results.

I've noticed that in the "alpha mask" preview window, the second and third columns for each image are basically pure white. I expected an image to show up (as seen in other examples) after training for a while, but nearly 18 hours in there was no noticeable difference.  The raw and masked preview windows were showing gradual improvement, though not great. When I tried to convert I just wound up with grey squares over the face. I have about 1,000 aligned images for face A and 700 for face B.

Am I doing something majorly wrong? Does it just need (a lot) more time? Just trying to figure it out.

**Comment by ZeroCool22** [comment]
The GAN thing is **pure hype**, i have not seen ayone to get a good results like the exmples GIFS shows and i tried...

https://www.youtube.com/watch?time_continue=1&v=sKhBkUVeFyQ

**Comment by Apollo122** [comment]
Treat the GAN code here as a draft. There are features to be implemented. And so far only @clorr worked on it and he seems to be missing nowadays :) yes GAN needs more time for training but it provides detailed 128x128 resolution masked faces and with PL more realistic eye movements. In my opinion totally worth the extra time

**Comment by shaoanlu** [comment]
I have no idea where the x10 factor comes from. I got the results shown in the repo. after ~20k iters. And iter take 2sec. on K80. Also I shown some result after 4~5 hrs of training with different dataset in [this issue]((https://github.com/shaoanlu/faceswap-GAN/issues/50)).

**Comment by ZeroCool22** [comment]
@shaoanlu 

**SOURCE:** https://www.fakeapp.org/forum/releases-tech-support/have-fakeapp-taken-the-advantages-of-faceswap-gan

**Comment by Ianmcmill** [comment]
@enniowatson I have noticed the same (on windows). After saving the model with Q and restarting the training process several times (on-off training during the day) I noticed that the alpha masked window got updated from pure white to face edges. similar to effect when doing edge detection with a graphc suite like photoshop.

Try to save a restart.

**Comment by oatssss** [comment]
@Ianmcmill so your masks were full-white for a little bit, but then you powered through it and eventually they came back looking good??

**Comment by Ianmcmill** [comment]
@oatssss Honestly I can't remember. I think I just let it run and they are now looking like "ordinary" alpha maps. Black/White. Maybe (?) the model saving and reloading just updated the preview prematurely. No idea.

**Comment by Apollo122** [comment]
@oatssss yeah. If we are 100% sure that port is correct that means something is wrong with preview? But I'm so not sure @ruah1984 reports that he is getting different results using gan repo. We should make sure that port is correct and complete before convert stuff

**Comment by Apollo122** [comment]
Definitely something is off. Not just second column is being full white also our preview masks are zoomed in. 
@ruah1984 what's changing loss function to 1e-3?

**Comment by ruah1984** [comment]
as shaoanlu comment to change for mask refinement after >15k 

# cell below
loss_GA += 3e-3 * K.mean(K.abs(mask_A))
loss_GB += 3e-3 * K.mean(K.abs(mask_B))
to

# cell below
loss_GA += 1e-3 * K.mean(K.square(mask_A))
loss_GB += 1e-3 * K.mean(K.square(mask_B))

**Comment by Apollo122** [comment]
Hmm must have missed that.
@oatssss you can add these lines as well. These are to be activated with the Boolean we talked before
