### ISSUE TITLE
Question on modifying the 64x64 training image size

### ISSUE THREAD

**Issue by lactoseintolerant** [deepfakes/faceswap-playground#59]
I'm trying to figure out what sets the training image size. Currently, I understand it is 64x64. Naively, why can't you just resize by setting IMAGE_SHAPE=(128,128,3) in model.py and then in training.py, use cv2.resize on the target and warped images?

I know for a fact this doesn't work :), whether I try to go up to 128x128 or down to 32x32.

I also tried adjust the encoder output so that the final command:
x = self.upscale(64)(x)
matches the desired dimensions... doesn't seem to work either.

Would appreciate if someone could point out what I am missing.

**Comment by Clorr** [comment]
When you say "doesn't seem to work " what do you get? AFAIK autoencoders are not well suited for high resolution outputs but 128x128 doesn't seem that big. However memory usage and training time may be increased

**Comment by lactoseintolerant** [comment]
I wanted to test downscaling first to 32x32, since that should guarantee that memory issues are absent.

I had problems with tensor shapes matching but got some input over here on how to check sizes. https://github.com/dfaker/df/issues/20

Haven't had time to test more as I need to read up on layers first.
