### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by deepfakes** [deepfakes/faceswap-playground#6]
_Note: Installation requires a bit of knowledge. Project is a work in progress, and people able to help are welcomed to._

## Without Docker
 - First install Python and Pip (Google is your friend).
 - Install requirements. You can do so with `pip3 --no-cache-dir install -r ./requirements.txt` (`pip3` for Python3 users, otherwise use `pip`)
 - If it doesn't work or if you miss dependencies. You can look at the Dockerfile that may help you find out which dependecy is missing

## With Docker
 - Go to the code folder
 - Run `docker build -t deepfakes .`
 - Once finished, you can start `docker run --rm --name deepfakes -v [path_to_your_folder]:/srv -it deepfakes bash`
 - Once it starts, you will have a prompt, and be able to run the commands

**Note:** This is for a CPU run.
If you want to use GPU, install outside Docker, and use `requirements-gpu.txt`
If you want to use Docker with GPU support, it is possible, but only for advanced users, so I assume you are advanced enough to find out how ;-)

**Comment by Clorr** [comment]
Another resource that may help you, found on reddit:

https://www.reddit.com/r/deepfakes/comments/7n00f2/really_high_level_tutorial/

**Comment by Clorr** [comment]
Also:

https://www.reddit.com/r/deepfakes/comments/7n6mly/new_here_read_this_windows_x_anaconda_python_x/

**Comment by vamzii** [comment]
made a video, hope it helps the community
https://www.youtube.com/watch?v=XcRgA9DDB14
