### ISSUE TITLE
Continue training model

### ISSUE THREAD

**Issue by MisterGenerosity** [deepfakes/faceswap-playground#60]
Is it possible to stop training a model and then continue training that same model if the results aren't that great? I've been training for about 2 days and I'd like to see how it looks, but I'd hate to lose my progress.

Also, is the smoothing and color averaging mentioned [here](https://github.com/deepfakes/faceswap/issues/30) included in the `python faceswap.py convert` command?

@Apollo122 Tagging you because you seem to know what you're talking about and you're actually active around here. I hope that's ok.

**Comment by Apollo122** [comment]
Yeah it's ok. Yes you can stop the training and continue later. If preview window is open click on it and press q. I think enter also works but try q first.

Those options can only be used with Adjust converter. I don't prefer it but if you want to use it you should use convert with -c Adjust . Their default values are true. You can also open convert.py with wordpad to check masked converter and it's options. Convert.py is under scripts folder.
