### ISSUE TITLE
utils.py in lib needs 'scandir' but it is missing

### ISSUE THREAD

**Issue by Lady-Moonshadow** [deepfakes/faceswap-playground#61]
I was trying to start with step one - extracting faces from pictures.

Everything is installed correctly but it does not start cause it is unable to find "scandir"

(faceswap_env) ubuntu@ubuntu-AI-Foundry:~/YouTube-Videos$ python3.5 faceswap.py extract -i file:///home/ubuntu/YouTube-Videos/Dan  -o file:///home/ubuntu/YouTube-Videos/Dan/Dan_Data 
Traceback (most recent call last):
  File "faceswap.py", line 8, in <module>
    from lib.utils import FullHelpArgumentParser
  File "/home/ubuntu/YouTube-Videos/lib/utils.py", line 5, in <module>
    from scandir import scandir
ImportError: No module named 'scandir'

Please help.

**Comment by Apollo122** [comment]
pip install scandir

**Comment by Lady-Moonshadow** [comment]
Thanks :) There where more components missing. I keep this Issue online for others with the same Problem :)
