### ISSUE TITLE
Faceswap installation problem on newly install clean python3.6

### ISSUE THREAD

**Issue by 09milk** [deepfakes/faceswap-playground#62]
I try to install Faceswap on Windows10 with python3.6, but fail at installing dlib, and seems the only pre-compiled binaries of dlib for python3.6 is outdated.

while trying to install dlib with `pip install dlib`, more problem occur, and after a bunch of googling, [someone](https://stackoverflow.com/questions/45545050/error-during-boost-and-dlib-installation-for-python-3-6) claim that dlib don't support python3.6, on the other hand, [faceswap's contributor recommended using python3.6 for Faceswap](https://github.com/deepfakes/faceswap/issues/42)

## Expected behavior

run 
`pip install -r requirements-gpu-python36-cuda9.txt`
and all dependencies should be installed

## Actual behavior

while all other dependencies is fine, I had a hard time trying to install dlib

**Comment by b4nn3d** [comment]
I can confirm this (w10 64, py  3.6.4).

I had to manually build dlib from this https://github.com/davisking/dlib

**Comment by MT-4ier** [comment]
I ran into this too.
What seemed to be the problem was cmake, so running
`pip install cmake`
and then installing dlib after that fixed things.

**Comment by 0xCABE** [comment]
pip install cmake did not work for me. I found another solution that is very quick and does not require one to manually compile dlib.

1. Go to [this site](https://pypi.python.org/pypi/dlib/19.7.0) and download [the whl file.](https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl#md5=b7330a5b2d46420343fbed5df69e6a3f)

2. run the command ```pip install <the path to the whl file>```

**Comment by Clorr** [comment]
Hi, is that issue closed? Feel free to add info to the docs in the main repo to help others ;-)
