### ISSUE TITLE
OpenCV and Dlib compiled to use CUDA, but 0% GPU use when running faceswap.py extract?

### ISSUE THREAD

**Issue by gessyoo** [deepfakes/faceswap-playground#63]
Please fill-in the form below to help others understand your problem

## Expected behavior:  OpenCV and Dlib compiled to use CUDA, shouldn't GPU be used during extract/align process? 

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*
 Running Anaconda 3.6, Windows 10 x64, Nvidia GTX 1070, complied opencv and dlib from source (VS 2014) with CUDA 8.0 support.  Task manager shows GPU use of 30 to 55% when training, but 0% GPU use during extract/align process.   Can the extract plugin be modified to use the GPU during extract/align?

I'm only a beginner with python and VS compiling, but I would welcome any help in speeding up the extract process by using CUDA.   

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information

- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- ...

**Comment by b4nn3d** [comment]
use another tool, like gpu-z, you will see the real %
for me (1060 6gb) there is full vram usage, low gpu (~15/20)

**Comment by iperov** [comment]
check dlib building log, may be CUDA disabled

**Comment by gessyoo** [comment]
Thanks for the replies.  I've had to re-install Anaconda 3.6 a couple of times. Sometimes dlib will compile to use CUDA and other times it refuses on my machine.  Have both VS 2015 and 2017 installed, it seems to compile with CUDA if VS 2015 is the cmake generator, but I haven't found a bulletproof, step-by-step  compile method yet.  I'm probably missing a step somewhere, trying to follow the discussion at https://github.com/davisking/dlib/issues/1035,

**Comment by Dico200** [comment]
I tried and succeeded in getting the program running yesterday on Windows 10. 
It seems critical that you use python 3.5 for this. Install python 35, select the install location directory, right click, properties, security, edit, give all permissions.

then 
`python -m pip install scandir`
`python -m pip install tqdm`
`python -m pip install keras`
`python -m pip install face_recognition`
`python -m pip install dlib` 
`python -m pip install opencv-python`
`python -m pip install face_recognition`
`python -m pip install tensorflow-gpu`

For the dlib install:
this one can take a while. You need cmake as well as a c++11 supporting visual c++ compiler (visual studio 2017 will do it).
If you run into an issue where it says the visual studio compiler doesn't fully support c++11:

* download dlib 19.9.0 distribution and extract it.
* go into the extracted folder and run `python setup.py --help`
* It should tell you the names visual c++ generators. Remember or copy the one you have installed, along with the Win64 tag appended. For example `Visual Studio 15 2017 Win64`
* Go into /dlib, the CMakeLists.txt file should be here.
* Create a file called PreLoad.cmake with the below line:
`set (CMAKE_GENERATOR "{GENERATOR}" CACHE INTERNAL "" FORCE)`
for example:
set (CMAKE_GENERATOR "Visual Studio 15 2017 Win64" CACHE INTERNAL "" FORCE)
* run python setup.py install

Once you have all the dependencies, get the repo cloned if you haven't already, get your source images and you can get it running.

**Comment by gessyoo** [comment]
Thanks, the best install guide for Win 10 I've seen.   I've got VS 2017 installed and will give it go again with python 3.5, rather than a 3.5 environment under Anaconda 3.6.
