### ISSUE TITLE
GAN128 - Weirdly warped faces in preview

### ISSUE THREAD

**Issue by Ianmcmill** [deepfakes/faceswap-playground#65]
## Behavior

*I am using https://github.com/oatssss/faceswap/tree/update-GAN-v2 and currently train a GAN128 model. The faces however are weirdly warped in masked and alpha mask preview. Like grimaces. Is that intended?*

## Other relevant information

- **Operating system and version:** Ubunut 16.04 - Nvidia 384 - Cuda 8
- **Python version:** 3.5, 
- **Faceswap version:** 51624b3d2f2a394f0ac6130c1208950b77b07199   -  https://github.com/oatssss/faceswap/tree/update-GAN-v2
- **Faceswap method:** GTX 980 4gb

**Comment by oatssss** [comment]
See https://github.com/deepfakes/faceswap/pull/217 for why the masked preview is warped.

**Comment by Ianmcmill** [comment]
Thanks @oatssss 
I am trying to figure out how to "pull" (?) those new updates into my local clone. I cloned the branch "update-GAN-v2" today.

I am not fit with git. No pun intended. I know how to clone but I do not know how to merge those updates into my local clone. 
Your help would be greatly appreciated :)

**Comment by oatssss** [comment]
@Ianmcmill you checked out my branch so you already have a local copy right? Are you trying to merge the branch into some other local changes you made?

**Comment by Ianmcmill** [comment]
I have a local copy and just 15 minutes later you did the commit on averaging. I did not change anything on your code, I just wanted the updated code from your commit in this local copy and I didn't want to download all the files from the zip and copy and replace them.

**Comment by oatssss** [comment]
I suggest using [Sourcetree](https://www.sourcetreeapp.com/) for git so you don't have to mess around with the command line.

Open up sourcetree and follow the instructions here to clone the branch locally (the clone url you should use for my fork is `https://github.com/oatssss/faceswap`): https://confluence.atlassian.com/sourcetreekb/clone-a-repository-into-sourcetree-780870050.html

Once you have it cloned, in the left sidebar, look for the "remotes" section and expand "origin". Double click on the branch `update-GAN-v2` or right-click on it -> checkout...

That'll checkout my branch. If I push any more updates to the branch, go to the top toolbar and click on "fetch" to refresh and find branch updates. If Sourcetree finds updates, there will be a badge on the "pull" icon indicating how many updates there are. You can then click on "pull" to receive those updates.

**Comment by Ianmcmill** [comment]
@oatssss thanks oats. I use git for some time but never came beyond git clone. Downloading the zip seems the most efficient method (for me!). I will try Sourcetree but from your explanation, fetch and pull now makes more sense to me. Didn't quite get the pull when I tried that before sometime. Will look into this.

Thanks for you explanation!
