### ISSUE TITLE
App based on repo code?

### ISSUE THREAD

**Issue by mike-truk** [deepfakes/faceswap-playground#67]
First -- **thanks everyone** for your fantastic contributions to this project.

_(this may have been discussed already)_
Is the latest version of the app (v2.2) using the same code that's staged in the faceswap repo?

I thought that was the case but many of the tests I've run using the evolving code in the GIT repo (spanning back before the subreddit ban -- when there was only one training mode) have resulted in inconsistent scaling over a sequence of frames, as well as noticeable bounding boxes. I was using the provided Trump/Cage data for GPU training; and trained for various lengths of time (from 6-48hrs) in both Original and GAN modes.

I figured I should get at least something that is consistent over a sequence of frames using the Original method with some blur and erode, but it's still super inconsistent and very sensitive to anything remotely occluding part of the face.

I really like the idea of being able to run this code from command line linux and just want to confirm I'm not trolling myself by attempting to achieve the same quality as the app.

- Linux - Ubuntu 17.10
- GCC-6  G++-6
- Python 3.6.3
- Faceswap version: 51f1993d93e0ffb581d44416f327f0cf731c34e8
- Faceswap method: GPU 
- CUDA 9.0 Tensorflow-GPU 1.5
- GTX 1080 8GB

**Comment by deepfakesclub** [comment]
Do you have examples of the problems you mention?

Another user has previously posted a direct comparison here: https://github.com/deepfakes/faceswap-playground/issues/45

**Comment by Clorr** [comment]
FakeApp first version was based on the same code that originated this repo. However both codes have evolved separately. The additions in this repo come from various public sources. The code in FakeApp is not publicly available AFAIK...

**Comment by mike-truk** [comment]
@deepfakesclub -- thanks for referencing the comparison.

Many thanks for confirming, @Clorr.
