### ISSUE TITLE
Pre-Trained model link won't open

### ISSUE THREAD

**Issue by Dorsolomon20** [deepfakes/faceswap-playground#69]
Hey, iv'e traied to open the link to the pre trained model to save time, so i can check the logic for the app, but the link won't open, did any one else have the same issue. If some one know what to do i would love to know, Thank you all.

**Comment by deepfakesclub** [comment]
The link is dead. Someone else who has it will have to upload.

What do you mean by check the logic for the app? If you want to do a test run, just grab any photos and run them through the steps. The results will be a smear if you only train for a short time, but you can tell that the steps are working.
