### ISSUE TITLE
Share your experience!

### ISSUE THREAD

**Issue by Clorr** [deepfakes/faceswap-playground#7]
Please provide feedback so that later coming user can find how you did and what result you obtained

**Comment by Clorr** [comment]
From: https://www.reddit.com/r/deepfakes/comments/7lgwv4/first_fake_complete/

> Can we have the workflow from beginning until the end??

depfakacc

>Pretty boring really, almost all depending on deepfake's code and most recent auto-cropping innovation.
>
>There was only ever one one static data set for the porn star consisting of 4800 sequential frames normalised with the new cropper.
>
>The celebrity face was initially trained with around 1000 frames extracted from youtube videos also run through the cropper, these were relatively low resolution and weren't transferring enough detail or variation after the initial head structure was established (eyes weren't opening fully with no whites visible, nose angles were low detail or overly bulbous, hair was meshed with eyes even late into training).
>
>These were then replaced incrementally to finally contain 277 high resolution publicity and events still photography shots of the celebrity, completely replacing the images sourced from video frames, I didn't include any that had any great deal of variation facing left or right as this wasn't present in the porn video and doesn't maximise the number of pixes of face infomation presented to the network, with the exception of a few cases where side-ish-facing shots contained a novel mouth shape.
>
>I had to hunt for some lower angle images as it was decoding what was basically fleshy noise when it tried to re-encode into the celebrity face a low-angle shot from the porn face (any ability to see the bottom of the nose).
>
>That's about it, I've posted about the alpha blending between image borders just recently.

ruah1984

> how you export back to the video after the training and alignment??

broadfakes

> It's pretty straight forward in ffmpeg.
> `ffmpeg -r 16 -i %d.jpg output.mp4`
> http://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/

**Comment by Ganonmaster** [comment]
NSFW link: https://gfycat.com/RemarkableDeliciousArrowana

Latest version of faceswap, commit no. e0c00bdf74dc77c14a15556fd427b6c2fbd8b773
Somewhere between 24-42 hours of training on GPU. I'm drunk but the result looks pretty good to me so far, and my coworkers (who are just as wasted) agree.

Original face: Phoenix marie
Swapped face: Hillary Clinton

**Comment by Clorr** [comment]
Putting Hillary clinton on a porn, you have to be drunk to do that!!!

**Comment by Clorr** [comment]
#WhatsSeenCantBeUnseen

:-P

**Comment by jiannibang** [comment]
if I want to train new models,should I still use trump and cage models?I'm new to all of this.

**Comment by Ganonmaster** [comment]
@jiannibang that depends! Are you running the training on a CPU or GPU? If you are using a GPU, training will go much faster, and you can attempt to start from scratch. However, if you are on CPU, it is much faster to start from the trump and cage models.

Essentially, the trump/cage model already recognises a face like shape. This is better than starting from no face at all. (from scratch)

**Comment by jiannibang** [comment]
@Ganonmaster  I'm running on GPU.And I intend to start from scratch.But when I used new empty model path,'encoder.h5','decoder_A.h5' and 'decoder_b.h5' seemed to be necessary and I don't know how to generate them.So i pasted them from the original models,Now all the faces look a little trumpish.

**Comment by Ganonmaster** [comment]
As long as the destination directory for your model exists, it should generate the files automatically after a bit of training.

Alternatively, when you are using the trump model, run the training for longer and the "trumpishness" should disappear. Eventually.

**Comment by raksasaa** [comment]
https://www.raymond.cc/blog/extract-video-frames-to-images-using-vlc-media-player/

we could use ffmpeg to convert between video & images

**Comment by Ganonmaster** [comment]
Yes, this is what I've been doing for my tests. I'm pretty sure OpenCV uses FFMpeg under the hood as well, so we could use that.

**Comment by raksasaa** [comment]
pip install tensorflow-gpu  need  cudnn 6.0  && cuda 8.0

DON'T CUDA9.1 & CUDNN 7 RIGHT NOW
