### ISSUE TITLE
GAN convert error

### ISSUE THREAD

**Issue by sharonvar** [deepfakes/faceswap-playground#70]
Unable to convert with GAN training

## Expected behavior
Able to Convert after GAN training

## Actual behavior
I have trained with -t GAN flag 
python3 faceswap.py train -A ~/Desktop/FSdata/Jf3 -B ~/Desktop/FSdata/Lf3 -m ~/Desktop/FSdata/modelGAN/ -t GAN -p -v -w 

but when I try to convert: 
python3 faceswap.py convert -i ~/Desktop/FSdata/Jf2/ -o ~/Desktop/FSdata/output -m ~/Desktop/FSdata/modelGAN/ -t GAN
..
..
File "/Users/NAME/Downloads/fsm/faceswap-master/scripts/convert.py", line 125, in process
    assert model_name.startswith("GAN") is False, "GAN model can only be used with GAN converter!"
AssertionError: GAN model can only be used with GAN converter!

## Other relevant information

- **Operating system and version:** , macOS,  
- **Python version:**  3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU
- ...

**Comment by Ianmcmill** [comment]
Maybe try adding
-c GAN

```
-c {Masked,Adjust,GAN}, --converter {Masked,Adjust,GAN} Converter to use.
```

**Comment by sharonvar** [comment]
I will try with the -c flag.
I 300 each in  A and B
trained 30K epochs 
loss about 0.015 on each

**Comment by sharonvar** [comment]
I did try with -c GAN (just typed it out wrong in my original question)

In my models directory I have the following 
netDA_GAN.h5
netDB_GAN.h5
netGA_GAN.h5
netGB_GAN.h5


it says "assert model_name.startswith("GAN") is True," 
I dont see nay model name that starts with "GAN"

I dont see an encoder.. do I need more training?

**Comment by sharonvar** [comment]
Solved - used both -t GAN and -c GAN - worked..
