### ISSUE TITLE
Merged frames are being produced with extreme distortion // Only happening to a specific model

### ISSUE THREAD

**Issue by deepshakes** [deepfakes/faceswap-playground#72]
## Expected behavior
Merged frames should match preview frames

## Actual behavior
My training data looks fine as you can see [here](https://imgur.com/a/0QhbJ), but when I try to convert the video, it outputs all faces as either a weird blue/green blur thing, or just terrible quality with weird colours over the top of it depending on the settings I use. (Using FakeApp 1.1)

For example, [this](https://imgur.com/a/uRQrP) is what I'm getting when I run it as 'seamless', and [this](https://imgur.com/a/ibBzr) is what I get when I run it as non-seamless with 10 blur and 5 kerning. Clearly my training data isn't anywhere near that bad, so something somewhere is breaking.

## Steps to reproduce

This is only happening to one of my sets. A user on voat downloaded my model + a handful of frames from the target clip, and they were able to reproduce into the same issue. You can check it out yourself [here](http://www33.zippyshare.com/v/kQQNpH50/file.html) if you'd like.

## Other relevant information

- Windows 10 64bit
- Python version: 3.6.4
- Faceswap version: Whatever FakeApp v1.1 uses?
- Faceswap method: GPU

**Comment by Clorr** [comment]
I'm downloading your files right now, but i have a question: Do your source images come from the video you try to convert?

**Comment by deepshakes** [comment]
@Clorr Some did, some didn't. I used a mixture of clips for my sets.

**Comment by Clorr** [comment]
Hmm in the file you sent, there are only a few pictures in `aligned` How many faces did you use for training?

Also note that the reason of that problem is that the generated face is not good, and playing with seamless params won't help. You should just try with the `Adjust` plugin so that you see the output of the model without all the post processing of the `Masked` one

**Comment by deepshakes** [comment]
I used thousands of pictures for my training, I only uploaded a handful of frames in that zip so other people didn't have to download the whole clip to help me test it.

> You should just try with the Adjust plugin so that you see the output of the model without all the post processing of the Masked one

Could you point me in the right direction? I'm not sure what to google

**Comment by deepfakesclub** [comment]
Adjust is an option for the convert script. I think "-c Adjust". See the code or help output.
