### ISSUE TITLE
For people with high-end cards, what is your GPU usage?

### ISSUE THREAD

**Issue by deepfakesclub** [deepfakes/faceswap-playground#73]
On lower end cards like the 1050 or 1060, the GPU usage sits around 95%+ most of the time. I don't own any 1080 cards, but I have tested Tesla processors. Half a K80 (via Google) is pretty good, but a P100 sits at 30-40% usage. Increasing the batch size only marginally decreases the per image computation time for the Tesla GPUs. Perhaps Google's instances aren't zippy enough to support a P100?

Are GTX 1080 users being bottlenecked by non-GPU processes?

A long time ago, Phil Latio over at reddit made a threaded image preloader. His code is pretty straightforward. With all the classes and iterators going on in the current repo, I'm having trouble figuring out if there is any preloading (I don't think so), and implementing it looks a bit more tangled.

I suppose I can test out the old code +/- threading.

However, I'm curious to know if others are running into low GPU usage on the faster cards.

**Comment by Ianmcmill** [comment]
Windows 10
Python 3.6.4
Cuda 9 - cudnn 7.0.4
GTX 980 4GB
Training GAN128 oatssss updateGAN-v2 branch (faceswap fork)
I get around 25-30% GPU usage.
RAM usage 8GB
VRAM usage 3.9GB

On an older GTX 960 I got the roughly the same. Maybe 40% GPU usage.

Would be good to know which repo you are using.

**Comment by Clorr** [comment]
There is the `BackgroundGenerator` that prepares a batch for the next training iteration. Images loading + warping is done separately from training so GPU usage should be maximum as long as your CPU can provide enough data. Some time ago, I did a [small benchmarking utility](https://github.com/deepfakes/faceswap/pull/91) to check how long threads are waiting for each other.

If I remember well, my 1070 GPU was almost always 95% used while my core i5 was more around 50%. With the benchmark above, I was seeing almost no latency in `get` (when GPU is waiting for a new batch), and a bit of latency in `put` (when CPU is waiting for the queue to be emptied by GPU)

**Comment by deepfakesclub** [comment]
@Ianmcmill I'm mostly just using the Feb 14 faceswap commits with the Original Model and a little bit of the dfaker repo.

Google cloud with free credit + preemptible instances is not too bad for pricing. I'm not really training for full videos at the moment. My main goal for now was to benchmark some software and hardware combinations, as I haven't seen any hard numbers. Cloud instances are convenient for that sort of testing.

It looks like from your numbers and mine - neither the CPU nor the GPU maxes out with faceswap in some cases.  dfaker is much more greedy - I can get it to almost max out the CPU and GPU together, so I see bigger improvements with the right hardware.

@Clorr Thanks for the explanation. I imagine a lot of it is system-dependent, but what about the type of scenario in @Ianmcmill's case where both GPU and CPU are sitting idle? Perhaps a single CPU core is the bottleneck?  I couldn't tell with Google Cloud, as I think their virtual CPU cores all go up and down together.

**Comment by Ianmcmill** [comment]
@deepfakesclub didn't know that.
When fakeapp 2.2 around 16GB RAM are used. I can't remember the CPU/GPU usage. Will try when I have time.
