### ISSUE TITLE
[Question] Adjust "square" face result after swap

### ISSUE THREAD

**Issue by vkurguzov1pt** [deepfakes/faceswap-playground#75]
Hello, 
I would like to know if it is somehow possible to adjust "square" face result after swap, because currently it looks like a face of model A cropped as a square and put on face of model B or it is just a result of insufficient training time and source data?

I use python3.5 and CPU (i7) for learning and currently have the following result after 2 days of learning:
loss_A: 0.02240, loss_B: 0.02332
![res_swap](https://user-images.githubusercontent.com/23241262/36892601-4d3b0644-1e16-11e8-9e4e-5dd9540f380a.png)

**Comment by iperov** [comment]
`--converter Masked --seamless --blur-size 0 --erosion-kernel-size 1`

**Comment by vkurguzov1pt** [comment]
Thanks. It gives much more better result
