### ISSUE TITLE
CUDA Compute Capability 2.1 is not supported why?

### ISSUE THREAD

**Issue by gittyhub2018** [deepfakes/faceswap-playground#76]
Why i can not use my GPU ?
I use Myfakeapp GUI and they said i need CUDA Compute Capability Version >= 3.0. Why?

## Expected behavior

I want to try using my GPU with CUDA Compute Capability 2.1 .

## Actual behavior

This is not possible.

## Steps to reproduce

Take a GPU with CUDA Compute Capability Version 2.1 and try to use it.

## Other relevant information

- **OS** Windows 10
- **Python** 3.6.4, ...
- **Faceswap method:** GPU
- **CUDA Compute Capability Version** 2.1
- **Graphic Card:** Nvidia Geforce GTX 560
- **GUI** MyFakeapp from radek's issue

**Comment by i5L4NDOF5T4BiLiTY** [comment]
TensorFlow with GPU support needs CUDA Compute Capability 3.0 or higher.
