### ISSUE TITLE
Can't run extract script

### ISSUE THREAD

**Issue by DrDreGFunk** [deepfakes/faceswap-playground#77]
@Clorr This will be quick but I just need to know what to do...I've read the README and all the installation details.  

in the scripts/extract.py. Which parts do I modify?

try:

                for filename in tqdm(self.read_directory()):
                image = cv2.imread(filename)
                self.faces_detected[os.path.basename(filename)] = self.handleImage(image, filename)
                except Exception as e:
                print('Failed to extract from image: {}. Reason: {}'.format(filename, e))

to

                for filename in tqdm(self.read_directory()):
                image = cv2.imread(filename)
                self.faces_detected[os.path.basename(filename)] = self.handleImage(image, filename)

**Comment by torzdf** [comment]
In scripts/extract.py, starting line 53, there is something called a 'try except block'. This is basically a way of error handling within python. I believe @Clorr wants you to remove it so the program generates a fuller error. Therefore you need to remove the try except block from the code.

The easiest way to explain this would be to remove the 'process' function entirely by deleting rows 42 through 60 and replacing it with the following:
```

    def process(self):
        extractor_name = "Align" # TODO Pass as argument
        self.extractor = PluginLoader.get_extractor(extractor_name)()
        processes = self.arguments.processes
        try:
            if processes != 1:
                files = list(self.read_directory())
                for filename, faces in tqdm(pool_process(self.processFiles, files, processes=processes), total = len(files)):
                    self.num_faces_detected += 1
                    self.faces_detected[os.path.basename(filename)] = faces
            else:
                for filename in tqdm(self.read_directory()):
                    image = cv2.imread(filename)
                    self.faces_detected[os.path.basename(filename)] = self.handleImage(image, filename)
        finally:
            self.write_alignments()
```

NB: The indentation is very important, so you should paste it as is.

**Comment by Clorr** [comment]
Seems fine. What results does it gives you?

**Comment by DrDreGFunk** [comment]
Ok, I think I've managed to do that. This is the error I got from it:

------------------------------------------------------------------------------------------------------
MY NAME-MacBook-Pro-2:faceswap MY NAME$  python faceswap.py convert -i video -o output -m model

Traceback (most recent call last):

  File "faceswap.py", line 4, in <module>

    from scripts.extract import ExtractTrainingData

  File "/Volumes/MyPassport/DeepFakes/faceswap/scripts/extract.py", line 9, in <module>

    from lib.multithreading import pool_process

ImportError: No module named 'lib.multithreading'

**Comment by Clorr** [comment]
It means it can't find the file named `multithreading` located in the `lib` folder. Are you sure you have all files installed?

**Comment by DrDreGFunk** [comment]
Yh I should have. I followed a tutorial that was for mac and followed every single instruction...

I just realized I had a folder called "faceswap-master". which includes the multithreading file in there. I'll drag and drop that in my current faceswap folder and see if that works.

**Comment by DrDreGFunk** [comment]
Nope it stills gives me the object is not iterable error and doesn't detect the 930 faces.

**Comment by Clorr** [comment]
The object is not iterable has many causes, so if you can't give more precise feedback i won't be able to help you much...

**Comment by DrDreGFunk** [comment]
Is there another way to find out the cause, like last time?

**Comment by torzdf** [comment]
It sounds like it's not installed correctly. Can you provide a screengrab of your faceswap folder structure and also your faceswap_master folder structure.

Also, have you got a link for the mac guide you followed?

**Comment by DrDreGFunk** [comment]
Sure... 

Here's the faceswap stucture

 
<img width="1199" alt="faceswap structure" src="https://user-images.githubusercontent.com/36054512/36935042-02e9d21c-1eea-11e8-9dd5-b10a8ae8561e.png">

Here's the faceswap-master structure


<img width="1197" alt="faceswap-master structure" src="https://user-images.githubusercontent.com/36054512/36935062-3120d93c-1eea-11e8-9cc3-e36de03897f0.png">


And here's the link to the tutorial I followed. It's the only tutorial I found for mac and just so you know, I'm not using this for porn. I'm trying to create a funny video with Dwayne Johnson.

https://medium.com/@oliverlardner/tutorial-for-mac-deepfakes-reddit-mirror-d75eb8069a16

**Comment by torzdf** [comment]
Ok. For some reason it looks like you have a faceswap folder which has an older version of the app (the requirements files are from an older version). The faceswap-master folder looks to be a more recent version.

You can do one of 2 things. Scrub the entire folder and try and reinstall again. 

Alternatively, move your working images into the faceswap-master folder and try running faceswap.py from there.

**Comment by DrDreGFunk** [comment]
YOU SIR, ARE A BLOODY GENIUS!
IT ACTUALLY WORKED

HOWEVER...

It comes up with an error message:

Reading alignments from: /Volumes/MyPassport/DeepFakes/faceswap-master/video/alignments.json
/Volumes/MyPassport/DeepFakes/faceswap-master/video/alignments.json not read!
[Errno 2] No such file or directory: '/Volumes/MyPassport/DeepFakes/faceswap-master/video/alignments.json'
 11%|████▍                                    | 100/930 [02:45<22:55,  1.66s/it]

What do "alignments.json not read" mean? The images come up in the output folder but the faces are not aligned properly and look like something out of a Tim Burton horror movie haha.

**Comment by torzdf** [comment]
Ok, you'll need to re-run extract. The older version did not generate an alignments.json file, but the new one does and it is required. You won't need to train your model again though.
