### ISSUE TITLE
convert.py script failing: Reason: basic_filebuf::underflow error reading the file: iostream error

### ISSUE THREAD

**Issue by Yutsa** [deepfakes/faceswap-playground#8]
Hello guys,

I'm trying to run the `convert.py` script and I'm not 100% sure on how it works. I did the following steps 👍 

* Gatherd pictures from two person.

* Extracted their faces

* Trained the model using the `train.py` script

* Executed the following `python convert.py -i ~/Téléchargements/faceswap-data/source-images/lawrence/ -o ~/Téléchargements/faceswap-data/result/`

The input directory I used contained full picture (not cropped) of person A. Is it how I should use it ?

I got the following error : 

`Failed to extract from image: /home/edouard/Téléchargements/faceswap-data/source-images/lawrence/109.jpg. Reason: basic_filebuf::underflow error reading the file: iostream error`

**Comment by Ganonmaster** [comment]
The steps are as follows:

- gather pictures of the people you want to swap
-  `extract.py` Extract training data
    - outputs: cropped faces that we will use to train the model
    - You need to run this on the faces of both your image sets: Face_A and Face_B (example: trump and nic cage)
    - You also need to double check that the cropped images that it generates are actually usable as training data. Preferably high quality, no glasses or obscuring features, and no incorrectly detected faces.
- `train.py` Train the model
    - inputs: directory containing cropped faces of face_A, directory containing cropped faces of face_B, trained model directory
    - outputs: a trained model
-  `convert.py` Convert a series of pictures
    - inputs: unprocessed images, the output directory, the directory of the trained model
    - outputs: converted images

General note: the directories you enter into the command line script have to exist. Otherwise, it will not generate any images. The script can be improved to automatically create the directories if they don't exist.

You say you have issues with the `extract.py` script, but say you've already gone through a bunch of later steps, which doesn't really make sense. Be sure to check the resulting data of each step before moving on to the next.

**Comment by Yutsa** [comment]
Yeah sorry I mixed up `convert` and `extract` my bad

**Comment by Ganonmaster** [comment]
Yes. You can use the `-h` flag to see which ones.

**Comment by Yutsa** [comment]
Actually I get the following help message for `convert.py`

```
optional arguments:
  -h, --help            show this help message and exit
  -i INPUT_DIR, --input-dir INPUT_DIR
                        Input directory. A directory containing the files you
                        wish to process. Defaults to 'input'
  -o OUTPUT_DIR, --output-dir OUTPUT_DIR
                        Output directory. This is where the converted files
                        will be stored. Defaults to 'output'
  -v, --verbose         Show verbose output
  -m MODEL_DIR, --model-dir MODEL_DIR
                        Model directory. A directory containing the trained
                        model you wish to process. Defaults to 'models'

Questions and feedback: https://github.com/deepfakes/faceswap-playground
```

How should I pass the directories ? I tried comma and space separated but it didn't work.

**Comment by Ganonmaster** [comment]
Like any regular command. Example:

`convert.py -i /path/to/input/ -o /path/to/output/ -m /path/to/model/`

For verbose output:
`convert.py -i /path/to/input/ -o /path/to/output/ -m /path/to/model/ -v`

**Comment by Yutsa** [comment]
Oh right I misunderstood what you said earlier then. I actually did what you said :

`python convert.py -i ~/Téléchargements/faceswap-data/source-images/lawrence/ -o ~/Test/ -m models/`

and I get `Failed to extract from image: /home/edouard/Téléchargements/faceswap-data/source-images/lawrence/115.jpg. Reason: basic_filebuf::underflow error reading the file: iostream error`

**Comment by Ganonmaster** [comment]
Could you post that image?

**Comment by Yutsa** [comment]
It does that with every picture. I took one of the picture from which I extracted the face. So it's the original picture in full.

![115](https://user-images.githubusercontent.com/11539831/34326960-da5ee984-e8b8-11e7-9d45-b155b837ccb1.jpg)

It was this one exactly.

Sorry if I'm making a obvious mistake

**Comment by Yutsa** [comment]
I keep on having this `basic_filebuf::underflow error reading the file: iostream error` with this script.

Not sure what causes this. I tried using differents pictures from the internet but nothing changed.

**Comment by Ganonmaster** [comment]
Does the output directory exist? Like, did you specify a directory as your output directory, and make sure that the intermediate folders exist?

**Comment by Yutsa** [comment]
Yes, it actually managed to create two files out of fifty

**Comment by Ganonmaster** [comment]
Where did you obtain these files; could you try converting them to a different format and see if it will process them?

**Comment by Yutsa** [comment]
I pulled the latest commits and I don't have the bug anymore. That's weird, I don't know what caused this.

I'm closing this for now then.
