### ISSUE TITLE
FYI. Posting a number of benchmarks

### ISSUE THREAD

**Issue by deepfakesclub** [deepfakes/faceswap-playground#81]
I posted a lot of benchmarks over here.
https://www.deepfakes.club/best-hardware-software-deepfakes/

TLDR; relevant to faceswap
faceswap is 50-75% faster than FakeApp.
But I can't seem to max out the GPU usage on a P100 with 8 vCPUs. <== my main question/concern, how to max out
faceswap OriginalModel compared to dfaker 128x128 output model, no surprises, dfaker quality is higher
Latest Keras CNN commit is slow, good detector though.

**Comment by Apollo122** [comment]
Wow such a detailed report. Thanks.

Im glad to hear that latest keras port finds more faces. I don't care how long it takes or false-positive it gives. We can be patient and delete the false-positives now that we have alignment file support.

**Comment by iperov** [comment]
@deepfakesclub
recheck stability test. No more zooming problems due to keras face-alignment.

**Comment by deepfakesclub** [comment]
@iperov, oh yeah, I didn't show the stability test, because I just assumed it worked!

**Comment by Ianmcmill** [comment]
Regarding GPU usage:

Latest versions (https://github.com/deepfakes/faceswap/commit/0ea743029db0d47f09d33ef90f50ad84c20b085f) take full GPU.

```
$ nvidia-smi
Sat Mar 10 20:22:14 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.25                 Driver Version: 390.25                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:01:00.0  On |                  N/A |
| 69%   73C    P2   153W / 196W |   3945MiB /  4042MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1360      G   /usr/lib/xorg/Xorg                           166MiB |
|    0      2744      G   compiz                                       145MiB |
|    0     22928      C   python3                                     3608MiB |
+-----------------------------------------------------------------------------+
```


Python 3.5
Tensorflow-GPU 1.4.0 7 1.6.0
Cuda 8 / Cuda 9
Cudnn 7.0.5

**Comment by deepfakesclub** [comment]
@Ianmcmill I haven't tested the latest version yet, but that's good to hear you get 100% GPU. That was really bugging me that I couldn't maximize the GPU... now I have a good excuse to buy a better graphics card, ha.
