### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'input_A'

### ISSUE THREAD

**Issue by sd12832** [deepfakes/faceswap-playground#84]
Trying to understand how to use this program right now. 

Firstly, after quite a few installation and dependency hurdles, I managed to invoke `python faceswap.py extract` on my input folder. As expected facial recognition happened and I got a bunch of faces in the `/output` folder. Now I invoke `python faceswap.py train`, but I get the error below: 

```
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Model A Directory: input_A
Model B Directory: input_B
Training data directory: models
Loading data, this may take a while...
Loading Model from Model_Original plugin...
Failed loading existing training data.
Unable to open file (unable to open file: name = 'models/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sharanduggirala/Documents/fswap/faceswap/scripts/train.py", line 140, in processThread
    images_A = get_image_paths(self.arguments.input_A)
  File "/Users/sharanduggirala/Documents/fswap/faceswap/lib/utils.py", line 15, in get_image_paths
    return [x.path for x in scandir(directory) if
FileNotFoundError: [Errno 2] No such file or directory: 'input_A'

```

After this appears, the program just hangs unless I press `Cntrl+C` or `Enter`. I am not sure as to where this error is coming from. Why aren't my models being created? 

I am currently working on a **mac**, and running **Python3.6**.

**Comment by MT-4ier** [comment]
It looks like you need to create "input_A" and "input_B" directories, and put images in them. I think those are the default directory names for those.
With a command line or terminal, you can specify folder locations for inputs and outputs as well as the model directory. To see the available options, you just enter
``python faceswap.py train -h``

**Comment by sd12832** [comment]
Yeah, this definitely does the trick. So I don't understand why the playgrounds README was talking about Trump and Nick Cage?

**Comment by MT-4ier** [comment]
That was just an example of what's possible with this program, and the provided model is already trained on the images in the full download, so you wouldn't have to spend time training for yourself to see it.
I'm glad I could help. :)

**Comment by sd12832** [comment]
Before you go, you could probably help me on this. Is INPUT_A is the set of faces that will be transposed upon the set of faces in B?

**Comment by MT-4ier** [comment]
It can be done in either direction, but by default I think it puts Face B onto Body A.
To see the options for merging, use
`python faceswap.py convert -h`
