### ISSUE TITLE
Train with faceset from image search engines. 

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#85]
(sry bad english)

I tried to train model with various detailed faces of one celeb ~650 photos which I got from search engines.
Aligned SFW: [AlexandraDaddario.zip](https://github.com/deepfakes/faceswap-playground/files/1780092/AlexandraDaddario.zip)

Also tried to train same celeb but images I took from every frame of video.

Conclusion: after N epochs predict from video model looks much sharper than same N epochs photo model.
Also photo model produces some glitches on final video, such as changing color of pomade depends of face angle, and shit morphing effect from angle to angle.

So is this NN limit to remember all faces with too different conditions? Therefore better train only faces that will match destination video.

**Comment by modelsex** [comment]
How about Aligned SFW_video, also use 650 photos for compare? But I think it is meaningless compare <Aligned SFW_photo> & <Aligned SFW_video>, so much different betweent these 2 photosets, like angle, exposuro, clarity, etc. 
Photos like <00012>, <00099>, <00151> are overexposed;
Photos like <00020>, <00072>, <00181> are too dark;
Photos like <00008 --> 00011>, <00050>, <00082>, these are same angle & almost same expression(not big different in landmarks), so there are no enough faces sample to supply, obviours less than 650 number.
As my experince, <Aligned SFW_video> will more efficient get rid of these metioned problems. My <Aligned SFW_video> number always more than 2000 to give enough quality.
