### ISSUE TITLE
Portable Winpython versions

### ISSUE THREAD

**Issue by deepfakesclub** [deepfakes/faceswap-playground#86]
I'm finding that WinPython is the simplest way to share no-install setups, easier than embeddable zip or pyinstaller, etc. WinPython handles all the custom paths for you. These are really easy to setup.

I put together portable python installs of faceswap and dfaker (the 128x128 output repo). That means you just unzip and run the python programs without any installation, compiling dlib, or other annoying things.

https://mega.nz/#!Wcg2mRDC!WnsW2emBHjRry6FkAq7UZjP6VEv_AT5sUfnJIisRtY8

The good thing about WinPython is you can do whatever you want, clone your own repo in. Replicating this is fairly straightforward, but the two possibly tricky parts are compiling dlib with GPU support and installing pytorch (for dfaker).

I tested the basic functions (extract, train, convert with default options), but let me know if something is not working.

Requires CUDA 9, cuDNN 7, VC Redistributable 2015 to be pre-installed, like everything else. Win10, Intel, NVIDIA, you know the drill.

To use:

Unzip the file.

The base directory is pythondf. From here, double click WinPython Command Prompt.exe

Navigate to the directory of the flavor you want to run (within python-3.6.3.amd64). Then, follow the respective github usage notes.

The three included flavors are:

faceswap – Exact copy of most recent faceswap

faceswap_lowmem – The LowMem setting in faceswap doesn’t actually work on 2GB cards. Plus, the new GPU-based face extractor doesn’t work on 2GB cards. For this flavor, I changed these so everything should work on 2GB cards with a batch size of 16 or smaller. (Using Feb 14 commit for GPU face extraction and a different Model_LowMem.py)

dfaker – Exact copy of dfaker with one change. I activated the GPU-based face extractor by commenting one line. You will have to manually change the code if you want to adjust batch size or directory names.

**Comment by deepfakesclub** [comment]
If you want to set it up yourself (for example, I copy my portable install to cloud instances, which speeds up creating new instances), here is a basic guide.

This is from WinPython Zero (minimal install version).
Install WinPython Zero
pip install pathlib==1.0.1
pip install scandir==1.6
pip install h5py==2.7.1
pip install Keras==2.1.2
pip install opencv-python==3.3.0.10
pip install tensorflow-gpu==1.5.0
pip install scikit-image

[Slightly tricky part. Install Visual Studio 2015, including C++ tools and SDK, Install CMake, Install boost binaries]
git clone https://github.com/davisking/dlib
cd dlib
python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

pip install face_recognition (not required for most recent commit, just leaving here for posterity)
pip install tqdm

git clone https://github.com/dfaker/df
cd df
git clone https://github.com/keras-team/keras-contrib.git
cd keras-contrib
python setup.py install
cd ..

[Slightly tricky part]
pytorch wasn't installing cleanly with the WinPython Zero, so I created a conda install of pytorch as explained here: https://github.com/peterjc123/pytorch-scripts
Copy the pytorch folders from the conda environment's site-packages to your WinPython site-package folder.

git clone https://github.com/1adrianb/face-alignment.git
cd face-alignment
python setup.py install

You now have your own portable python install.

**Comment by iperov** [comment]
why need face-alignment ?

**Comment by deepfakesclub** [comment]
@iperov, That's for the dfaker build. I didn't change any of his code. Different repo. (https://github.com/dfaker/df)

Includes faceswap, faceswap_lowmem (custom), and dfaker.

**Comment by iperov** [comment]
@deepfakesclub do you know where is faceset db now after subreddit ban ?

**Comment by Clorr** [comment]
@iperov in cas this helps, there is a mirror of reddit here : https://archive.is/x82Za
I did not find all the pages I wanted but it helped somehow...

**Comment by deepfakesclub** [comment]
@iperov Sorry, I don't know. I usually download videos on my own, since you get many frames easily, and the quality is better (like you pointed out in the other issue). There are some sketchier forums around that may have facesets, but I don't really visit them so I don't know if they are active or not.

**Comment by iperov** [comment]
i just want contribute Daddario faceset 2098 photos to somewhere :)
