### ISSUE TITLE
What exactly does the 'layers' option do?

### ISSUE THREAD

**Issue by deepshakes** [deepfakes/faceswap-playground#87]
I had a quick scan through the code to see if I could find anything describing 'layers' but didn't have much luck, so I figured I'd ask here.

In FakeApp (at least in 1.1) the training tab has a 'layers' option which defaults to 4. I've been bumping it up to 8, but I have no idea what the option actually does? Does this setting affect the quality of the model at all, or just the processing speed?

**Comment by Clorr** [comment]
Layers are what define the model so it has an impact on both quality and speed/memory. However we don't know which code FakeApp does use so I can't give you more info on that... My guess is that [these hardcoded layers](https://github.com/deepfakes/faceswap/blob/120535eb11b6d606d5c72d80c88c890aeff9eee2/plugins/Model_Original.py#L48) are generated on the fly
