### ISSUE TITLE
We can work on Intel HD Graphics while fakes computing on gtx

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#89]
Just enable HD graphics in bios, install drivers, and now we can work in browser, watching videos etc without any graphics freezes.

2 cables required to be connected to monitor, one from motherboard, one from videocard.

switching cards only through screen resolution panel.
![explorer_2018-03-07_12-38-33](https://user-images.githubusercontent.com/8076202/37082003-b90444d4-2204-11e8-8c25-3bba0779cf6b.png)
monitor will automatically detect video input after switch videocard.

Also I installed coolerless GT 730 card, all works fine. 
Keras automatically chooses best card.

![2018-03-07_12-37-58](https://user-images.githubusercontent.com/8076202/37081980-a47e72b4-2204-11e8-9aa3-af9b767c714e.png)

@deepfakesclub can you add this info to FAQ on ur site?

**Comment by deepfakesclub** [comment]
Lol, okay, if you want to keep the unwashed masses away.
