### ISSUE TITLE
balance loss comparison 

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap-playground#92]
trained models with and without balance loss

10k epochs vs 19k epochs (because balance loss model training only one model in epoch),
both took same time ~2.5h

without balance loss 0.34:
![2018-03-10_17-45-17](https://user-images.githubusercontent.com/8076202/37242969-2d734d0a-248b-11e8-9faa-2742da8b3cd8.png)

with balance loss 0.31:
![2018-03-10_17-45-24](https://user-images.githubusercontent.com/8076202/37242970-2f91b838-248b-11e8-9381-08b3a7efb572.png)

**Comment by FallyFakey** [comment]
Hey!

I'm a big fan of this function, is there a way to use it with the original Model? Or is there another possibility to only train the B encoder with the original Model?

**Comment by iperov** [comment]
i dont know. Need more tests.
