### ISSUE TITLE
Can not get GPU used in extraction or converting!

### ISSUE THREAD

**Issue by frosty3907** [deepfakes/faceswap-playground#93]
I have installed so much stuff over the past few days trying to get the Extract/Convert to use my 1080ti but I just can't get it working. Is there a detailed step by step of the requirements somewhere because all the ones I've used seem to be missing several things that you need that I had to work out on my own.

at the moment i'm cloning the git dlib repo then running 
cmake -G "Visual Studio 15 2017 Win64" -T host=x64 .. 
and then 
cmake .. -DUSE_AVX_INSTRUCTIONS=1
and then
cmake --build . --config Release

which is saying Build succeeded but whenever I run 
python faceswap.py extract -i D:/faceswap/data_A -o D:/faceswap/data_A/aligned

it is incredibly slow and just using the CPU :(

If I run cmake-gui I can see dlib use CUDA is OFF.

If I try and run: cmake -G "Visual Studio 14 2015 Win64"

CMake Error in CMakeLists.txt:
  Failed to run MSBuild command:
    MSBuild.exe
  to get the value of VCTargetsPath:
    The system cannot find the file specified
-- Configuring incomplete, errors occurred!
See also "D:/faceswap/dlib/CMakeFiles/CMakeOutput.log".

output.log just says:
The system is: Windows - 10.0.16299 - AMD64 

I think perhaps I've installed the wrong Visual Studio or something but I have no idea then which would be the 'right' one?

**Comment by torzdf** [comment]
Do you have CUDA and  cuDNN  installed? These are requirements for building dlib with GPU support.

When you run the initial cmake command the output should tell you whether it will be building with CUDA or not.

**Comment by torzdf** [comment]
Also, it may be worth looking into using Ubuntu on Windows.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

as documentation and for building on a linux system tends to be more thorough.

**Comment by deepfakesclub** [comment]
What worked for me:
VS 2015 (include SDK and C++ options)
boost 1.66 precompiled binaries = easy (not 1.65, it is buggy unless you build yourself = hard)
cmake
CUDA 8/cuDNN 6 OR CUDA 9/cuDNN 7
python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

There are a couple prebuilt CUDA 8/9 ones floating around here too.

**Comment by bryanlyon** [comment]
GPU acceleration on extract is minimal (except for when you use CNN).  The extract needs a refactor to improve the flow and enable better acceleration.

Conversion should use much more GPU, but still has other bottlenecks (loading/patching/saving the original image).

Unfortunately optimizations were not a major part of the current design and it will take some serious efforts to optimize and improve things.

**Comment by frosty3907** [comment]
Thanks for all the suggestions I'll try them today.
@bryanlyon it is taking almost a second per frame for default and nearly a minute for CNN - that can't be right?

**Comment by frosty3907** [comment]
Pip install dlib --install-option="--yes USE_AVX_INSTRUCTIONS" --install-option="--yes DLIB_USE_CUDA" yields:

Command "c:\users\XXX\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='S:\\temp\\SYStemp\\pip-build-yifej_et\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record S:\temp\SYStemp\pip-048dbn9v-record\install-record.txt --single-version-externally-managed --compile "--yes USE_AVX_INSTRUCTIONS" "--yes DLIB_USE_CUDA"" failed with error code 1 in S:\temp\SYStemp\pip-build-yifej_et\dlib\

none of those folders listed on the S: are present...

**Comment by frosty3907** [comment]
Could someone confirm for me the approximate speed/GPU usage they get using Extract?
with a 2600k @ 4.8GHz and 1080ti w 11GB VRAM and 16GB system RAM I'm getting an extraction rate of about 2 images per second using default extract parameters. and 0% GPU usage.

**Comment by bryanlyon** [comment]
That doesn't sound like a bad speed if on CNN.  hog may be faster, but usually requires more threads to keep it going any better anyway.  Actually, what GPU you have is far less important for extract since it's not optimized very much yet.  Any GPU will be about the same.

**Comment by frosty3907** [comment]
No that's with the default extract, if I tell it to use CNN it takes like.. a minute per frame.

**Comment by frosty3907** [comment]
When I was using the prebuilt fakeapp extraction was maybe 50x quicker.

**Comment by bryanlyon** [comment]
Give me the log info it shows while running.  I'll see what I can figure out.

**Comment by frosty3907** [comment]
D:\faceswap>python faceswap.py extract -i D:/faceswap/data_A -o D:/faceswap/data_A/aligned
C:\Users\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Input Directory: D:\faceswap\data_A
Output Directory: D:\faceswap\data_A\aligned
Filter: filter.jpg
Using json serializer
Starting, this may take a while...
Loading Extract from Extract_Align plugin...
  0%|                                                                                        | 0/27552 [00:00<?, ?it/s]Info: initializing keras model...
2018-03-13 12:40:58.167920: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
2018-03-13 12:40:58.469893: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 9.10GiB
2018-03-13 12:40:58.475086: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From C:\Users\XXXX\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\backend\tensorflow_backend.py:1349: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
  0%|▎                                                                            | 99/27552 [00:57<4:25:19,  1.72it/s]Alignments filepath: D:\faceswap\data_A\alignments.json

**Comment by frosty3907** [comment]
if I run python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA in /dlib it seems to run but gives 3 warnings: "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\ALL_BUILD.vcxproj" (default target) (1) ->
       "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_python.vcxproj" (default target) (4) ->
       (ClCompile target) ->
         d:\faceswap\dlib\tools\python\src\basic.cpp(22): warning C4101: 'e': unreferenced local variable [D:\faceswap\dlib\build\temp.win
       -amd64-3.6\Release\dlib_python.vcxproj]
         d:\faceswap\dlib\tools\python\src\vector.cpp(61): warning C4101: 'e': unreferenced local variable [D:\faceswap\dlib\build\temp.wi
       n-amd64-3.6\Release\dlib_python.vcxproj]
         d:\faceswap\dlib\tools\python\src\svm_struct.cpp(59): warning C4101: 'e': unreferenced local variable [D:\faceswap\dlib\build\tem
       p.win-amd64-3.6\Release\dlib_python.vcxproj]

**Comment by kvrooman** [comment]
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX

this will be fixed if you upgrade to tensorflow 1.6 as the new default build compiles with AVX. Will speed up CPU calcs.

**Comment by frosty3907** [comment]
Yep I've tried tensorflow 1.6 previously also, but really need to get CUDA working first.

**Comment by kvrooman** [comment]
Try uninstalling all dlibs ( pip uninstall ) , manually deleting the dlib folders and any temp stuff,wheels, or eggs out of the C:\Users\####\AppData\Local\Programs\Python\Python36\Lib\site-packages\ folder.

Then re-download from dlib, and try this command

run python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA --clean
from.... https://github.com/davisking/dlib/issues/1082

Post the entire dlib install log here... you should be looking for a 
Found CUDA: E:/CUDA 9.0 (found suitable version "9.0", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: E:/CUDA 9.0/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...

or some such stuff.. It will also tell you if it will or will not use CUDA.

**Comment by frosty3907** [comment]
[log (2).txt](https://github.com/deepfakes/faceswap-playground/files/1805340/log.2.txt)

log attached, relevant portion would seem to be:
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***   Change Dir: D:/faceswap/dlib/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build
   ***
   ***   Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe" "ALL_BUILD.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0"
   ***   Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
   ***   Copyright (C) Microsoft Corporation. All rights reserved.
   ***
   ***   Build started 13/03/2018 2:13:57 PM.
   ***   Project "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ALL_BUILD.vcxproj" on node 1 (default targets).
   ***   Project "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ALL_BUILD.vcxproj" (1) is building "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
   ***   PrepareForBuild:
   ***     Creating directory "x64\Debug\ZERO_CHECK\".
   ***     Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
   ***   InitializeBuildStatus:
   ***     Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
   ***   CustomBuild:
   ***     Checking Build System
   ***     CMake does not need to re-run because D:/faceswap/dlib/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build/CMakeFiles/generate.stamp is up-to-date.
   ***   FinalizeBuildStatus:
   ***     Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
   ***     Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
   ***   Done Building Project "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ZERO_CHECK.vcxproj" (default targets).
   ***   Project "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ALL_BUILD.vcxproj" (1) is building "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj" (3) on node 1 (default targets).
   ***   PrepareForBuild:
   ***     Creating directory "cuda_test.dir\Debug\".
   ***     Creating directory "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\Debug\".
   ***     Creating directory "cuda_test.dir\Debug\cuda_test.tlog\".
   ***   InitializeBuildStatus:
   ***     Creating "cuda_test.dir\Debug\cuda_test.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
   ***   ComputeCustomBuildOutput:
   ***     Creating directory "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\CMakeFiles\cuda_test.dir\Debug\".
   ***   CustomBuild:
   ***     Building NVCC (Device) object CMakeFiles/cuda_test.dir/Debug/cuda_test_generated_cuda_test.cu.obj
   ***     CMake Error at cuda_test_generated_cuda_test.cu.obj.Debug.cmake:215 (message):
   ***       Error generating
   ***       D:/faceswap/dlib/build/temp.win-amd64-3.6/Release/dlib_build/cuda_test_build/CMakeFiles/cuda_test.dir//Debug/cuda_test_generated_cuda_test.cu.obj
   ***
   ***
   ***   C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]
   ***   Done Building Project "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj" (default targets) -- FAILED.
   ***   Done Building Project "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
   ***
   ***   Build FAILED.
   ***
   ***   "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\ALL_BUILD.vcxproj" (default target) (1) ->
   ***   "D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj" (default target) (3) ->
   ***   (CustomBuild target) ->
   ***     C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]
   ***
   ***       0 Warning(s)
   ***       1 Error(s)
   ***
   ***   Time Elapsed 00:00:01.09
   ***
-- *****************************************************************************************************************
-- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA

**Comment by frosty3907** [comment]
I wonder if https://github.com/davisking/dlib/issues/1035 or https://devtalk.nvidia.com/default/topic/1027299/cuda-setup-and-installation/cuda-9-failed-to-support-the-latest-visual-studio-2017-version-15-5/2 are relevant?

**Comment by bryanlyon** [comment]
How many visual studios do you have in your add/remove programs?  I think
you have a problem with too many of them.

**Comment by frosty3907** [comment]
i've installed 2017 and 2015.3 but have been having the issue since the initial install of 2017 build tools.

My next step will be to remove them all and start again though.

**Comment by bryanlyon** [comment]
Yeah, try with just the build tools.

**Comment by frosty3907** [comment]
So with build tools I remember there being many choices to select, which are required? I'm reading somewhere else that "VC++ 2015.3 v140 toolset for desktop (x86/x64)" might be the missing link.

**Comment by bryanlyon** [comment]
No, just the build tools with the 2 default checkboxes.

**Comment by frosty3907** [comment]
Ok downloading (again) now (6Gb...) - will I need to tell Cmake to change the compiler it's using after this?

**Comment by bryanlyon** [comment]
No.  It shouldn't be 6gb, it should just be about 2gb for the build tools.

**Comment by frosty3907** [comment]
Nope, same error.

Uninstalled VS 2017 and 2015.3

reinstalled 2017 Build Tools with default two selections.

dlib install still giving cuda errors.

I'm not sure if it was actually 6gb but that's what the installer said.. might've been space required.

**Comment by frosty3907** [comment]
also if I try:
Pip install dlib --install-option="--yes USE_AVX_INSTRUCTIONS" --install-option="--yes DLIB_USE_CUDA"

I get:
error: option --yes USE_AVX_INSTRUCTIONS not recognized

    ----------------------------------------
Command "c:\users\craig\envs\faceswap\scripts\python.exe -u -c "import setuptools, tokenize;__file__='S:\\temp\\SYStemp\\pip-build-oxr7iwri\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record S:\temp\SYStemp\pip-rau21qzm-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\craig\envs\faceswap\include\site\python3.6\dlib "--yes USE_AVX_INSTRUCTIONS" "--yes DLIB_USE_CUDA"" failed with error code 1 in S:\temp\SYStemp\pip-build-oxr7iwri\dlib\

**Comment by deepfakesclub** [comment]
Back above,you had an error on the test CUDA compilation with CUDA 9.0:

Make sure you install the latest NVIDIA driver for your graphics card, released Jan or Feb 2018. I have no idea if this affects the build/compilation, but you will definitely get errors later if you do not do this.

Everything else looked good then, except you failed the CUDA test build... so it sounds like something was wrong with your CUDA setup and I can't think of anything else except old drivers. CUDA 9 is only supported on the most recent drivers.

For extraction speeds, I recorded some here: https://www.deepfakes.club/best-hardware-software-deepfakes/#Face_extraction_speed

**Comment by frosty3907** [comment]
I tried updating to latest video driver, no dice, tried reinstalling cuda 9 (gives warning about no supported version of Visual Studio, that's OK I assume) and it just says Installer Failed :/

**Comment by deepfakesclub** [comment]
The issue you cited above pretty much implies you should use VS2015, not VS2017... just noticed. Can't think of anything else.

You can ignore the VS error with CUDA - although if you installed VS, you shouldn't get that error, making it sound like something else may be wrong.

**Comment by frosty3907** [comment]
I didn't install VS2017 this time, just the build tools.. guess i'll remove those and try 2015 again.

**Comment by frosty3907** [comment]
OH my god I think it's working! Uninstalled VS2017/15/build tools etc.

Downloaded VS2015.3 BUILD TOOLS (was down the bottom of the download page) custom install to include win10 SDK.

I think where I was going wrong was someone said to install Visual Studio 2015 (not specifically build tools).

Testing further now.

**Comment by frosty3907** [comment]
Upgraded to tensorflow 1.6 and it's even slower now (maybe a quarter of the previous speed) but pegging CPU at 100% ! Argh!

**Comment by kvrooman** [comment]
Congrats! ? 
How many frames a sec do you process when extracting with -D cnn and -D hog?

depending on your current branch of faceswap and hardware and frames in the input directory, I could expect somewhere between 2 it/s and 5 it/s.

**Comment by frosty3907** [comment]
1.5 with hog. CNN shows something ridiculous like 65 it/s but it takes almost a minute per frame.

**Comment by deepfakesclub** [comment]
Did your build go through correctly with 0 errors? Also double-check it says "65 sec/iter" and not "65 iter/sec". tqdm will swap the sec/iter and iter/sec to keep the number above 1.

The CNN detector should not be that slow with a 1080ti.

If you verified your dlib build is correct, it still sounds like something is wrong if it takes a minute per frame.

Make sure you uninstall other python versions so you don't inadvertently load the wrong dlib module. Saw your other issue on nuking python, haha.

**Comment by frosty3907** [comment]
0 errors but a ton of warnings (had the word VOID in it a lot from memory).
It's currently halfway through an extraction (3 hours) so I'm waiting for that to finish before going nuclear.

**Comment by kvrooman** [comment]
Sorry, its been such an issue for you.
Hey.. just to be sure on the VS stuff. From the following page, I downloaded the 4 things below
https://my.visualstudio.com/Downloads?q=visual%20studio%202015&wt.mc_id=o~msft~vscom~older-downloads
Visual Studio Community 2015 with Update 3
Visual C++ Redistributable for Visual Studio 2015
Visual C++ Redistributable for Visual Studio 2015 Update 1
Visual Studio 2015 SDK

Then I have python 3.6.3, cudnn 7.05, cuda 9.0, as dependencies.

**Comment by MT-4ier** [comment]
After reading that it SHOULDN'T take a minute per frame with CNN extract, I tried compiling dlib instead of using the wheel I had downloaded. Now instead of 70 sec/it, I get 1 sec/it on my GTX 960. :D

**Comment by frosty3907** [comment]
Using @deepfakesclub prepackaged winpython from here: https://github.com/deepfakes/faceswap-playground/issues/86 increases my extraction speed 100x - so does this mean my issue is related to my winpython install?

**Comment by bryanlyon** [comment]
No, it was visual studio.  Since he included a compiled binary if dkib with
support for your Cuda already, it's working.

On Mar 14, 2018 19:18, "frosty3907" <notifications@github.com> wrote:

Using @deepfakesclub <https://github.com/deepfakesclub> prepackaged
winpython from here: #86
<https://github.com/deepfakes/faceswap-playground/issues/86> increases my
extraction speed 100x - so does this mean my issue is related to my
winpython install?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/deepfakes/faceswap-playground/issues/93#issuecomment-373238236>,
or mute the thread

**Comment by frosty3907** [comment]
I don't get why my visual studio install is so hosed... so I should be able to use the compiled dlib from the package with my other installs?

**Comment by deepfakesclub** [comment]
Yay, at least you can play around. Because it's a full install, you can all pull the latest repo updates and do whatever you want.

I don't know if you can just copy the site-package dlib folder into other installs - you can give it a try.

I tried again yesterday compiling both a wheel and egg for dlib. The builds succeed, but when I try to install them on another computer, they fail to import dlib properly with some missing DLL error.

I turned a 1 line .py program (import dlib) into a .exe file and ran through Dependency Walker... I am only getting the usual win-api complaints.

While the portable python install should work for most, it's kind of a halfway solution... users shouldn't have to download an entire installation to get dlib working.

Unfortunately, I can't figure out how to get a working wheel or egg to distribute.

I've been using setup.py bdist_wheel or bdist_egg with -global-install, etc. for the cuda options.

Maybe it requires some setup.py or cmake kungfu that is beyond me.

**Comment by frosty3907** [comment]
IT's all beyond me mate, thanks for your help :)

**Comment by MT-4ier** [comment]
@frosty3907 I have something that could be helpful if you still want to try and fix it. After doing some experimenting, I determined that I had my original dlib install file hanging around in the main site-packages folder. After removing that, cnn extract works normally for me.
(username)\envs\faceswap\lib\site-packages
The dlib installation should be in a subfolder of its own, and there might be a dlib file in that main folder that needs removing.
Although, since you have something that works, you don't have to mess around with this anymore if you don't want to. :)
