### ISSUE TITLE
Which Visual Studio version/components are required to be installed?

### ISSUE THREAD

**Issue by frosty3907** [deepfakes/faceswap-playground#95]
I cannot find this information detailed anywhere and suspect it may be why my build won't use the GPU for extraction/conversion.

**Comment by iperov** [comment]
building dlib in windows not so easy task.
You can use my prebuilt folder from here https://rutracker.org/forum/viewtopic.php?t=5519086

**Comment by kvrooman** [comment]
Visual Studio 2015 Update 3 with cudnn 7.05 and cuda 9.0 works for me

This guide on compiling your own version of tensorflow ( 1.6  ) also was
helpful
http://www.python36.com/install-tensorflow-gpu-windows/

**Comment by bryanlyon** [comment]
You will need to install Build Tools for Visual Studio 2017 (from https://www.visualstudio.com/downloads/ ) and cmake ( https://cmake.org/download/ ) to compile your own.  I recommend compiling your own on each system you use so that dlib compiles with all the accelerations for your that system.

**Comment by frosty3907** [comment]
@bryanlyon yep that's what I've already done. A few people today suggesting vs2015 so I'll give that a try next.

**Comment by frosty3907** [comment]
Do you guys mean: Visual Studio Community 2015 with Update 3 from here: https://my.visualstudio.com/Downloads?q=visual%20studio%202015&wt.mc_id=o~msft~vscom~older-downloads ?

**Comment by bryanlyon** [comment]
All you actually need is the build tools.  Down near the bottom of the this page: https://www.visualstudio.com/downloads/

**Comment by frosty3907** [comment]
Yep that's what I'd initially installed..

**Comment by bryanlyon** [comment]
You left a message about errors on another thread, I think you meant to have them here.  When you have Cuda installed, you shouldn't need to actually tell it that you have Cuda.  Just pip install dlib should be enough.  In fact, you should actually pip install -r the appropriate requirements.txt file based on what version of python you have installed (probably requirements-gpu-python36-cuda9.txt).

**Comment by frosty3907** [comment]
Yes I've done that too! Tried so many things and just getting different errors each time.

**Comment by bryanlyon** [comment]
What errors do you get with the normal pip install -r requirements...?

**Comment by frosty3907** [comment]
No errors on the last run - just tried it again and all req's are satisfied. I'm just getting incredibly slow extraction (and errors on convert last I tried, but trying to sort extraction out first).

**Comment by frosty3907** [comment]
hmm, a clue: 
after running git clone https://github.com/deepfakes/faceswap and then python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA in /dlib this time I noticed buried in the many pages of text: ***     c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/host_config.h(133): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions 2012, 2013, 2015 and 2017 are supported! [D:\faceswap\dlib\build\temp.win-amd64-3.6\Release\dlib_build\cuda_test_build\cuda_test.vcxproj]

**Comment by bryanlyon** [comment]
Hmm, maybe, also did you install cudnn 5 7 and 8 for Cuda 9?

**Comment by frosty3907** [comment]
I installed Cuda 9 (had 8 installed before, now uninstalled) and also CUDNN 7.0.5

**Comment by bryanlyon** [comment]
You can install any and all Cuda apis, they don't interfere with each
other, same as cudnn.  I just install any/all if them in shotgun style.

I am not sure what the problem with your GPU is.  Cudnn 5 and 8 will
probably be a good idea.

**Comment by frosty3907** [comment]
Do I need 5,7 and 8 as well?

**Comment by bryanlyon** [comment]
7 should be all, but it doesn't hurt.  Cudnn you can install all of them
once with no drawback..

**Comment by frosty3907** [comment]
Is there somewhere with a relatively up to date version pre-built? There was a russian site mentioned earlier but I'd prefer not to have to go translating instructions since it's hard enough as is.
Just about at the point of giving up here I've spent so much time trying to get this thing going.
Thanks for all your help by the way, much appreciated.

**Comment by deepfakesclub** [comment]
I posted this:
https://github.com/deepfakes/faceswap-playground/issues/86

It is a portable python install with all the dependencies you need for Win10/CUDA9

The faceswap version is pretty recent, but before the IAE and all that stuff. Since it is a full python installation, you can update the repo yourself. It seems that other people are able to run it, but one person who did a lot of crazy python installs before was not able to use it... WinPython may conflict with lots of global python environmental variables floating around, so suggested you remove other python installations and crazy stuff first to be safe.

If you are just desperate for faceswap, I also made an .exe self-contained version of faceswap a while ago in Mid-February.
https://mega.nz/#!3IBXVbTZ!V183qeUlkXbazZsgVTHhey9FD_D9egmRKsTfSFfQ4oE

This should run no matter what, I think, as long as you have CUDA9/cudNN7 and the VC redist.

I'm not sure, but I think you should be able to copy the site-package dlib from the WinPython install above (it is python 3.6)... and somehow transfer it to your own python environment. I briefly tried making a precompiled dlib wheel, but it didn't install correctly and I didn't have time to pursue that further.

**Comment by Clorr** [comment]
> I briefly tried making a precompiled dlib wheel, but it didn't install correctly and I didn't have time to pursue that further.
👍

**Comment by deepfakesclub** [comment]
I know right, seriously, no one over at the main dlib repo is posting Win10/CUDA wheels? Linux has tons of them posted... and I'm just an utter bdist/wheel noob.

**Comment by frosty3907** [comment]
@deepfakesclub using your portable winpython install seems to work! - has increased cnn extraction speed 100x 

So would this indicate that the issue is my winpython installation? or could it still be a result of any of the dependencies that you've included with your build?

**Comment by frosty3907** [comment]
So it looks like my issue is something to do with my VS install - I've tried heaps of different versions and variants on install. Could someone just confirm exactly what they download and check during the installs? Or is there some way to ensure all old installs are gone and aren't interfering?

I've installed/uninstalled 2017/2015.3 many times but each time during the installation process it asks which components I want so I'm never quite sure I'm getting the right requirements.

You only need the Build Tools right (I've tried both anyway)?
Does VS need to be installed before Cuda?

**Comment by deepfakesclub** [comment]
For VS, only install 2015. I can't remember exactly, but the C++ tools are all in one section. I usually add most of it (quite large). There may be some python tool section, which I also add (I don't think necessary, but I add anyways.) Finally there should be some SDK 10 part that needs to be checked. VS before/after CUDA, don't think it matters, but I install before CUDA.

If another dependency is missing, you should get an error. You can try copying the winpython site-package folders, and exchanging them (put the bad one in my winpython, the good dlib in your winpython). Not sure if that will work, but may tell you if the dlib is the problem or the environment.
