### ISSUE TITLE
Humble Bundle of AI books and videos.

### ISSUE THREAD

**Issue by bryanlyon** [deepfakes/faceswap-playground#96]
https://www.humblebundle.com/books/artificial-intelligence-books

It's a good bundle.  Packt does some good stuff.  It includes several books and videos that fit faceswap, including "Deep Learning for Computer Vision", "Artificial Intelligence with Python", "Deep Learning with Keras", and "Tensorflow Deep Learning Solutions for Images"

All of the books/videos should be easy to follow and the total cost is $15 for the whole bundle.

**Comment by feepdakenoob** [comment]
I grabbed it a few days ago. There's a lot of great stuff in this bundle. Thanks for sharing.
