### ISSUE TITLE
Only one image in 10 has face extracted & alignments saved. Can't convert back to video due to missing frames.

### ISSUE THREAD

**Issue by AreDubya** [deepfakes/faceswap-playground#97]
## Expected behavior

When performing extraction using the following switches, facial images and alignment data are extracted for each image.

```python Libraries/faceswap/faceswap.py extract -i /home/orw/faceswap/v2/video-in-1 -o /home/orw/faceswap/v2/video-in-1/extracted -f /home/orw/faceswap/v2/filter.jpg --serializer json -v -D cnn```

## Actual behavior

Images are extracted at a rate of 1 facial extraction per 10 images. Given full size images `008040.jpg, 008041.jpg, 008042.jpg, 008043.jpg, 008044.jpg` ..... etc, the program actually extracted these files : `008040.jpg, 008050.jpg, 008070.jpg, 008090.jpg, 008130.jpg`. 

## Steps to reproduce
The starting data set I am using is quite large - 38,084 images. 
Using a large number of images, run the extraction command above. 

Should I process smaller batches? Ideally, I would like to setup jobs and let them run overnight, but I could go smaller. Or is there a parameter anywhere that I could change?

## Other relevant information
- **Other related issues:** 
- **Operating system and version:** Ubuntu 16.04
- **Python version:** 3.5.2
- **Faceswap version:** 120535eb11b6d606d5c72d80c88c890aeff9eee2
- **Faceswap method:** GPU
-  absl-py==0.1.10
bleach==1.5.0
click==6.7
cycler==0.10.0
decorator==4.2.1
dlib==19.9.0
face-recognition==1.2.1
face-recognition-models==0.3.0
h5py==2.7.1
html5lib==0.9999999
Keras==2.1.2
kiwisolver==1.0.1
Markdown==2.6.11
matplotlib==2.2.0
networkx==2.1
numpy==1.14.1
opencv-python==3.3.0.10
pathlib==1.0.1
Pillow==5.0.0
pkg-resources==0.0.0
protobuf==3.5.1
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2018.3
PyWavelets==0.5.2
PyYAML==3.12
scandir==1.6
scikit-image==0.13.1
scipy==1.0.0
six==1.11.0
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.1
tqdm==4.19.6
Werkzeug==0.14.1

**Comment by torzdf** [comment]
I think you are misreading your extracted faces folder. The extraction appends a digit on the end relating to the number of faces it has extracted.

If you have a file 1234.png and it has one face in it, the extracted face will be:
12340.png

If it has 3 faces, the extracted faces will be:
12340.png
12341.png
12342.png.

I suspect that, in your example, you are looking at the output faces for frames:
00804.jpg
00805.jpg
00807.jpg
00809.jpg
00813.jpg

**Comment by AreDubya** [comment]
@torzdf That is what is happening, thanks for pointing it out! Feel a bit foolish for so thoroughly documenting the issue, but that's another story. Since I am using a filter, I wasn't even thinking of a facial identifier digit.

While the format explains some of my confusion, there are still large gaps between converted frames occasionally. A skip of 2 - 4 frames seems to happen quite often, and larger skips of 10 - 100ish images are happening frequently as well. The odd thing about the skips is that they happen in the middle of a section with an easily recognizable face. I haven't seen that before, in my experience once the program can find a face it will find it until there is a significant change. 

I am going to try this in smaller batches to see if that helps, and possibly stop using the filter to see if that gives more complete results. Maybe a single filter image doesn't give enough info for locating all faces? It has worked quite well for me up to this point though, so I don't want to point fingers.

**Comment by torzdf** [comment]
Are the faces rotated at close or further than 90 degrees? Dlib has problems recognizing faces not in an upright position.

If so, you can use the -r flag to try to find more faces (it will extract a bit slower)

**Comment by AreDubya** [comment]
In the original photos some are pushing that angle, I will give it a shot. I was impressed with the alignment of the extracted faces on this run, but you never know. I will let you know how it turns out. I'm setting up to run batches of increasing size and see if issues arise, I will try the -r flag on a pass as well. Thanks again!

**Comment by bryanlyon** [comment]
Also remember that you run convert on the original folder, not the aligned
folder.  It's normal to miss some faces if they turn away or something like
that, since the face recognition is looking for a full face.  When you run
the convert though, it will copy the unchanged frame over (unless you tell
it to skip unchanged frames).  So that it will let you recombine into a
video.

**Comment by AreDubya** [comment]
@bryanlyon I've done this successfully several times now, but this re-combination has been surprising. Although I do like your idea of somehow running the model back against the extracted face only, there might be a painting-of-a-painting-of-a-painting effect to be had there. Or a bunch of white. 

@torzdf Thanks for pointing me in the right direction.

I am going to chalk this up to a combination of a couple things, but mainly to being a bit under the quality threshold for reliable filter usage. I am not sure about the memory issue, but I will run some tests. And work with more reasonably sized batches.

**Comment by AreDubya** [comment]
I hate to comment on an open issue, but on closer inspection the larger gaps were just that the filtering by the specified `-f` image didn't work for several blocks of time. I'm not sure why, in my estimation I have seen it detect more specifically, but maybe something about this image set doesn't work. Thanks again for the input.
