### ISSUE TITLE
How to nerf your ganked python install and start over?

### ISSUE THREAD

**Issue by frosty3907** [deepfakes/faceswap-playground#99]
Winpython 3.6.2
OK been trying for days to get faceswap working (issues with speed and errors during extraction and conversion) and at this stage I'm just going to start over because I've tried everything and nothing's working and I assume there's too much crap installed to make any conclusions anymore.

I tried creating a new virtualenv but I noticed when installing the requirements it said all requirements were already satisfied so I guess they're kept in a common directory.

So my question is how do we get a clean slate to work from and try again?

**Comment by torzdf** [comment]
I believe that you can clear out the pip cache dir and try again. On windows it's located: %LocalAppData%\pip\Cache

**Comment by deepfakesclub** [comment]
Winpython is self-contained, so you just delete the parent winpython directory.

It's the other ones, like conda, that get deep into your system. Look out for "Anacdona3" folders, etc. that may still remain.

**Comment by frosty3907** [comment]
I used setenv (forget the parent app name) instead of anaconda, I think they're the same things?
So uninstall winpython should take out all the user folders etc?

**Comment by deepfakesclub** [comment]
Yes, just double check that you delete the winpython folder where you installed it. Winpython is meant to be portable, so it uses custom paths and puts everything into the main folder. You're supposed to be able to copy it to any computer and run it immediately.
